### ISSUE TITLE
Multiple results list - show state, indent second line of machine name

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1001]
Assigning thy self. 

Huh, not really possible to indent second line, because all the machines are within a single `li`. Perhaps we can nest them in a fresh ul li.

**Comment by RyanTG** [comment]
Stuck here. I want to change this line: https://github.com/scottwainstock/pbm/blob/master/app/views/locations/_locations.html.haml#L81
from a `.join` to an `each` array so that each one can be a list item. And I'm not sure about the syntax. I've tried about 20 variations of:

```l.machine_names.each do |machine|
      %li l.machine_names```

**Comment by scottwainstock** [comment]
@RyanTG Did you do it like this?

```
- l.machine_names.each do |machine|
  %li #{machine.html_safe}
```
That prefixed "-" tells haml to treat the code after it as "non display" stuff... like looping.

**Comment by RyanTG** [comment]
I did try a number of variations that started with `-`. But I was still doing something else wrong. I didn't have `html_safe` for one. ANYWAY, this works! You're a genius.

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/commit/c368d6908002875295a1412537831cab73f0cfac
