### ISSUE TITLE
Profile Page - List only the top 50 locations edited

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1007]
Right now it lists all. And to be honest, that's simply excessive. CUT IT DOWN.

**Comment by scottwainstock** [comment]
@RyanTG Top 50 means last 50?

**Comment by scottwainstock** [comment]
@RyanTG And is this for the APP or the website?

**Comment by RyanTG** [comment]
Oops, yes _last_ 50, not top 50.

I'd say for both! This issue was specifically targeted at the website. I think I even crashed the site once loading my profile.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/7201bc9c3f9c5521fd329e9a79598678ec797584

@RyanTG This code shows the locations edited from your last 50 edits... so if you touched a place 50 times, you'd have one location on your list. Not EXACTLY what you asked for, but it's a lot less complicated and easier on the DB. Let me know if this won't work. Scores should be last 50 scores.

**Comment by RyanTG** [comment]
Yeah, that seems fine. 

My list is surprisingly short, but I must have added multiple machines at each of these places.

https://pinballmap.com/users/pbm/profile

**Comment by RyanTG** [comment]
Right now, this is not only showing the top 50 locations edited (`List of Locations Edited (with your last 50 updates):` ), but the `Locations Edited` value is only the top 50 (or less if you've done multiple edits to a machine).

So like, right now my profile says
````
22
Locations Edited
List of Locations Edited (with your last 50 updates): O'Brian's Tavern
Gorman Winery Hollywood Hill Tasting Room
Spring Lake Arcade
TotalErg
The Burl Arcade
Blue Cross RiverRink
Z82 Retrocade (Vortex)
Fun-O-Rama
Yahooligans Bar & Grill
Timezone VivoCity Flagship Store
Silver Beach Carousel
Wacky's
Crowne Plaza Ventura Beach
TotalErg
Pacific Pinball Museum
Il Chiosco di San Feliciano (The Kiosk of San Feliciano)
Galactic Comics
DailyPint
The Baxter 
````

But I'd prefer it if it said:
````
920
Locations Edited
List of Locations Edited (with your last 50 updates): O'Brian's Tavern
Gorman Winery Hollywood Hill Tasting Room
Spring Lake Arcade
TotalErg
The Burl Arcade
Blue Cross RiverRink
Z82 Retrocade (Vortex)
Fun-O-Rama
Yahooligans Bar & Grill
Timezone VivoCity Flagship Store
Silver Beach Carousel
Wacky's
Crowne Plaza Ventura Beach
TotalErg
Pacific Pinball Museum
Il Chiosco di San Feliciano (The Kiosk of San Feliciano)
Galactic Comics
DailyPint
The Baxter 
````

**Comment by RyanTG** [comment]
I'ma reopen. Please see the previous comment.

**Comment by scottwainstock** [comment]
@RyanTG Where'd you get 920 from? I get 525. Just want to make sure I didn't mess up the code.

**Comment by RyanTG** [comment]
I wasn't lying, per se. I just didn't know what the value SHOULD be! All I was seeing was 22. But 920 sounded right to me. I overestimated.

Closing. Thank you!
