### ISSUE TITLE
Support for different kinds of apostrophes

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1012]
Different keyboards type different types of apostrophes. So, on iOS browser, the apostrophes are curly, but in our data they’re straight. This seems crazy... but here we are. We need to find a way so that if someone searches for a name that contains an apostrophe, it’ll always work. 

Location example: Rio’s Pizza. 

I’m writing this from my phone, and as you can see (hopefully, unless github changes it upon submit) it’s a curly apostrophe. 

If this isn’t clear, I can explain it better.

**Comment by scottwainstock** [comment]
This should do it: https://github.com/scottwainstock/pbm/commit/7208e462d7790e334a35a479c83452b207835b41

**Comment by RyanTG** [comment]
Kind of works. Remaining issue is that when you type in a location name that has an apostrophe on your phone, the autocomplete doesn't work.

Steps (do these on mobile and desktop to see the difference):
- Visit https://pinballmap.com/regionless
- Location search
- Type in `rio's pizza`

Result: On desktop, it's fine. The autocomplete works. On mobile, it stops autocompleting at `rio'` because you've typed in the wrong apostrophe (because the apostrophes on the iOS keyboard are a different style).

**Comment by scottwainstock** [comment]
How about this. https://github.com/scottwainstock/pbm/commit/33ac28b5db7a06e5bf495205f5265a7995e4025f

**Comment by RyanTG** [comment]
Sick!
