### ISSUE TITLE
Super admin: Daily digests of comments/removals for ALL regions

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1017]
One email each (one for comments, one for removals), that contains ALL locations.

**Comment by scottwainstock** [comment]
@RyanTG You say "for ALL regions" and "One email each (one for comments, one for removals), that contains ALL locations".

Is this supposed to include regionless locations AND regioned locations?

**Comment by RyanTG** [comment]
Yeah. I figure super admins might as well see everything. If you think that’s not a good idea, then the emails can only show regionless locations.

**Comment by scottwainstock** [comment]
This should do it: https://github.com/scottwainstock/pbm/commit/d3864368ed424eac4a0a88dafafaf18beeaf7a89
