### ISSUE TITLE
Dockerize app

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#1024]
Prep for AWS deployments.

**Comment by RyanTG** [comment]
Is it dockerized? @bpoore did you make that docker version, or did someone else make it and you installed it?

**Comment by bpoore** [comment]
I was using the docker-compose file in this repo I was playing around with getting the dockerized app on my machine. The current docker-compose file needs to be edited to reflect the newer version of Ruby y'all have updated to for it to work at this time though. I'm not sure what is missing for AWS deployments, but I was able to get the app running via docker on my machine- I just wasn't able to figure out how to run the test suite as of yet.

**Comment by Jengah** [comment]
Unless there is anything else you envisioned for this particular issue, it should be closed as of https://github.com/scottwainstock/pbm/pull/1191
