### ISSUE TITLE
Bug: website showing incorrect current status

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#1030]
Message: Tried to update several machines that I repaired and the site will not let me. All of a sudden comments from 2 years ago are showing up as well stating that working machines are broken.

**Comment by scottwainstock** [comment]
Copied the live database to my machine and I see the CORRECT sort order. So that's weird!

<img width="1321" alt="screen shot 2018-08-15 at 8 07 36 pm" src="https://user-images.githubusercontent.com/179757/44185059-fccc0d00-a0c6-11e8-97bd-3a8910402a36.png">

**Comment by RyanTG** [comment]
Only for Guardians. The Family Guy ones are still out of order.

**Comment by scottwainstock** [comment]
Looks like my DB dump was 15 hours old... here's one I generated manually:

<img width="841" alt="screen shot 2018-08-15 at 8 13 52 pm" src="https://user-images.githubusercontent.com/179757/44185214-d5c20b00-a0c7-11e8-96b9-3c90f1590e0f.png">

**Comment by scottwainstock** [comment]
```
scottwainstock@Scotts-MacBook-Pro ~/work/pbm (enhancements) $ heroku run bundle exec rails c -a glowing-dusk-5085
Running bundle exec rails c on ⬢ glowing-dusk-5085... up, run.7331 (Hobby)
[tunemygc] not enabled
   (1.5ms)  SELECT COUNT(*) FROM "regions"
  Region Load (8.1ms)  SELECT "regions".* FROM "regions"
   (1.6ms)  SELECT COUNT(*) FROM "regions"
  Region Load (3.4ms)  SELECT "regions".* FROM "regions"
Loading production environment (Rails 5.2.0)
irb(main):001:0> LocationMachineXref.find(18094).machine_conditions.last
  LocationMachineXref Load (1.5ms)  SELECT  "location_machine_xrefs".* FROM "location_machine_xrefs" WHERE "location_machine_xrefs"."id" = $1 LIMIT $2  [["id", 18094], ["LIMIT", 1]]
  MachineCondition Load (1.5ms)  SELECT  "machine_conditions".* FROM "machine_conditions" WHERE "machine_conditions"."location_machine_xref_id" = $1 ORDER BY "machine_conditions"."id" DESC LIMIT $2  [["location_machine_xref_id", 18094], ["LIMIT", 1]]
=> #<MachineCondition id: 35187, comment: "Works Great! Stewie is ready to take over the worl...", location_machine_xref_id: 18094, created_at: "2018-08-15 22:02:39", updated_at: "2018-08-15 22:02:39", user_id: 2305>
irb(main):002:0>
```

**Comment by scottwainstock** [comment]
iOS app:
![image-1](https://user-images.githubusercontent.com/179757/44185720-04d97c00-a0ca-11e8-8525-0b0a383c22ad.jpg)

**Comment by scottwainstock** [comment]
@RyanTG TRULY weird.

**Comment by scottwainstock** [comment]
Sopranos: https://pinballmap.com/portland/?by_location_id=909

**Comment by scottwainstock** [comment]
https://pinballmap.com/pittsburgh/?by_location_id=4410

**Comment by RyanTG** [comment]
From what I can tell so far, this began some time between Aug 1 and Aug 4. I gathered that from looking at Portland submissions. Could look at another region, and narrow it down further.

**Comment by RyanTG** [comment]
Narrowed it down further. The issue began in between:

**WORKING**
````
August 03, 2018 03:10 (submission ID: 68300)
User ZipperFlipper (xx@xx) commented on The Simpsons at Pizza Planet. They said: Plays fine, but you can't read the displays. 50c or 3 for a dollar 
- https://pinballmap.com/ca-valley/?by_location_id=8628
- https://pinballmap.com/admin/user_submission/68300
````
**STOPPED WORKING**
````
August 03, 2018 03:23 (submission ID: 68301)
User lordhowardhurtz (xx@xx.com) commented on White Water at Cidercade - Bishop Cider. They said: Insanity Falls switch not registering 
- https://pinballmap.com/dfw/?by_location_id=7907
- https://pinballmap.com/admin/user_submission/68301
````
I'm guessing those are server times and don't correspond to actual times.

Also, that place is called Pizza Planet. I wonder if Hidden Mickeys knows about it (I haven't listened to the latest episode).

**Comment by scottwainstock** [comment]
Pretty sure it's this, but also I have no idea why it'd be this: https://github.com/scottwainstock/pbm/commit/3d0b2a2dd90d7854509ad7f02f7f92a38202a372

**Comment by scottwainstock** [comment]
It was not it.

**Comment by scottwainstock** [comment]
I think this fixed it: https://github.com/scottwainstock/pbm/commit/eb43cb9c4a6eb1ec9ba2cf12cb57a35f241a8184

@RyanTG Can you confirm?
