### ISSUE TITLE
Additional query parameters to closest_by_lat_lon API endpoint needed

### ISSUE THREAD

**Issue by bpoore** [scottwainstock/pbm#1035]
In order to support the regionless concept for the phone app, the closet_by_lat_lon route needs additional query parameters. 

Specifically we need: 
-machine id
-location type
-# of machines
-operator?

I understand there currently isn't a way to query operators with regionless. From what I can tell, that is also a lower priority at the moment.

<img width="740" alt="screen shot 2018-08-19 at 8 43 27 pm" src="https://user-images.githubusercontent.com/7720282/44352657-d22cdc00-a459-11e8-9c5c-098852bbdb12.png">

**Comment by scottwainstock** [comment]
@bpoore How's this? https://github.com/scottwainstock/pbm/commit/019313f512e0e18accc4e319eb82b47cd7465733
