### ISSUE TITLE
Regionless NEAR search - don't throw "Not Found" message if no locations are found

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1038]
First: We don't know if that's what is happening. So test this:

- Search in the NEAR field, such as "Knoxville, TN"
- Determine if the geocode worked, and if the "Not Found" error message occurs because there are no locations within 5 miles of the knoxville centroid.

If that's the case, then we don't ever want to show the "Not Found" after a successful geocode. If there are no locations in the extent, then we should instead just say "0 Locations in Results"

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/6b6f9249392c20f697aede8f65356d78d5bccd9e

**Comment by RyanTG** [comment]
1. If a Near search results in 0 locations, still geocode the search so the map shows the area they want to see (and they can then toggle on the "redo" option and browse around.
2. If there's only 1 result, don't show the "1 Locations in Results" text. But if there are 0, then it's ok to show "0 Locations in Results."
3. If they put `foo` in _any_ search field aside from Near, then show the Not Found error. This includes:
-- Machine on Regionless
-- Machine on region
-- Location Regionless
-- Location on region

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/1825548d178579069ee288039d474fcb761288fb
