### ISSUE TITLE
"Original" size pictures are too large! Create a new size called Large, max width 800px

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1044]
### **Context:**

This is about user-uploaded photos. The "original" size images open up when users click the photo thumbnail in Location Details. The "original" images are usually around 5mb. And I think that's _too big_. We don't need a 5mb image - it takes a while to open/download, and it's enormous.

But the "medium" size is too small, so we need something in between.

### **Goal of this Issue**

This is the paperclip code we're using to create different image sizes: https://github.com/scottwainstock/pbm/blob/c66c9fd88db704e34d7ae555feb9ac25f3822728/app/models/location_picture_xref.rb

Note this:

````
styles: {
                      thumb: '36x25>',
                      medium: '300x300>'
},
````
**_Can we:_**
**- Add a new style to this? like `large: "800x800>"`**
**- And then go back and process all our existing images to that?**

### **side notes**

We use Paperclip: https://github.com/thoughtbot/paperclip

I dunno if we'd want to switch to something like CarrierWave, which I think has more options: https://github.com/carrierwaveuploader/carrierwave

and there's also Refile: https://github.com/refile/refile

Comparison of the three gems: https://infinum.co/the-capsized-eight/best-rails-image-uploader-paperclip-carrierwave-refile

**Comment by scottwainstock** [comment]
https://stackoverflow.com/questions/2977234/resize-existing-images-to-new-style-in-paperclip-rmagick

**Comment by scottwainstock** [comment]
Ran: rake paperclip:refresh:missing_styles

And pushed: https://github.com/scottwainstock/pbm/commit/cd40fad77b1ad7fe043d7b8b84f6171751b35dd3

**Comment by RyanTG** [comment]
Seems like they were not generated for all pictures. See https://pinballmap.com/la?utf8=%E2%9C%93&region=la&by_location_id=6784

**Comment by scottwainstock** [comment]
Weird. I ran this from my dev machine, and I think I'm only a couple days out of sync with live... I'm running it again on live.

```heroku run bundle exec rake paperclip:refresh:missing_styles -a glowing-dusk-5085```

**Comment by scottwainstock** [comment]
https://pinballmap.com/la?utf8=%E2%9C%93&region=la&by_location_id=6784 appears to work now... so hopefully when this run completes, we'll be good.

**Comment by scottwainstock** [comment]
Oh wait it's just the thumbs that work... whoops. Well, we'll see tomorrow.

**Comment by RyanTG** [comment]
That particular location has some that I uploaded yesterday. The owner emailed them to me for some reason. 

We were also missing some medium sizes here and there (we had an issue for it, but I closed it recently for no reason), so it’s cool that this command will fix all those, too.

**Comment by RyanTG** [comment]
Awesome!
