### ISSUE TITLE
Daily ALL locations comments/removals emails did not come through

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1054]
Not sure if it was a one-time problem. But, just noting it here.

We recently removed a bunch of admins, which made some regions admin-less. I _thought_ that we had a couple admin-less regions already, prior to the Purge. But perhaps not, and perhaps the admin-less regions are messing up the ALL locations emails. I don't see why they would - but who knows!

**Comment by scottwainstock** [comment]
3 days later... do we think this is still a thing?

**Comment by RyanTG** [comment]
Yes, still a thing. I haven’t gotten them.

**Comment by scottwainstock** [comment]
Sync'ed my dev db with what's in live. Ran the command. Shows that two of my email addresses and your fastmail account should receive an email.

I'm going to try running things in live to see if it throws an error.

**Comment by scottwainstock** [comment]
```  User Load (2.1ms)  SELECT "users".* FROM "users" WHERE "users"."region_id" = $1 ORDER BY users.id  [["region_id", 24]]
rake aborted!
ArgumentError: SMTP To address may not be blank: []```

Blank Nebraska admin seems to be breaking it. I'll add a fix. Weird that it doesn't seem to blow up on dev.

**Comment by scottwainstock** [comment]
This should do it: https://github.com/scottwainstock/pbm/commit/574d852352c1d8738b5cafda8a0d702bdfc24156

**Comment by RyanTG** [comment]
Thanks!
