### ISSUE TITLE
Are we experiencing any problems with the IFPA Calendar pulls?

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1055]
A business owner in Milwaukee has noted that his events aren't showing up on the Wisconsin events page. 

So I'm checking to see if we've experiencing any problems pulling the IFPA Calendar data.

The lat/lon for the Wisconsin region is _not_ in Milwaukee, so at first I thought the issue was that his events were too far from that lat/lon. Buuuuut, we have other Milwaukee events listed, and we are also showing events that are even further away, like in Chicago.

Here is one his events https://www.ifpapinball.com/tournaments/view.php?t=25918#

**Comment by scottwainstock** [comment]
I think this has been broken since the Ruby upgrade. Fixing.

```
glowing-dusk-5085::HEROKU_POSTGRESQL_COBALT=> select max(created_at) from events;
            max
----------------------------
 2018-08-21 18:40:29.075607
```

**Comment by scottwainstock** [comment]
It looks like the IFPA feed dropped a "calendar_id" field. Our importer expects this. So, I'll rework the importer I guess.

```
{"tournament_id"=>"25918", "tournament_name"=>"Bounce Milwaukee monthly pinball tournament", "event_name"=>"Main Tournament", "city"=>"Milwaukee", "state"=>"WI", "country_name"=>"United States", "country_code"=>"US", "average_players"=>"18", "average_points"=>"2", "start_date"=>"2018-09-21", "end_date"=>"2018-09-21"}
```

**Comment by scottwainstock** [comment]
This is the endpoint we hit... and it says it should be sending calendar_id:

GET /calendar/active
https://www.ifpapinball.com/api/documentation/calendar/

**Comment by RyanTG** [comment]
Brian noted:

> I re-added the calendar id field.  The output will contain no longer has the ECS/PAPA stuff and has some new content.

But we're still missing events (I've discovered his simply by looking at the https://www.ifpapinball.com/calendar/ around Milwaukee, and then comparing that with our Wisconsin events calendar).

**Comment by scottwainstock** [comment]
Confirmed that the feed is fixed. Found some new bugs in the script (post some kind of gem upgrade). Upgraded ruby too.

Run the importer manually, seems to have worked. (?)

**Comment by RyanTG** [comment]
Seems fixed!
