### ISSUE TITLE
How many location names are state abbreviations?

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1057]
I don't know how/why this is happening. The most obvious answer is "user error" - and that user is me. But I _really_ don't think I would be manually changing the location name to be the state abbreviation.

So for now, I want to monitor this. And the first step is to do a select that is:

`show us location names that are only two characters long.` If there are any, they might be state abbreviations instead of the actual location name.

**Comment by scottwainstock** [comment]
```
glowing-dusk-5085::HEROKU_POSTGRESQL_COBALT=> select r.name as region_name, l.name as location_name from locations l left outer join regions r on r.id = l.region_id where length(l.name) = 2 order by 1, 2;
 region_name | location_name
-------------+---------------
 wisconsin   | BP
(1 row)
```

**Comment by RyanTG** [comment]
Ah, thanks. That's a gas station, so it's legit.
