### ISSUE TITLE
Move to mapbox

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#1058]
Google is too $$$$.

**Comment by RyanTG** [comment]
Notes about the map controls. I haven't seen it yet. But the issue of the missing controls may be due to this negative margin: https://github.com/scottwainstock/pbm/blob/master/app/assets/stylesheets/application.css.scss.erb#L2187 and the 100% width on the #map div (just above that in the css).

**Comment by scottwainstock** [comment]
@RyanTG https://github.com/scottwainstock/pbm/tree/mapbox

Tests all pass for this... only thing that I know for sure doesn't work is "center map on marker when you click on it".

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/9c44c59094a3012922aa352547e48613750cfdc3

**Comment by scottwainstock** [comment]
```remote:        Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).```
