### ISSUE TITLE
Add "Forgot password" and "resend confirmation" to the API so we can use in the app

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1091]
Both should accept either username or email address.

And if not found, then there should be a message saying so.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/5f993a116853bec2da820e27811a56dcced137c8
https://github.com/scottwainstock/pbm/commit/8f2160276775c32a678ef7385eadcdc6d0bac1bb

@bpoore Those should do it.

**Comment by bpoore** [comment]
I got the screens made up and they are working. I noticed the username / email are case sensitive- is this intentional/desired? I found it confusing at first not realizing my go-to username on staging is lowercase.

**Comment by scottwainstock** [comment]
I can make it case insensitive. That wasn’t intentional.

**Comment by RyanTG** [comment]
Note that we made it case insensitive on the website https://github.com/scottwainstock/pbm/issues/706

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/e233b4f0ebb90b7d9492b799dac4c651d684be98

**Comment by RyanTG** [comment]
thx
