### ISSUE TITLE
API Endpoint for SAVED

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1093]
So on the app, users can favo locations.
````
Probably a new table.
With user_id/location_id pairs.
And then endpoints to create/delete them.
````

**Comment by scottwainstock** [comment]
Should do it.

https://github.com/scottwainstock/pbm/commit/634e1f7c9ea371436613655f7ff41c118203f239

**Comment by RyanTG** [comment]
I'm not the one to review this. tagging @bpoore
