### ISSUE TITLE
API Endpoint for Nearby User Submissions

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1094]
The app will have a feed showing all the nearby recent activity.

machine add
machine removed
confirmed
comments
scores
updated metadata

**Comment by scottwainstock** [comment]
@RyanTG @bpoore How are you picturing this data coming back from the API? Seems like the formatting would be different for each "type" of activity. Is it enough to put the main payload of data in a blog, but have a separated link to the location being discussed? EG:

[
{ location_id: 123, type: "machine_add", desc: "Blah blah was added" },
{ location_id: 456, type: "machine_removed", desc: "blah blah was removed" },
{ location_id: 456, type: "confirmed", desc: "foo bar was confirmed" },
{ location_id: 789, type: "comments", desc: "COMMENT was added to MACHINE" },
{ location_id: 789, type: "scores", desc: "High Score of 123 was recorded on MACHINE" },
{ location_id: 789, type: "updated_metadata", desc: "??????" },
]

Not sure what the idea with the last one is... what kind of metadata would people want to be updated about? How would we format that in the desc field?

**Comment by RyanTG** [comment]
That seems good to me. But Beth has final say. 

The final result will be things  like, “John added pirates of the Carib
to high score. Date.”
For metadata, I was thinking it would say “updated the phone number” or
“updated the website”. Just a generic message. But, if it’s too much to
separate those out in order to highlight the actual field that was
updated, then we can skip metadata.



On Sat, Nov 17, 2018, at 1:34 PM, Scott Wainstock wrote:
> @RyanTG[1] @bpoore[2] How are you picturing this data coming back from
> the API? Seems like the formatting would be different for each "type"
> of activity. Is it enough to put the main payload of data in a blog,
> but have a separated link to the location being discussed? EG:> [
>  { location_id: 123, type: "machine_add", desc: "Blah blah was
>  added" },>  { location_id: 456, type: "machine_removed", desc: "blah blah was
>  removed" },>  { location_id: 456, type: "confirmed", desc: "foo bar was
>  confirmed" },>  { location_id: 789, type: "comments", desc: "COMMENT was added to
>  MACHINE" },>  { location_id: 789, type: "scores", desc: "High Score of 123 was
>  recorded on MACHINE" },>  { location_id: 789, type: "updated_metadata", desc: "??????" },
>  ]


> Not sure what the idea with the last one is... what kind of metadata
> would people want to be updated about? How would we format that in the
> desc field?> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].

Links:

  1. https://github.com/RyanTG
  2. https://github.com/bpoore
  3. https://github.com/scottwainstock/pbm/issues/1094#issuecomment-439649230

**Comment by scottwainstock** [comment]
@RyanTG @bpoore What's the date range on activity? Stuff in the last week?

**Comment by scottwainstock** [comment]
@RyanTG @bpoore I added this so we can start playing around with results:
https://github.com/scottwainstock/pbm/commit/be9b0f86b1be88f74f5f715e2aa1aa0d14543337

It's live now.

There is NO date range on activity right now, so you'll get user submissions from since the time we added users submissions. I'm sure that'll be too much data.

I left the formatting "rails-like"... meaning we get all the object data from UserSubmissions back. It's cleaner in the code, but will likely require reformatting on the app side? Maybe. Let me know if it's too much reformatting and I can take over that duty in the API.

**Comment by RyanTG** [comment]
Jesus, commenting on issues via email is NOT reliable. Just realized that my response to you never came through. But here it is:

> That’s kind of tough because some areas will not be busy, and some will be super busy. I was envisioning limiting the number of results to 20 or so (but also being able to filter results to only one type of submission, and if filtered then still show 20 of just that type... maybe that’s an ill idea). I hadn’t thought of a date range. How about one month? We can discuss about this in chat.

**Comment by scottwainstock** [comment]
We haven't discussed about this... but I'll assume 1 month default and have it be a variable to the endpoint.

**Comment by scottwainstock** [comment]
Added 1 month default (and filter)... and type filter. @bpoore , let me know if you need anything else.

https://github.com/scottwainstock/pbm/commit/2f2d57cff9c347e9f82d6e2650531349732c1af9

**Comment by RyanTG** [comment]
Once this issue is resolved, https://github.com/scottwainstock/pbm/issues/912, please add photo uploads to this endpoint (maybe that happens automatically).

**Comment by bpoore** [comment]
I need to get my github notices from this repo worked out. I'm sorry I've missed all these discussions. Having the `type` seems good. I'll get to work on this screen and let you know if I have any questions / what comes up.
