### ISSUE TITLE
Rails Admin - filtering Locations by Zone "Is Blank" results in an error

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1095]
Steps:

- https://pinballmap.com/admin/location
- Add Filter > Zone
- choose "Is Blank"

https://pinballmap.com/admin/location?model_name=location&utf8=%E2%9C%93&f%5Bzone%5D%5B21143%5D%5Bo%5D=_discard&f%5Bzone%5D%5B21143%5D%5Bv%5D=&query=

**Comment by scottwainstock** [comment]
@RyanTG I had to do this like I did the admin/non-admin thing on the User page. There's now a "regionless" button to hit on the locations lookup page (rather than a filter).

https://github.com/scottwainstock/pbm/commit/b75ee1e4e8ea6973362a6f6bf58ef4aa176400c0

**Comment by RyanTG** [comment]
Cool! Thanks.
