### ISSUE TITLE
User can add favorite location multiple times

### ISSUE THREAD

**Issue by bpoore** [scottwainstock/pbm#1098]
POSTing multiple times to `/api/v1/users/:id/add_fave_location.json` with the same location will add the location to the user's favorite locations. All favorite locations associated with any user should be unique.

**Comment by scottwainstock** [comment]
This should do it.

https://github.com/scottwainstock/pbm/commit/dc74bd554f3da3aeed78733ad3ae52457beaa239

**Comment by bpoore** [comment]
Looks great. Thank you!
