### ISSUE TITLE
Include fields specific to location in user favorite request

### ISSUE THREAD

**Issue by bpoore** [scottwainstock/pbm#1099]
We would like to add a list view screen to the mobile app showing details specific to locations a user has saved. To do this, we can save on multiple requests if we can get the following fields for each location in a request to `GET /api/v1/users/:id/list_fave_locations.json`:
location name,
lat,
lon,
street, 
state, 
zip,
machines,
location type

<img width="420" alt="screen shot 2018-11-16 at 12 10 13 pm" src="https://user-images.githubusercontent.com/7720282/48645363-52e86f00-e99a-11e8-9ce7-57ede5dc55fb.png">

**Comment by scottwainstock** [comment]
This should do it:
https://github.com/scottwainstock/pbm/commit/71280fc28b29db2a78bb6c429af1d3185865d4ac

**Comment by bpoore** [comment]
Awesome. Thanks!
