### ISSUE TITLE
Profile - only show TOP score for each machine id

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1101]
On the app, we would like the Profile page to list only a user's TOP score for each machine. For example, if a user has inputted 3 scores on 3 different LMXs that share the same M, then the profile would only list the top one for that M. 

So this issue is (I think) for an API endpoint to allow for that.

And we should also implement that functionality on the website profile, too.

**Comment by scottwainstock** [comment]
@bpoore What's the endpoint you're currently calling for this?

**Comment by scottwainstock** [comment]
This should do it for mobile AND website profiles:
https://github.com/scottwainstock/pbm/commit/d315c72de8633e50670ff73178bd5ac210827130

**Comment by bpoore** [comment]
@scottwainstock, I'm currently calling `/users/${id}/profile_info.json`. 

This currently isn't properly grabbing the highest machine for a given machine on location. On the dev server, you can see lmx 18830 has a high score for bap2018 of 123,451,234, but the response coming from the request to `/users/130/profile_info.json` is coming back with a high score of 500.
