### ISSUE TITLE
Include lmx info at the location level query? 

### ISSUE THREAD

**Issue by bpoore** [scottwainstock/pbm#1103]
@scottwainstock @RyanTG 

On the equivalent of the location list screen in the current app, we're not displaying the machines on location: 

![img_4081](https://user-images.githubusercontent.com/7720282/49054730-0f67df00-f1aa-11e8-801f-d5273bbd2f7d.jpeg)

For our new location list screen, we are including up to 5 machines on location. When a machine is added or removed from a location, we are dealing with lmx data, but the data from `GET /api/v1/locations/closest_by_lat_lon.json` lists machines at a location by `machine_names: []`. Unless we do a new request to `GET /api/v1/locations/closest_by_lat_lon.json` after adding or removing a machine, there's no really straightforward way for me to do the comparisons I need to do to update the list. I can trace the lmx to the machine #, but there, the machine name is not in the same format as the name from machine_names.
<img width="449" alt="screen shot 2018-11-26 at 6 34 47 pm" src="https://user-images.githubusercontent.com/7720282/49054706-fa8b4b80-f1a9-11e8-8d35-1a7d309944d0.png">

I'd just like to get an idea of how is best to proceed and what would be easiest from the API end to support this feature if there's anything that can be done to make the comparisons I need to be more straightforward. If I can consistently count on taking the `name`  (`manufacturer`, `year`) from `GET /api/v1/machines.json`, I think I _could_ make this happen from my end, but there will be quite a few comparisons to make to make this happen. Does this sound like the best approach at this time? I imagine we don't want to make too many changes to the locations array since the existing apps are counting on the data structures there.

**Comment by scottwainstock** [comment]
This adds a machine_id array to the closest_by_lat_lon endpoint: https://github.com/scottwainstock/pbm/commit/de4f5ac59d814408b1c9bbb0b3c67f196028d6c6

**Comment by bpoore** [comment]
@scottwainstock, will the indices in the `machine_id` array always match up with the `machine_name` array? Having these as two separate arrays, when checking which machine to remove from a location coming in with a machine number, I want to be sure to remove the right machine name from the list.

**Comment by bpoore** [comment]
@scottwainstock, sorry to be a PITA, but I came up with a workaround to not have to query parallel arrays by adding to the app state for machines to have a field of `name (manufacturer, year)`.  With this added to the machine info, I can do a direct string comparison. Sorry I didn't think to do that at first.
