### ISSUE TITLE
The "Operator" field when editing a Location isn't a dropdown

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1106]
I've confirmed this occurs with the super admin and regular admins.

When editing a location or a suggested location, the operator field isn't a dropdown, but is instead the plus/minus button. This occurred right after I added a regionless operator (Ace Music Co).

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/098a2039af65561c4da1f12d1ad198247be85b91

**Comment by RyanTG** [comment]
thx
