### ISSUE TITLE
Operators are not receiving all daily digest emails

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1115]
Sometimes the daily digest emails are sent. Sometimes they are not sent.

My wild thoughts:
- Could the "regionless" operators be affecting things? seems unlikely...
- I removed a few operators that had really invalid emails. No idea if the script was hitting those and failing - but that seems unlikely.
- Or could it be related to how some regions don't have admins...

**Comment by RyanTG** [comment]
Latest idea to check: perhaps it's not grabbing the past 24 hours.

File to check: https://github.com/scottwainstock/pbm/blob/12c12b6127d0ad03d3fe1a209d093b9bb4e3fbfb/app/models/operator.rb

Should it use this https://github.com/scottwainstock/pbm/blob/73c909765b40613bcf2867a38ffbef721717b4e1/app/models/region.rb#L154 definition of start_of_day rather than `Time.now.beginning_of_day`?

And why is the task in `pbm/app/models/operator.rb` while all the others are in `pbm/lib/tasks/`? It's probably irrelevant, but it stood out to me.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/0a4f639f01fd2e15a90a640765e7090204870824

We should know if this worked in ~2 days.

The work of the task is mostly done in the model because it's easier to test the model (with unit tests) than the task itself (with integration tests).

**Comment by RyanTG** [comment]
Thanks. I can't really test this. So I'll just close it and see if someone complains.
