### ISSUE TITLE
Admin: remove phone validation when editing/promoting; make State not required

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1118]
1. The phone validation is causing issues with non-US locations. Can we remove it, so that when you edit a location in Rails Admin, it no longer validates the number?

There aren't any errors when you edit a number via the map itself, so maybe it doesn't validate at that stage? If it DOES validate at that stage, then it's ok to leave it on there if possible.

2. I got feedback from non-US admins, and they'd like the State field to not be required when editing/promoting a location.

**Comment by RyanTG** [comment]
State not required: 
https://github.com/scottwainstock/pbm/blob/master/app/models/location.rb#L6
https://github.com/scottwainstock/pbm/blob/master/app/models/suggested_location.rb#L5

Phone:
https://github.com/scottwainstock/pbm/blob/master/app/models/suggested_location.rb#L7
make it like https://github.com/scottwainstock/pbm/blob/master/app/models/location.rb#L7

**Comment by RyanTG** [comment]
In case the broken tests can ever be figured out, here were my commits (which I think include valuable things):

Remove unnecessary phone validation: https://github.com/RyanTG/pbm/commit/79f8815bd935c6f87d84b81b3499a0d2a0dcbd2c

Remove requirement for state field: https://github.com/RyanTG/pbm/commit/6e3fe4c66672706dae5bf4590a60cf3a9c73e980
Add a blank state entry to State dropdown on location suggestion form: https://github.com/RyanTG/pbm/commit/4aa1d396eb42e3c65d3ad8ca434e0bacb8a6abd4

I'd love to see these changes to the site soon. But the tests are beyond me.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/b6b9fefc359f08b3b2fb6091c325b1f59b6bd9b5

@RyanTG  ^^^

**Comment by RyanTG** [comment]
Thanks!

If you know a way to still include the comma on https://github.com/scottwainstock/pbm/commit/b6b9fefc359f08b3b2fb6091c325b1f59b6bd9b5#diff-54b4e4f2b562d74dad3af78e66e74e4f then it would be cool to add it back. I only removed it because I couldn't figure out how to only show the comma if the state was present.

I should have tried _deleting_ that phone validation line. argh... I was so close.
