### ISSUE TITLE
import_ifpa_tournaments.rake is encountering a json error

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1132]
I don't understand why Finland isn't showing any events.

**Comment by RyanTG** [comment]
It is failing
````
   (7.5ms)  SELECT "locations"."state" FROM "locations"
** [NewRelic][2019-02-27 21:19:00 -0800 run.* (4)] INFO : Reporting to: https://rpm.newrelic.com/accounts/111428/applications/140862
rake aborted!
JSON::ParserError: 765: unexpected token at ''
/app/lib/tasks/import_ifpa_tournaments.rake:18:in `block in <top (required)>'
````

**Comment by scottwainstock** [comment]
What I noticed is that the first run FAILS... second run passes... no changes in the code at all.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/edf874496550345f650d7d55cab7d44de1728faf

**Comment by RyanTG** [comment]
Huh, interesting. Thanks!

The Finland events page is still not showing any events. I don't know how to troubleshoot that at this point.

**Comment by RyanTG** [comment]
I'll close this, since the issue is resolved. The "no Finland events" seems like a different issue. Not sure what it could be, though. Like, are we not capturing events near the region lat/lon because... there are foreign address issues?

**Comment by RyanTG** [comment]
Reopening. I still see a json error:

```** [NewRelic][2019-04-19 15:25:10 -0700 run.* (4)] ERROR : Empty JSON response from collector: '""'
rake aborted!
EOFError: end of file reached
```

**Comment by RyanTG** [comment]
If the API rejected us for making too many requests in too short a time span, would the error tell us that? Just wondering if a pause between each region's fetch would help...
