### ISSUE TITLE
User profile high score not always returning the highest score

### ISSUE THREAD

**Issue by bpoore** [scottwainstock/pbm#1133]
When a user records their score multiple times on the same lmx, the highest score isn't always being returned in their profile. 

On the dev server, you can see lmx `18830` has a high score for `bap2018` of `123,451,234`, but the response coming from the request to `/users/130/profile_info.json` is coming back with a high score of `500`.

**Comment by scottwainstock** [comment]
@bpoore This endpoint? https://pinballmapstaging.herokuapp.com/api/v1/users/130/profile_info.json I'm not seeing that stuff... and I'm not able to get a test that shows this behavior. Can you replicate any of this on the staging site?

**Comment by bpoore** [comment]
Yes.

Steps to replicate: 
* Add score of 500 to location 910, Speakeasy Gil's
* Confirm score is added to machine details screen and user profile. 
* Add score of 5000 to location 910 
* High score is now 5000 on machine details, but the user profile screen still shows 500
* Check on postman to make sure the user profile data isn't a caching issue on the app side, get back: 
```            [
                "Speakeasy Gil's",
                "3-Ring Circus",
                "500",
                "Mar-10-2019"
            ],
```

**Comment by bpoore** [comment]
Found something:
https://github.com/scottwainstock/pbm/blob/d315c72de8633e50670ff73178bd5ac210827130/app/models/user.rb#L113

I think comparing the score to a value where `number_with_precision` has been applied is related to the issue. I went back to try a new value within the same number of digits and didn't see this issue (i.e. adding a score of 700, now shows the user's highest score as 700 rather than 500, but it should be 5000)

**Comment by bpoore** [comment]
#1146
