### ISSUE TITLE
If a location that someone has Saved gets deleted from the db, then there are Saved Location errors

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1140]
If a location gets deleted from the db, then the user profiles for any users who had that location in their Saved list will not load. And the Saved Locations list on the new app doesn't load, either.

So I think we need a mechanism that removes deleted locations from people's Saved list.

**Comment by scottwainstock** [comment]
```
glowing-dusk-5085::HEROKU_POSTGRESQL_COBALT=> select distinct location_id from user_fave_locations f where location_id not in (select id from locations);
 location_id
-------------
        6898
        8637
        9978
       11542
(4 rows)
glowing-dusk-5085::HEROKU_POSTGRESQL_COBALT=> delete from user_fave_locations where location_id in (select distinct location_id from user_fave_locations f where location_id not in (select id from locations));
DELETE 4
glowing-dusk-5085::HEROKU_POSTGRESQL_COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT
```
...code coming next.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/7938340235998aab162a6f2c706fc4313e2f1744

**Comment by RyanTG** [comment]
This still seems to be an issue. For example, the `pbm` user profile doesn't load https://pinballmapstaging.herokuapp.com/users/134/profile

Did I misinterpret the problem?

**Comment by bpoore** [comment]
@RyanTG @scottwainstock, the issue with the PBM account is location #4845 is hanging around 

<img width="452" alt="Screen Shot 2019-04-19 at 11 57 46 AM" src="https://user-images.githubusercontent.com/7720282/56439794-46937580-629c-11e9-9322-6bbee376a755.png">

**Comment by RyanTG** [comment]
All good now! Thanks. Closing.

```
pinballmapstaging::HEROKU_POSTGRESQL_GRAY=> select distinct location_id from user_fave_locations f where location_id not in (select id from locations);
 location_id 
-------------
        4845
(1 row)

pinballmapstaging::HEROKU_POSTGRESQL_GRAY=> delete from user_fave_locations where location_id in (select distinct location_id from user_fave_locations f where location_id not in (select id from locations));
DELETE 1
pinballmapstaging::HEROKU_POSTGRESQL_GRAY=> commit;
WARNING:  there is no transaction in progress
COMMIT
```
