### ISSUE TITLE
manufacturer=Stern API call is returning one location per Stern machine (so, duplicate locations)

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1141]
Example: http://pinballmap.com/api/v1/locations/closest_by_address.json?send_all_within_distance=true;no_details=1;manufacturer=Stern;address=77092;max_distance=50

If a location has two Stern machines, then that location will be in the results twice.

Stern is using this endpoint for their locator.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/34e9695df8422bbbd21667c68c8996fefb5e606b

**Comment by RyanTG** [comment]
Closing. Now there's a new issue https://github.com/scottwainstock/pbm/issues/1145
