### ISSUE TITLE
Decide how to construct the UserSubmissions "sentences"

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1144]
Right now we are constructing sentences from the user submissions that look like:

`User xtraball (gmail@gmail.com) commented on Judge Dredd at Pins Mechanical Co. (Downtown). They said: Was out of order/turned off`

https://github.com/scottwainstock/pbm/blob/c66c9fd88db704e34d7ae555feb9ac25f3822728/app/models/machine_condition.rb#L16

These sentences are used in Rails Admin, and for some of the user submission types they're used in emails to admins and operators.

For the Recent Activity section of the app (which may later also get added to the website), we need custom-formatted sentences. For example, for the above sentence will get changed to something like `xtraball commented on Judge Dredd at Pins Mechanical Co. (Downtown). They said: Was out of order/turned off`

**@scottwainstock stated:**

> In general what we're doing right now is a bad idea.
> Depending on the formatting of a string to drive events.
> So I think that'd be the thing we need to change. I haven't had much time to think about how that'd work.

@bpoore says that we also need to include the location name:

> the location name needs to be included (without it, the location name is not going to show up at the top of the screen like it does when getting to this screen from other means).

**So this issue is to figure out how do this.** I can supply the sentence formats. 

(if I'm using the wrong words here, such as "sentences," please forgive me)

**Comment by RyanTG** [comment]
Formats. So, whenever `by username` is included, those strings should only be present if there's a username to attach to the submission. For example, if a location was added by an admin through rails admin, then the "machine added" submission won't include the `by username` because there's no username to attach to the action. 

Each user submission should pass with it a DATE, as well as a LINK to the location (a location ID, maybe? @bpoore help me out!). If I'm not stating that correctly, please tell me.

**Location Confirmation**
`[username] confirmed the lineup at [location]`

**Machine Added**
`[machine] was added to [location] [by username]`

**Machine Removed**
[machine] was removed from [location] [by username]`

**Machine Comment**
[username] commented on [machine] at [location]. They said "[comment]"`

High Score
`[username] added a high score of [score] on [machine] at [location]`

**Comment by bpoore** [comment]
We do need a location ID to link an activity to the location, but that is already coming back with the current response format. We can assemble the strings on the app-side if all the information we need can be provided in the fields (i.e. username rather than user_id, location_name since the location may not necessarily be in the app state, etc) or we can grab a field from the API for the `sentences`. Whatever is easier for @scottwainstock.

The response already includes `submission_type` which would allow the strings to be composed from the app as long as the additional fields we need are included as fields.

**Comment by scottwainstock** [comment]
Sorry, I'm not really following this anymore... the formats provided don't appear to include the IDs, just the names. We want both or just names? Sounded like we want both. And we're talking about dates and links too, but I don't see them in the formats.

Can I get the final formats lined up before I start making the changes? I'm going to have to update historical data to fit the new format, so I'd rather not go through the process more than once.

@RyanTG @bpoore

**Comment by bpoore** [comment]
Double checking this got cleared up in Slack, right? I started working on a draft response realizing I think we already have a path forward. I can write up something here if we still need it.

**Comment by scottwainstock** [comment]
I think we're good now... I need to fix some breaking tests.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/f5cd2a4960166865faf9ea7b3379d9acf7c2d7c3

New wording should start to roll in.

**Comment by RyanTG** [comment]
Thanks! I'll check it out.

I think _chances_ are that the app won't go live for 30 days, and so all the old wording will be flushed out of the app's view by then. But if we are ready to go live before 30 days, I think we should wait. And we'll just tell the admins what the deal is.
