### ISSUE TITLE
Some endpoints are no longer returning data

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1145]
Such as http://pinballmap.com/api/v1/locations/closest_by_address.json?send_all_within_distance=true;no_details=1;manufacturer=Stern;address=77092;max_distance=50

**Comment by RyanTG** [comment]
Also, submitted locations are _not_ being geocoded on the staging site, but they are on the live site.

**Comment by scottwainstock** [comment]
@RyanTG This should be good now... I did some submitted locations testing in dev and it seemed ok. If you don't find that to be the case in live, please send me all the location data that you submitted (and didn't get geocoded).

**Comment by RyanTG** [comment]
Did you check submitted locations geocoding on staging, too? Geocoding the submitted locations had been working on live but not staging.

**Comment by scottwainstock** [comment]
```2019-03-23T19:24:25.911939+00:00 app[web.1]: Google API error: request denied (You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account).```

**Comment by scottwainstock** [comment]
Works in staging after I set the API key in the heroku config.

Seemed to work on the live site with no changes on my part:
```2019-03-23T19:27:50.152070+00:00 app[web.1]: [4e060bcd-9f1a-4bcf-8d52-946477f23a66]   SuggestedLocation Create (2.6ms)  INSERT INTO "suggested_locations" ("name", "street", "city", "state", "zip", "phone", "website", "region_id", "comments", "machines", "user_inputted_address", "lat", "lon", "created_at", "updated_at", "country") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) RETURNING "id"  [["name", "test site from web"], ["street", "617 West 7th Street"], ["city", "Los Angeles"], ["state", "CA"], ["zip", "90017"], ["phone", ""], ["website", ""], ["region_id", 1], ["comments", ""], ["machines", "Aerobatics (Zaccaria, 1977), "], ["user_inputted_address", "617 w 7th st, los angeles, , 90017"], ["lat", "34.0479628"], ["lon", "-118.2572405"], ["created_at", "2019-03-23 19:27:50.148569"], ["updated_at", "2019-03-23 19:27:50.148569"], ["country", ""]]```

Can you confirm?

**Comment by RyanTG** [comment]
Works great!

I should have suspected a missing API key.
Beth had been using a personal API key for geocoding searches on staging, and so I should have suspected that we didn't have one established for geocoding suggested locations.
