### ISSUE TITLE
API: add an endpoint for City name autocomplete

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1147]
In the new app, we'd like to have an autocomplete for City names, using our City field. It should also include State. So like, "City State". 

Our usage will be to include it in the same autocomplete as the location names, but when clicked it will geocode the city and show locations in that city.

**Comment by scottwainstock** [comment]
@RyanTG I'm a little confused on how this is going to work in the app.

On locations we have a "city" field and a "state" field. I return something by searching through "city" and returning back a string that has "CITY STATE". Is that enough? It sounds like you want to filter by city AND state, and that's going to get really complicated.

**Comment by RyanTG** [comment]
I _think_ that is enough? What do you mean by "filter"? 

Returning back a string that has "CITY STATE" seems right. And then in the app, it will geocode that string, like "address=CITY STATE" (like "address=portland or"), right? Otherwise, if it was just geocoding only the city string, then portland, maine might get geocoded.

So if a user just types "portland" they'll see autocomplete options for "portland OR" and "portland ME".

**Comment by scottwainstock** [comment]
👍

**Comment by scottwainstock** [comment]
This should do it: https://github.com/scottwainstock/pbm/commit/e97ba75ae47fd9ce1dfdbb31d5e22b2e4a41598f

**Comment by scottwainstock** [comment]
cc @bpoore

**Comment by bpoore** [comment]
Thanks! I'll check this out soon!

**Comment by bpoore** [comment]
We might need to clean up some of the data in the table coming back for this. This is what I see for `'portland'`.

<img width="1366" alt="Screen Shot 2019-03-25 at 5 47 08 PM" src="https://user-images.githubusercontent.com/7720282/54963475-3058fa80-4f26-11e9-9c3e-b998578335a8.png">

**Comment by RyanTG** [comment]
Yeah, I figured that would be the case. The staging data is especially messy. On the live data, I run commands that do routine clean-up (like delete empty spaces after the value).
