### ISSUE TITLE
Can't add users to be admins of a region

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1153]
I just added a new region, Arkansas. Then I restarted the server, and went to give a dude privileges to be the admin, but it fails at that step. I just get a white screen of death. I tried adding him to another region, and got the same result.

Edit: Can't edit users at all. Can't change their email address.

**Comment by scottwainstock** [comment]
```PG::NotNullViolation: ERROR: null value in column "encrypted_password" violates not-null constraint```

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/56c84a7370bcfcf561dd8fa5a83fa67a09170088

@RyanTG  ??

**Comment by RyanTG** [comment]
Success! Thanks.
