### ISSUE TITLE
Allow user who is not logged in to POST to /regions/contact.json

### ISSUE THREAD

**Issue by bpoore** [scottwainstock/pbm#1156]
For the app, we are hoping to allow users who are not logged in to still be able to submit a message: https://github.com/bpoore/pbm-react/issues/42

Currently, the API enforces a user must be logged in to allow a message to be submitted. https://github.com/scottwainstock/pbm/blob/master/app/controllers/api/v1/regions_controller.rb#L109 

Can we remove this enforcement? 

@RyanTG, if a user is logged in vs not, is it desirable for the admin to know the difference? The name and email fields are going to be populated with every submission... if the user is logged in we are doing it for them and otherwise the user needs to fill out those fields before submitting. Should we have an additional field indicating if they were logged in or not when submitting? Or if logged in, still pass the auth token to indicate they were logged in?

**Comment by RyanTG** [comment]
On the website, people don't have to be logged in to submit a message, so I'm surprised the API is enforcing that. And they come in like:

Logged IN user:
````
Their Name: 

Their Email: 

Message: blah balh

Username: xyx (automatically filled in)

Site Email: xyx@xyx.com (automatically filled in)
````

Logged OUT user:
````
Their Name: Ryan (manually typed in)

Their Email: xyx@xyx.com (optional, manually typed in)

Message: blah balh

Username:

Site Email: 
````

So, we can tell from the fields if they were logged in or not.

**Comment by bpoore** [comment]
Differentiating between the name/username email/site email will require updating what fields are sent to this route, currently the route accepts only name and email: https://github.com/scottwainstock/pbm/blob/master/app/controllers/api/v1/regions_controller.rb#L105

Sending the auth token along for the ride if the user is logged in could let us know what the fields mean. Whatever is easiest to implement for the API is a similar effort to get the request sent from the app (auth token or differently named fields in the request).

**Comment by RyanTG** [comment]
My opinion is that it is nice to know if a `name` is a username or just a name that someone typed in (because I sometimes have to look up that user in out system and help them out). So if we stuck with only two fields (name and email), then it would be nice to know when those values were autopopulated because they're logged in, and when they were manually added. Are you saying that taking the auth token along for the ride could supply us with something like "auth_present? yes/no" in the message?

**Comment by bpoore** [comment]
> Are you saying that taking the auth token along for the ride could supply us with something like "auth_present? yes/no" in the message?

yes, that was what I was indicating with that. From my end, the difference of how to send is trivially different either way, so whatever is easier for interpretation and for the API.

**Comment by bpoore** [comment]
I think I see what changes need to happen here. I think I'll make a stab at making a PR myself. I've been wanting to get my hands more dirty in the PBM codebase. I will plan on differently named fields and update the email to have the new fields.
