### ISSUE TITLE
Location data - make the Country field required

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1162]
Can't tell you how often I have to fill this in for admins.

I don't think we should require it of people submitting the locations. But we should require it for promoting a suggested location.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/cd60008c61b191fe40765b20aa47efc11bafdd35

**Comment by RyanTG** [comment]
thx

**Comment by RyanTG** [comment]
Re-opening. When admins Add a New Location, we should require the country field.

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/pull/1184/commits/7c6c7e297a197df2e0bb5eabb35af10eddb12321

**Comment by RyanTG** [comment]
Re-opening! I didn't do this quite right. The country field is being cleared out when an admin edits a suggested location. Or something. I'll look into it.

**Comment by RyanTG** [comment]
The country field is the number 1 thing I have to fix on the locations that admins approve.

I think what's happening is the user is choosing the correct country when filling out the form. In the email, the country field is shown as populated. When you view the submission in rails admin (via the "Show" tab) the country field is populated. But when the admin reviews the submission, the country field is empty (and then they approve the location, and there's no error). I don't know what the exact issue is, but the country that the user is choosing seems to be the wrong format or code or something. So, everything looks ok to the admin, but then gets cleared out when they approve (defaulting to "United States" instead of of the correct "US").

**Comment by RyanTG** [comment]
Testing it... I think that when admins approve a location without editing it at all, then the country field gets cleared out (because it's in the wrong format) but the validation doesn't check to see if the field is populated. 

If an admin edits the location before approving it, then the country field gets cleared out, but the validator catches the issue.

**Comment by RyanTG** [comment]
This seems to be fixed now.
