### ISSUE TITLE
Clearing out location_type and operator_id not working 

### ISSUE THREAD

**Issue by bpoore** [scottwainstock/pbm#1188]
Issue as described in the app repo: https://github.com/bpoore/pbm-react/issues/246

I thought passing `null` was how we were wiping out values. Can update app-side if it was a misunderstanding on my part.

**Comment by bpoore** [comment]
Also- I added back an operator_id to 3860 looking into the issue and was unable to get it back to no selected operator. That will need to be updated from the backend until we figure out what's going on with the client requests. Sorry!

**Comment by RyanTG** [comment]
K. Operators can be cleared out via the website, FYI.

**Comment by bpoore** [comment]
Fixed it on the site. Thanks!

**Comment by RyanTG** [comment]
https://github.com/bpoore/pbm-react/pull/409/commits/3f516c7842ada08f76b24e56fc10b378ca206d1a
