### ISSUE TITLE
Top 25 machines API endpoint

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1212]
So that the app can display this information.

I would like to display Name, Manufacturer, Year. If the machine is part of a machine group, then display the machine group name and the man and year. I think we'll have to add man and year fields to machine_group for this to work.

**Comment by scottwainstock** [comment]
@RyanTG What kind of filters for this? Region? Manufacturer? Year?

**Comment by RyanTG** [comment]
I don't think we need any filters.

Let me know if you think I'm not understanding the implications of filters. 

I just want the app to have a screen that displays the top 25 machines across the entire map. With a count for each one.

**Comment by scottwainstock** [comment]
"I think the year should be the year the game first came out. So like, if the Pro first came out in 2017, and then a year later some other version came out, the year should be listed as 2017."

**Comment by scottwainstock** [comment]
select coalesce(g.name, m.name) as machine_name, min(m.manufacturer) as manufacturer, min(m.year) as year, count(*) as machine_count from location_machine_xrefs lmx inner join machines m on m.id=lmx.machine_id left outer join machine_groups g on g.id=m.machine_group_id group by 1 order by 4 desc limit 25;

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/3d8a45c36a960da845e85ffd5780a242a5da6038

**Comment by RyanTG** [comment]
Review: This is also including any machine with the same name to the sum. For example, the Jurassic Park Data East machine is included in the Jurassic Park Stern stats.

Is it possible to not use names at all when summing, but only Machine_ID, and if the machine is part of a machine_group, then all the Machine_IDs within that group?

**Comment by RyanTG** [comment]
Just thought of this: maybe we can use OPDB IDs to calculate top 25 without including different machines that have the same name.

The first five characters in an OPDB ID identifies the machine, and the strings after that are for versions and variants. So we could identify machines (and all the variants together) based on the first five characters. I'll try it out!

https://opdb.org/about

**What is an OPDB ID?**

Every machine in the database is assigned a unique identifier. This OPDB ID is designed to convey as much information as possible in the ID itself. Each OPDB ID is made up of three parts: A mandatory group identifier followed by an optional machine identifier and an optional alias identifier. A sample OPDB ID looks like: G43W4-MrRpw-A1B7O:

    G43W4 identifies that this machine belongs to the AC/DC group of machines. The group identifier always begins with G.
    MrRpw identifies that this machine is an AC/DC LE machine. The machine identifier always begins with M.
    A1B7O identifies that this machines is the Back in Black variant of the AC/DC LE machine. The alias identifier always begins with an A.

Assigning each machine an ID consisting of these separate parts it's possible to see the relationship between machines just by examining their OPDB IDs.

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/commit/76e887b73c4eb9a2d76bbb0cd879e85555d67871
https://github.com/scottwainstock/pbm/commit/b28cf22023ced97673b68ef574aec5627eebe9e3

It worked with opdb_id.
