### ISSUE TITLE
Add Year and Manufacturer fields to machine_group

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#1213]
And I'll populate them.

**Comment by scottwainstock** [comment]
@RyanTG This could just be joined in from machine. There'll likely (?) be one manufacturer... but it seems possible that years will differ. How are you going to handle that?

**Comment by RyanTG** [comment]
Is the join a method for populating the new fields, or is the join instead of creating the new fields? 

I think the year should be the year the game first came out. So like, if the Pro first came out in 2017, and then a year later some other version came out, the year should be listed as 2017.

**Comment by scottwainstock** [comment]
Not needed.
