### ISSUE TITLE
Feature Request: Location Ratings

### ISSUE THREAD

**Issue by brianhanifin** [scottwainstock/pbm#123]
We have a couple of crap locations, we have a couple of excellent locations, and a lot of in between. My definition of a crap location is one that consistently does not maintain their machines.

It would be really nice if we could have a ratings system. User votes would be ideal, but I would also take a drop down in the admin section as well. Can I have a steaming pile of crap show up in front of the crap locations name? ;-)  And the shining examples should get a nice icon of their own... a ribbon... a star? :-)

**Comment by RyanTG** [comment]
Replying to this as it will be relevant soon, now that we're about to add a user auth system.

**Comment by scottwainstock** [comment]
@RyanTG This seems like something that'd be cool to add...

**Comment by RyanTG** [comment]
True. But the more Yelpy we get, the more chances of aggravating business owners. Plus, will we have enough ratings (locations rated, and ratings per location) to make this data valuable?

But still, would be cool to tie ratings into a "my favorites" feature. Like, if a user rates something 4 or 5 stars, then that's automatically a favorite location. And/or, the profile page can list all rated locations, sorted by rating level.

**Comment by RyanTG** [comment]
At this point, I'm more in favor of "favorites" rather than "ratings". Due to the quantity of our users, I fear that too many locations would only have a couple ratings.

But we could display how many people have favorited a spot.

Favorites should also be included in the user profile. 

I'll probably create a new issue for this.
