### ISSUE TITLE
Feature: share business location 

### ISSUE THREAD

**Issue by alberttwong** [scottwainstock/pbm#1231]
A share button on entries.

**Comment by RyanTG** [comment]
Like a direct link to that location? They all have this. The permalink button. And on desktop there’s a second link on the map.

**Comment by alberttwong** [comment]
More like share this entry via iMessage

**Comment by RyanTG** [comment]
Is this an app request? If so: https://github.com/bpoore/pbm-react/issues

**Comment by RyanTG** [comment]
I’ll update the readme on this project to note that nations app issues spoils go on that project, and website ones go here. Closing.
