### ISSUE TITLE
Remove comma from autocomplete result label if there is no state

### ISSUE THREAD

**Issue by bpoore** [scottwainstock/pbm#1325]
The app is displaying the label returned from autocomplete result on search screen. Currently if the label does not have a state to display, there is still a comma being returned:

<img width="419" alt="Screen Shot 2021-11-27 at 12 42 27 PM" src="https://user-images.githubusercontent.com/7720282/143722613-d196a582-f2f0-4bbd-9263-de17a6cbb01b.png">

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/commit/fd593649aefc4cf61c18bfade3beeb44f812df30
