### ISSUE TITLE
Global links

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#331]
For every region, can we add a link category called:

Pinball Map Links

And within it these links:

Pinball Map Store 
http://pinballmap.com/store

Pinball Map Blog
http://blog.pinballmap.com

**Comment by RyanTG** [comment]
Can I reopen this with another request? Or is that lame?

Can you add descriptions for those two links (and apply them to all the regions that still have them listed)? I noticed on the iOS app that the description under each one says "N/A". The app should probably be updated to not include N/A when there's no description... 

Description for the Store link:
We have a t-shirt for sale.

Description for the blog link:
News, questions, feelings.

**Comment by scottwainstock** [comment]
glowing-dusk-5085::COBALT=> update region_link_xrefs set description='We have a t-shirt for sale.' where url='http://pinballmap.com/store';
UPDATE 55

glowing-dusk-5085::COBALT=> update region_link_xrefs set description='News, questions, feelings.' where url='http://blog.pinballmap.com';
UPDATE 55
