### ISSUE TITLE
High Score Rank

### ISSUE THREAD

**Issue by fmscode** [scottwainstock/pbm#340]
Look into trying to automatically assigning rank based on past scores. At least look into a default rank for high scores. You referenced changing this code segment to support the automatic assignment https://github.com/scottwainstock/pbm/blob/master/app/models/machine_score_xref.rb#L26

**Comment by scottwainstock** [comment]
@RyanTG Do we want to ditch rank? Doesn't feel all that important to me... mostly the score is.

**Comment by RyanTG** [comment]
Yeah, fuck rank.
