### ISSUE TITLE
Comment History Bug

### ISSUE THREAD

**Issue by fmscode** [scottwainstock/pbm#348]
From Ryan:
If there's a comment, and you add a new blank comment (like you hit save without adding any text), it adds a blank comment but doesn't push the previous one into the "past machine conditions" section. Instead, the old comment just disappears.

**Comment by scottwainstock** [comment]
@fmscode I took at stab at this, just to make sure I still know how to program. Let me know if you see any issues with it.

fbc7b892175e4cf66b41ddf0f53bef6ef3a85775

**Comment by fmscode** [comment]
Looks good to me. Thanks for fixing this issue!
