### ISSUE TITLE
Combine machine 2165 with machine 1793

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#349]
Merge machine 2165 with machine 1793, and use 2165's name.

Star Trek (Pro) - 2165
Star Trek - 1793

Mate them. Then in the end we are left with Star Trek (Pro).

Thanks.

**Comment by scottwainstock** [comment]
glowing-dusk-5085::COBALT=> select count(*) from location_machine_xrefs where machine_id=1793;
 count
-------
   103
(1 row)

glowing-dusk-5085::COBALT=> select count(*) from location_machine_xrefs where machine_id=2165;
 count
-------
    37
(1 row)

glowing-dusk-5085::COBALT=> update location_machine_xrefs set machine_id = 2165 where machine_id = 1793;
UPDATE 103
glowing-dusk-5085::COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT
