### ISSUE TITLE
Hide operator from dropdown if they have no locations

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#355]
Sometimes operators stop operating. But admins don't always know to remove them from the database. As a result, those operators are still listed in the dropdown search, but there aren't any results.

So, can we have a filter than filters them from the dropdown list if they have < 1 location?

**Comment by RyanTG** [comment]
Also, I'm going to add the operator name to the location info. Can you tell me what the field is called for operator names? And can you also tell me the other operator fields (email, phone, and website - I believe).

**Comment by scottwainstock** [comment]
pbm_dev=# \d operators
                                     Table "public.operators"
   Column   |            Type             |                       Modifiers
------------+-----------------------------+--------------------------------------------------------
 id         | integer                     | not null default nextval('operators_id_seq'::regclass)
 name       | character varying(255)      |
 region_id  | integer                     |
 email      | character varying(255)      |
 website    | character varying(255)      |
 phone      | character varying(255)      |
 created_at | timestamp without time zone |
 updated_at | timestamp without time zone |
Indexes:
    "operators_pkey" PRIMARY KEY, btree (id)

**Comment by RyanTG** [comment]
Thanks. And if I wanted to list all the operators in a region (and hide the list if there are none), how would I do it?

I was hoping it would be something like 
    - if (@operator.size > 0)
But that's not working.

**Comment by RyanTG** [comment]
```- if (@operators)```
That doesn't throw an error, at least. But it still doesn't work. Like, if I put it before a div, the div will not display even if there are operators in the region.

**Comment by scottwainstock** [comment]
I'd need to see the full gist of what you're looking at, I think. You can call "@region.operators" to see all operators within a region. And, "operator.locations" will return null if there are no operators in the region. So, that kind of thing would work in your "if (@operators)" example. Like... "if (operator.locations)" is a way of saying "if the operator actually has locations".

I took a different approach though. I joined the operators table to the locations table, effectively dropping any operators that don't have locations associated with them. I think it's a little cleaner, because it's hidden in the controller. In general, the more logic in the controllers/models the better.

**Comment by scottwainstock** [comment]
24e8c26978b33c4d39b85745c87f5c565a48be2b

**Comment by RyanTG** [comment]
I don't have any more code to show. I wasn't trying to solve this issue - I'm just trying to add a list of the region's operators to the About page, and I don't want anything to show if that region doesn't have any operators. So I was still on step 1 of this process: show a div if the region has operators.

**Comment by scottwainstock** [comment]
Oh OK, sorry. Check out... https://github.com/scottwainstock/pbm/blob/master/app/models/region.rb

The "has_many :operators" part means you can call ".operators" on a region object and get back all the operators for that region.

So, you could put a helper method inside region that loops through all the operators and returns true or false depending on if any have actual locations? Maybe something like that. Or if you are displaying them from a loop you could do something like...

- @region.operators.each do |o|
    - if o.locations
       #{o.name} IS AN OPERATOR WITH A LOCATION

**Comment by scottwainstock** [comment]
Github kill my formatting, but you get the idea...
