### ISSUE TITLE
[API] Only show six most recent machine comments

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#360]
"API paths do a noop for condition deletions"

 auto-delete the 7th comment for a machine.

What else do I need to say?

**Comment by scottwainstock** [comment]
Nothing.

Can you confirm that we don't currently allow condition deleting in any of the apps? I don't think we do, but I wanted to check before I remove API endpoints.

**Comment by scottwainstock** [comment]
I mean do noops on API endpoints.

**Comment by scottwainstock** [comment]
I don't think we actually have anyone using this deletion path, right? I made it for Brian, his stuff isn't live yet.

@fmscode You aren't using '/api/v1/machine_conditions/:id.json', right?
@bdols Do you mind if I remove ''/api/v1/machine_conditions/:id.json''?

**Comment by scottwainstock** [comment]
@RyanTG Since we've got basically unlimited DB space now... what do you think about me leaving all comments, but only returning the first 6 in the API? I just wonder if old comments might come in handy some day for... something?

**Comment by fmscode** [comment]
iOS app is not using that route

**Comment by RyanTG** [comment]
I'm super cool with keeping them all in the DB.

**Comment by scottwainstock** [comment]
58d13f32d87e3ea7337b224788aa877befb709e5
