### ISSUE TITLE
All region map

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#366]
Make a map that includes data for all regions.

**Comment by scottwainstock** [comment]
@RyanTG Do you see any issues with this from a UX standpoint? Is this something we should try to get on the apps too? In general, is this a bad idea?

**Comment by RyanTG** [comment]
Someone else recently expressed a desire to have this (on the app), because they were touring around the country and wanted to plan out a route based on where to play.

One potential issue would be: suggest a location. How would users know which region to suggest a location to? Would we just turn that feature off when viewing the super map?

I'll try to think about any other issues.

**Comment by RyanTG** [comment]
Not sure if this would be an issue - but if someone did an ALL search of locations, it would probably take two minutes to load... and possibly strain the database or some crap? Could that be an issue?

**Comment by scottwainstock** [comment]
Definitely could be an issue. I feel like things are a lot faster now than they were before, but it could definitely be a problem for us. Especially on the apps because they have to pull down ALL that data on-load.

**Comment by RyanTG** [comment]
If the data in two regions overlap, that might produce a weird result. I'm not sure if any overlap, though.

**Comment by RyanTG** [comment]
Atlas Obscura is a mapping site, and we might be able to get ideas from it. http://www.atlasobscura.com/

It's one site, but there are numerous "destinations" within it (which can be either a state or a city, as far as I can tell).

Some things I've noticed on it:

- There's no dropdown or option to show all. Instead there are two search boxes: "what" and "where"
- If you choose where (either by typing in 'portland, or' or finding a link that goes to http://www.atlasobscura.com/destinations/portland-oregon) it will list a pre-set number of results per page. This is likely for the sake of load time. And I'm guessing they're sorted by either popularity or random.

If we did something like that (bring up Portland, OR) and you get the first 15 locations, sorted by date updated, or sorted by number of machines).

I have more thoughts on this, but need to go to class.

We've gotten some feedback about regions in this thread: http://tiltforums.com/t/pinball-map-open-thread/901

I'm totally conflicted. There's a part of me that wonders if our usefulness as a curated regional mapping site has been surpassed by our popularity and people's desires to map everything.

**Comment by RyanTG** [comment]
On the Atlas site, when you type in city name in the "where" field, there's no autofill. Instead, it seems like it matches your text in some database of city names, and them shows you locations that are within a certain proximity of the lat/lon of that city name.

Just noting that here...

**Comment by RyanTG** [comment]
We'll deal with this anew when the time comes. No need to keep this issue open.
