### ISSUE TITLE
Weekly automated admin email

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#370]
From our conversation. Beefed up weekly email for the admins. Tailored to each admin. And this would replace the weekly listed of empty locations email.

Subject: PBM - Weekly admin digest for $region_name - mm/dd/yyyy

Body: Here's an overview of your pinball map region! Thanks for keeping your region updated! Please remove any empty locations and add any submitted ones. Questions/concerns? Contact pinballmap@posteo.org

$region_name Weekly Overview

List of Empty Locations:
[List of empty locations]

N Location(s) were submitted to you this week

N Location(s) were added by you this week

N machines were added by users this week

N machines were removed by users this week

$region_name is listing N machines and N locations

N events are listed

N events were added this week

N "contact us" messages were sent to you

Anything else? Did you have other ideas about how this should work? I figured the function would be to remind admins of things and give them an overview of the state of their region.

If any of those can't be easily quantified (like the events, maybe?) then we don't have to include them. 

Recap of content: 

List of empty locations
Number of submitted locations
Number of added locations
Number of machines added
Number of machines removed
Number of machines and locations listed in region
Number of events listed
Number of events added
Number of "contact us" messages sent

**Comment by scottwainstock** [comment]
513c3f97aacc0c275d9022e2e1bf603e7d8cd19f

This should get sent out next Friday at the normal time.
We now log all location suggestions, "contact us" submissions, and machine deletions.

**Comment by RyanTG** [comment]
Really cool. Thanks!

**Comment by RyanTG** [comment]
Issue: "Number of events listed" seems to list inactive events.

Suggestion: The super admins (me and you) receive a single email that contains ALL of these digests.

**Comment by scottwainstock** [comment]
e443f63cae749ead1f90d698ff586b961d0494b8

**Comment by RyanTG** [comment]
Number of events listed still lists inactive events.

And Portland had a location submission on Wednesday, but it's still saying, "0 Location(s) were submitted to you this week."

**Comment by scottwainstock** [comment]
e4f9d8d3f5fd4b111b82cda6a2899b9ac9f19709

**Comment by RyanTG** [comment]
Looking good!
