### ISSUE TITLE
"location not found" message

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#371]
When I've shown the site to friends, they sometimes type in a location name... but it's a location that isn't on the map. After clicking Search, the map shows the middle of the ocean. Would be nice to show a "NOT FOUND IN THIS REGION. SEARCH AGAIN." message instead.

**Comment by scottwainstock** [comment]
This could probably benefit from some styling...

ef9534f334b1934b98ab27fba4022c9a6d2f2c43
