### ISSUE TITLE
Links to pintips

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#373]
Underneath a machine name, we can add a "How to play this machine" link that goes to the relevant entry on pintips.net.

But if there isn't a pintips entry, what do we do?

http://pintips.net/pinmap/group/{machine_group_id} [4]

http://pintips.net/pinmap/machine/{machine_id} [5]

IMPORTANT: If a machine belongs to a group you MUST use the group
URL. I only store one pinmap machine id on my end (typically the
"Pro" machine) so if you try to redirect to the Avengers LE machine
id you'll get an error.

**Comment by RyanTG** [comment]
Note to self: https://github.com/scottwainstock/pbm/blob/master/app/views/location_machine_xrefs/_remove_machine.html.haml

Something like:
= link_to lmx.machine_group_id.nil? ? link/{lmx.machine_group_id} : link/{lmx.machine_id}, :target => '_blank' do

**Comment by RyanTG** [comment]
Scott, It's all good if I do:

= link_to "http://pintips.net/pinmap/machine/#{lmx.machine_id}"

But not 
= link_to "http://pintips.net/pinmap/group/#{lmx.machine_group_id}"

It doesn't render. Can I not call machine_group_id like that?

**Comment by scottwainstock** [comment]
= link_to "http://pintips.net/pinmap/group/#{lmx.machine.machine_group_id}"

**Comment by RyanTG** [comment]
Thanks. Got it working. Oddly enough, the if statement pasted above wasn't working - I had to instead do it like:
- if
- else

I'm working on the styling, and will send a pull request later.
