### ISSUE TITLE
Rack-attack throttles

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#374]
https://github.com/kickstarter/rack-attack#throttles

This is where we can set it to limit per second requests. Looks like it can apply to general site requests. And we can set different parameters for login attempts. Not sure if anyone's trying to log in.

More info: https://www.kickstarter.com/backing-and-hacking/rack-attack-protection-from-abusive-clients

Does this look doobieable? I see no legit reason for people to make more than a couple requests per second. I think two would be too strict. But three of four might be good.

**Comment by scottwainstock** [comment]
My only concern here is the mobile apps. Those tend to make a lot of requests on startup... and it's feasible that they'd make 3-4 within a few seconds if you navigate around the app a certain way.

Would it be silly to start with TEN and then work backwards from there?

**Comment by RyanTG** [comment]
That sounds reasonable. I hadn't thought of the mobile apps. To bad we can't exclude them entirely, since I doubt spammers ate using them.

**Comment by scottwainstock** [comment]
4ca52d97cd3d1b04c19271cc4b3e76fa59c54fa5
