### ISSUE TITLE
Merge these two machines (Blackout)

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#379]
machine IDs:

1109
1813

**Comment by scottwainstock** [comment]
1109 survived.

glowing-dusk-5085::COBALT=> select * from machines where id in (1109, 1813);
  id  |   name   | is_active |         created_at         |         updated_at         |             ipdb_link              | year | manufacturer | machine_group_id
------+----------+-----------+----------------------------+----------------------------+------------------------------------+------+--------------+------------------
 1109 | Blackout | f         |                            | 2013-04-18 22:07:50.46413  | http://ipdb.org/machine.cgi?id=317 | 1980 | Williams     |
 1813 | Blackout | f         | 2013-10-16 22:33:10.468011 | 2013-10-16 22:36:43.086726 | http://ipdb.org/machine.cgi?id=317 | 1980 | Williams     |
(2 rows)

glowing-dusk-5085::COBALT=> select * from location_machine_xrefs where machine_id in (1109, 1813);
  id   |         created_at         |         updated_at         | location_id | machine_id |        condition         | condition_date | ip | user_id | machine_score_xrefs_count
-------+----------------------------+----------------------------+-------------+------------+--------------------------+----------------+----+---------+---------------------------
 16313 | 2014-03-06 06:07:32.613263 | 2014-03-06 06:07:32.613263 |        3280 |       1109 |                          |                |    |         |
 19505 | 2014-10-01 16:34:17.151819 | 2014-10-01 16:34:28.867571 |        4495 |       1813 | Right flipper super weak | 2014-10-01     |    |         |
 24099 | 2015-06-21 19:20:00.012561 | 2015-06-21 19:20:00.02124  |        4874 |       1813 |                          | 2015-06-21     |    |         |
 18121 | 2014-07-16 04:25:03.028771 | 2014-07-16 04:25:03.028771 |        3745 |       1109 |                          |                |    |         |
 17479 | 2014-05-28 02:25:59.662257 | 2014-05-28 02:25:59.662257 |        4724 |       1109 |                          |                |    |         |
 22096 | 2015-02-18 18:35:02.844504 | 2015-02-18 18:35:02.844504 |        5509 |       1109 |                          |                |    |         |
 25053 | 2015-08-11 20:27:48.355758 | 2015-08-11 20:27:48.355758 |        5980 |       1109 |                          |                |    |         |
(7 rows)
glowing-dusk-5085::COBALT=> update location_machine_xrefs set machine_id=1109 where id in (19505, 24099);
UPDATE 2
glowing-dusk-5085::COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT
glowing-dusk-5085::COBALT=> select * from location_machine_xrefs where machine_id in (1109, 1813);
  id   |         created_at         |         updated_at         | location_id | machine_id |        condition         | condition_date | ip | user_id | machine_score_xrefs_count
-------+----------------------------+----------------------------+-------------+------------+--------------------------+----------------+----+---------+---------------------------
 16313 | 2014-03-06 06:07:32.613263 | 2014-03-06 06:07:32.613263 |        3280 |       1109 |                          |                |    |         |
 19505 | 2014-10-01 16:34:17.151819 | 2014-10-01 16:34:28.867571 |        4495 |       1109 | Right flipper super weak | 2014-10-01     |    |         |
 24099 | 2015-06-21 19:20:00.012561 | 2015-06-21 19:20:00.02124  |        4874 |       1109 |                          | 2015-06-21     |    |         |
 18121 | 2014-07-16 04:25:03.028771 | 2014-07-16 04:25:03.028771 |        3745 |       1109 |                          |                |    |         |
 17479 | 2014-05-28 02:25:59.662257 | 2014-05-28 02:25:59.662257 |        4724 |       1109 |                          |                |    |         |
 22096 | 2015-02-18 18:35:02.844504 | 2015-02-18 18:35:02.844504 |        5509 |       1109 |                          |                |    |         |
 25053 | 2015-08-11 20:27:48.355758 | 2015-08-11 20:27:48.355758 |        5980 |       1109 |                          |                |    |         |
(7 rows)
