### ISSUE TITLE
Find Nearest Locations

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#381]
Once geolocation is set up on the website (see https://github.com/scottwainstock/pbm/issues/372), it would be cool to then have a "find nearest locations" link.

It would probably involve showing a dot on the map for your current location, with the pins surrounding it. Then the results would show the closest locations (within 20 miles? Maybe that's too much), sorted by proximity. Each location could have "distance: xx miles" in the location details.

**Comment by scottwainstock** [comment]
Would you mind styling this? I put the button up near the "store" button on the region landing page.

https://github.com/scottwainstock/pbm/tree/issue_381

I have this setup for 20 miles. I *think* it might be too much, but let me know. It's easy to adjust.

**Comment by RyanTG** [comment]
Will doobie

**Comment by RyanTG** [comment]
Yeah, I think something like 5 miles would be better. 20 miles seems like too much.

Also, if you do a "closest" search when you're viewing a far away region, you just get the "not found" error message. Can we customize the error message for this case? "No pinball found on this map within 5 miles of your location."

**Comment by scottwainstock** [comment]
Can you do another pull on my issue_381 branch? I added the "Each location could have "distance: xx miles" in the location details." part... and scaled back the range from 20 miles to 5.

The far away region thing is going to take more work, so I don't have that yet.

**Comment by RyanTG** [comment]
As you wish.
