### ISSUE TITLE
Add ipdb_id to machine info

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#382]
Add ipdb_id to machine information. This will be used to do something like: link to "pinballvideos/?m=#{ipdb_id}"

When this is first set up, can you populate the field for all the existing machines using our current ipdb link? Like, right now ipdb_link has something like 'http://ipdb.org/machine.cgi?id=2699', with 2699 being the ipdb_id. So the ipdb_id is anything after the = in the ipdb_link.

Note that not every machine has an ipdb_link or will have an ipdb_id - there are a couple virtual pins in our db that aren't on ipdb.

And can the ipdb_id work in the url? Like, http://pinballmap.com/portland/?by_machine_id=#{ipdb_id} working the same as http://pinballmap.com/portland/?by_machine_id=#{machine_id}

**Comment by RyanTG** [comment]
There will be another step after this for the group IDs, wherein we'll assign a new group ID to our groups that is the same as what others are using. But the other folks are still figuring this out. Arno created an API to serve as the source of group IDs. But Andreas is looking at whether IPDB can incorporate it into their data themselves.

**Comment by scottwainstock** [comment]
We can't use the same "by_machine_id" filter for both. There's a potential for duplicates in ipdb_id and machine_id. I'll need to setup a different filter for by_ipdb_id.

I can copy over existing IDs from ipdb_link, yeah.

**Comment by scottwainstock** [comment]
84b8013f8f54d90db074c4bcd22215633f746f9a

I updated ipdb_id on machines that had an ipdb_link.

You can search two ways:

http://pinballmap.com/portland/?by_ipdb_id=5163
http://pinballmap.com/api/v1/region/portland/locations.json?by_ipdb_id=5163
