### ISSUE TITLE
[BUG] Search by machine in auto-complete is superseded by dropdown

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#384]
If you search by machine using the auto-complete textbox, the results are instead determined by the dropdown. For example, if you type in "Pirates of the Caribbean" while the dropdown says "ALL", then the results will be for ALL.

It doesn't behave this way for searching by location.

What about if you used the same solution that you recently came up with for adding machines to locations: https://github.com/scottwainstock/pbm/commit/6eec5b86dd13485befc73d4f7bcfbfe20b34f395 & https://github.com/scottwainstock/pbm/issues/378

So when you use the autocomplete, the choice jumps over into the dropdown. 

I think this solution would work for both "search by machine" and "search by location."

**Comment by scottwainstock** [comment]
Applied that "adding machines" solution to the location and machine searches.

aae54bbb9af5310f666fef099ad6fc96c9f99eb4
