### ISSUE TITLE
Update location timestamp with ajax

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#387]
So users will see the timestamp updated when they click the link, without having to refresh the page.

**Comment by RyanTG** [comment]
The timestamp isn't updating when machine comments are made. 

This location: http://pinballmap.com/portland/?by_location_id=880 had a comment yesterday, but still no timestamp.

**Comment by scottwainstock** [comment]
7749d9681fdbec811e20755cff30c8bb88b25eeb
