### ISSUE TITLE
Update timestamp when machine comments are added

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#389]
I tested this before the recent ajax update, but not after.

When machine comments are added, the timestamp isn't updated. But I think machine comments validly tell us when the location was last updated.

**Comment by scottwainstock** [comment]
I just tested this and it worked for me.

http://pinballmap.com/portland/?by_location_id=2360

Can you give me the steps to make this not work?

**Comment by RyanTG** [comment]
If it worked for you, then I was mistaken. And for that I apologize. Closing.

**Comment by scottwainstock** [comment]
Well I'm definitely not saying there aren't situations where it DOESN'T work. I just need help finding those situations.

**Comment by RyanTG** [comment]
I'll tell you if I come across a situation. I just tested it, and it worked. I don't know why it didn't work for me a few days ago, but I may have just made a mistake of some sort.
