### ISSUE TITLE
Edit location

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#393]
On the apps, users can edit phone number and location type. But we didn't add this functionality into the website.

We should add this to the website. I propose: adding a little "edit" button under the address (which I'd probably later change to a little pencil icon). 

When clicked:
- The phone becomes an editable field (can we make it only accept "xxx-xxx-xxxx" format? If so, we'd probably need an error when it's wrong); 

- and there's a dropdown for Location Type. 

- We could also add a dropdown for Operator (if there are any operators in that region's DB). 

- And there are "save" "cancel" buttons.

I don't think the editable fields needs to be located exactly where the, for example, phone number is displayed. The editable fields could simply be below the address (Phone, Type, Operator). I could do a mockup, if you'd like.

**Comment by scottwainstock** [comment]
This almost definitely doesn't look like how you want it to look like. So, it's here for you to style:

https://github.com/scottwainstock/pbm/tree/issue_393

...I added website to the list of things you can edit, because that seemed appropriate. But, if you want that removed I can do that.

For now it just silently doesn't update phone/websites that in an invalid format.

**Comment by RyanTG** [comment]
I added some stylage. 

We can try allowing users to edit websites. I think it will get hit by spammers, but hopefully we'll block them. Spammers seem to always include hyperlinks AND text. So we should allow hyperlinks but exclude, say, spaces (since spaces indicate that text, and not links, are being inputted).

**Comment by scottwainstock** [comment]
Makes sense. Right now the only rule is that it has to start with http://.
I can add a no spaces rule.

**Comment by RyanTG** [comment]
That might even be sufficient, given that the spam seems to often start with text... but I don't have firm data on whether that's truly the case.

**Comment by RyanTG** [comment]
The website input should also accept HTTPS

That often comes up in the admin section - sites like FB use HTTPS now.

Does the phone field only accept 000-000-0000, and not (000) 000-0000? What if someone is editing a different field, but the phone one happens to contain parentheses? Will the update fail?

If so, a possible solution could be to run a one time script that looks for "(000) " and replaces it with "000-"

**Comment by scottwainstock** [comment]
Can you make a new ticket for the HTTPS issue?
Phone only accepts 000-000-0000, if you want that updated just toss it in the HTTPS ticket, please.

I wrestled with the code for a while to make it update any SUCCESSFUL field changes, while just ignoring any failures. So it's not an all or nothing update.

app/models/location.rb the section that starts with "validates" shows you all the rules right now.

**Comment by RyanTG** [comment]
Perhaps I should have tested it before commenting. The edit did not fail (when editing a different field, when the phone field had parentheses).

**Comment by scottwainstock** [comment]
Yeah, that was a huge pain to get to work!

**Comment by RyanTG** [comment]
Sorry for assuming the worst. It works sweetly.

**Comment by scottwainstock** [comment]
It's definitely missing good "error notification", you know? I can see someone not putting http:// and being really confused why it's not working. I'll put in a ticket to beef that part up.
