### ISSUE TITLE
email operators with machine comments

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#395]
If a location is tagged with an operator, and that operator has an email in the db, then send them machine comment emails.

It would be nice to include a message with their emails: "someone left a comment on {region_url} on one of your machines. If you don't want to receive these messages, please contact pinballmap@posteo.org."

Doable?

**Comment by scottwainstock** [comment]
Very doable. Good idea.

**Comment by RyanTG** [comment]
Hmm, or what about a daily digest? Jonny in the Bay Area suggested this. Seems like a daily email would have less chance of annoying operators.

Subject: Pinball Map - Daily Digest of comments made on your machines - mm/dd/yyyy

Body:
Here's a list of comments made on your pinball machines that were posted today to {region_url}. We're sending this in the hope that it will help you identify, and fix, problems. If you don't want to receive these messages, please contact pinballmap@posteo.org.

Comment:
Location: 
Machine:

(we don't need to include device info or city)

**Comment by scottwainstock** [comment]
Do I send this right before midnight?

**Comment by RyanTG** [comment]
Yeah, sounds good.

**Comment by scottwainstock** [comment]
This starts today at 23:30 UTC. And then every day at 23:30 UTC. Unfortunately, UTC is all heroku scheduler allows us to use.

9e1dd59c09a6979ec1c5f521952b8a81c6b3b2a0

**Comment by RyanTG** [comment]
Sick. I should probably email the admins to tell them about this.

**Comment by scottwainstock** [comment]
ACTUALLY.... the first message will likely go out tomorrow. I disabled this until I could add a couple more tests to it.

**Comment by RyanTG** [comment]
Word. At a later point I may edit the text of the email. I was having trouble with it. And it may be useful to stress that they can't reply to the email, but HAVE to send messages to the address we included.

In my message to the admins today, I can say "this stuff is coming soon."

**Comment by scottwainstock** [comment]
OK, this is setup now. It'll run at 4:30p... but likely won't generate many messages today.

**Comment by RyanTG** [comment]
Reopening, since it doesn't seem to work yet.

**Comment by scottwainstock** [comment]
3d3912eecf97f030cd0941ba3976feb187bed79b

**Comment by RyanTG** [comment]
Not sure if it's working yet. I left a comment on a machine that I'm operating*, and didn't get an email today.

*I should start testing this on dev, rather than live.

**Comment by RyanTG** [comment]
Are you getting error reports?

**Comment by scottwainstock** [comment]
I'm not, no. I haven't had a chance to look into this lately... probably I will over the long weekend though.
