### ISSUE TITLE
One-time auto delete empty locations

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#396]
Many admins are not removing their empty locations. Can we run a one time script that removes all empty locations? 

At a later date, let's consider making this automatic. Possibly an automatic weekly? Could also have an opt-in option - like, opt-in for automatic removals...

**Comment by scottwainstock** [comment]
Is this a "fire when ready" situation on the one-time part?

**Comment by scottwainstock** [comment]
c740f057e7e388fbd556077ef29ce8b6b559c113

I added the "opt-in" flag to region, and a task that will do this deletion automatically. But, the task isn't on a cron to run right now. And I have NOT done this as a one-time yet.

**Comment by RyanTG** [comment]
Yeah, fire when ready. I'm curious to know how many get deleted.

**Comment by scottwainstock** [comment]
Delete 92.

**Comment by RyanTG** [comment]
Dang!
