### ISSUE TITLE
Better error notification from user location edit

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#401]
We should tell people about the website and phone format.

cc @RyanTG

**Comment by RyanTG** [comment]
Blog post: http://blog.pinballmap.com/2015/10/19/update-location-metadata-show-closest-locations

Nearly identical post: http://tiltforums.com/t/pinball-map-open-thread/901/52

I'll tweet it, too.

**Comment by scottwainstock** [comment]
@RyanTG Would you mind looking at: https://github.com/scottwainstock/pbm/tree/issue_401

I think I have the work done, but there might be some styling issues? If you look in https://github.com/scottwainstock/pbm/blob/issue_401/app/views/layouts/application.html.haml , you'll see I added a "flash-message" div. This is where the input error messages go. I see them being added correctly, but nothing displays on the screen. And, I assumed that was because of a css thing?

**Comment by RyanTG** [comment]
Pull requested.

I noticed that two errors messages come up at once (phone format and website format) there's no break between the two. If possible, it would be nice to add a semi-colon or something. The only way I could get them both to come up was when I was editing a location that already had an incorrectly-formatted phone number. So, if one already has (805) 222-2222, and you edit the website address and don't add http, then you'll see both errors.

**Comment by scottwainstock** [comment]
6b5d82caa8fbae22a318b5ca1f938e4aac9a1d1e

**Comment by RyanTG** [comment]
I just discovered that the flash dialog shows up after a successful update. But it's just two quote marks, with the pink box around them. No message.

We could keep it and give people a "Thanks for the update!" message. Or remove it, if possible.

**Comment by RyanTG** [comment]
I've been adding location type, and found that when the phone number is incorrectly formatted and I don't correct it, the phone error message is displayed twice (like, twice in one error box).

**Comment by scottwainstock** [comment]
Do you have a series of steps that reproduce this? I'm having trouble getting it to show up.

I fixed the "just two quote marks" issue, but I want to push out a fix for the other one at the same time.

**Comment by RyanTG** [comment]
My steps are:

- Get on the bus
- Open up pinballmap.com/la in the browser
- Show ALL locations
- Find a location that doesn't have a Location Type assigned (and that I'll know what it is, like a bowling center)
- Click to show location details
- If the location has a phone number that is formatted like (xxx) xxx-xxxx, add in a location type but don't change the phone number.
- Press Save

And two phone number errors would come up.

I'll try it right now on the desktop.

**Comment by RyanTG** [comment]
I was able to replicate it on the desktop.

**Comment by scottwainstock** [comment]
I think I was missing the "do this on a bus" part of things. I got them fixed now though:

a2a1f5882c8f931119573444955354a1ae2c3bc2

**Comment by RyanTG** [comment]
Yeah, it's just showing up once for me now. But, something I thought about: in this specific case, the phone error is coming up even though they didn't update the phone. And the update they did make (location type) still worked. So it might be confusing for users to see an error for the phone number even though their update worked and had nothing to do with the phone number.

**Comment by scottwainstock** [comment]
I went through and fixed most of the phone numbers (in the database) to be the standard xxx-xxx-xxxx format. There are some outliers, but I think I got the vast majority of them.

**Comment by RyanTG** [comment]
I'm guessing some of those outliers were from Canadian numbers that start with +1. I've fixed those on the Toronto map, but not BC.

**Comment by RyanTG** [comment]
Can we close this?

**Comment by scottwainstock** [comment]
I think so, yeah.
