### ISSUE TITLE
Take a look at this font

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#402]
https://github.com/ryantg/pbm/tree/newFont

It's probably too intense! I really WANT to like it, but I don't want to make the site too hard to read. I could definitely make the font more bold/dark in places, which would probably help.

I also made some other changes, such as hiding the entire header menu in a dropdown. And I tweaked some of the colors in some places.

**Comment by scottwainstock** [comment]
I really like it a lot, but I think a lot of colors on the site would have to change in order to have it "blend in". But, this isn't my area of expertise.

**Comment by RyanTG** [comment]
And the location info section is kind of a cluttered mess. 

I'll continue to motherfudge with it.

**Comment by RyanTG** [comment]
I messed with it some more. I think it's looking pretty good!

I think the most glaring things are the buttons (like the search and cancel and save buttons). That orange color doesn't really fit in. 

Does anything else stand out to you?

**Comment by RyanTG** [comment]
Updated most of the buttons. Still some more work to do.

**Comment by scottwainstock** [comment]
Yeah, it's definitely looking better. Here's my list of stuff I noticed being off:

* score ticker at the bottom right
* "add machine condition" button
* location detail infowindow on the map (not sure if that should change or not)
* add picture upload button
* add machine button
* add score button
* buttons in general I guess, yeah
* "Limit results to  or more machines."

**Comment by RyanTG** [comment]
Thanks. I've just pushed another commit. Check it out.

For the score ticker, I made the font the old sans serif. Same for "limit results". That seemed to make them more readable. Does the "limit results" not fit for you?

When you say "add picture upload button" you mean the button that says "upload", right? Or the button that actually says "add a picture of this location"? If the latter, do you not like the black background?

I had bad luck in the past changing the styling on the location detail infowindow. It resulted in the window sizing itself incorrectly. So I don't do anything to it anymore. 

I really like how the form looks on the /suggest page.

**Comment by RyanTG** [comment]
I don't need to do a pull request for you to see the latest commits, right?

**Comment by scottwainstock** [comment]
N. As long as you push to your branch, I can pull it down from there.

**Comment by RyanTG** [comment]
If you're down with this, I'm cool with rolling it out. I'm happy with it. There are a couple really small things to tweak, I'm sure.

Would I have to do a pull request from my branch to your master?
