### ISSUE TITLE
Continue Angular dev

### ISSUE THREAD

**Issue by slnovak** [scottwainstock/pbm#413]
Hey @scottwainstock,

I see that you started working on an Angular [branch](https://github.com/scottwainstock/pbm/tree/angular) earlier this year. Are you interested in trying to pick back up on it again? I noticed that the long page load times associated with the `Locations` controller is due to 600+ server-side partial renderings whenever a user browses through locations. We should be delegating that to a client-side app.

I'd like to help out with this. Would it be alright with you if I make another stab at implementing an Angular app or would it be worth trying to pick up on the work you did prior.

Cheers!

**Comment by scottwainstock** [comment]
This makes sense, yeah. PBM started off as a Perl project, then went to rails. I was HOPING to move it to a proper "one page" site using either Angular or Ember. There was synergy with some other projects I was working on in Angular, so I went with Angular.

I'd love to dust this off and try again, yeah. I'm totally fine with you starting completely over if you think that'd be better. I have no confidence that the work I've already done is useful.

It's possible to sit this on top of the rails app, right? I have a lot of (I think) well tested endpoints that could maybe be useful here. I like having code that's tested extensively, and it's daunting to me to think that we'd have to start over 100% and try to keep feature parity.

**Comment by RyanTG** [comment]
Possibly considering Ember in the future. But I don't think we need to keep this open. The work will be part of a slew of new issues.
