### ISSUE TITLE
Refresh site layout

### ISSUE THREAD

**Issue by slnovak** [scottwainstock/pbm#415]
In lieu of #413, is there any interest in considering a site re-design? A good example of a site that's similar to PBM is [workfrom.co](https://workfrom.co). Let me know if there's any interesting in talking out some ideas -- I'd love to help!

**Comment by scottwainstock** [comment]
@RyanTG is pretty much 100% in charge of all the UI/UX elements of the site.

Personally, I have no issues with a re-design or anything like that. But, it's something that you and Ryan should suss out if you guys think there's value in doing this alongside the JS work.

**Comment by RyanTG** [comment]
Thanks @slnovak. We've been discussing (outside of github) ideas recently for a redesign. http://workfrom.co will be added to the list of example sites. Can't say I love it, though. It's almost non-functional on mobile with location services turned off, the filters take up a lot of real estate, and contains a fairly complex array of features which I think detract from its immediate usability (PBM attempts to be really simple in goals and function). Our current design is modelled after foursquare, which perhaps gives the map too much prominence. 

If we didn't have a regional map-based model, it would be easier to compare us with workfrom, yelp, atlas obscura, and the like. But that's also something we're talking about. 

Also, I'm not too into bootstrap =/

**Comment by slnovak** [comment]
Hey @RyanTG,

Keep me in the loop for discussions. You're definitely spot on with respect to workfrom.co. I'm definitely interested in providing some input.

Cheers!

**Comment by RyanTG** [comment]
Cleaning up issues. I'm going to close this for now. We just did a site layout refresh (not a huge redesign, though). But it will continue to evolve.
