### ISSUE TITLE
Remove "show machines" toggle and always show machines

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#417]
I think the "SHOW MACHINES AT THIS LOCATION" toggle is unnecessary. It's just one more thing someone has to click to show machines. I can't think of a situation where someone wouldn't want to see the machines.

This comes up in this context: When you search by anything other than location, and there are multiple results. At that point, the results display an abbreviated version of the location info. Then you click a location to expand the info, but the machines list isn't toggled on. I think the machine list should be displayed after that click of the abbreviated location info.

So, to reiterate:
- REMOVE the "show machines at this location" toggle.
- Always show machines.

I delved into this on my own, but concluded that I'd probably do it in a messy way.

**Comment by scottwainstock** [comment]
This MIGHT be a sketchy move. The reason that we don't show them on load (unless you are looking at a single location) is that there are way way way more things we need to hit up the database for when we display machines. In the past, this made loading up initial screens slow.

I don't think it's a ton of work to make them always display.... but if this is something you want to do, I think we should push this to a branch and check out performance first. What do you think?

**Comment by RyanTG** [comment]
Hmm, yeah, I forgot about that performance issue.

But showing location details is always a "one location at a time" function - like, if you have a list of locations, you can only click to show the details for one of them at a time. Seems TO ME like adding "render machines" to showLocationDetail function (or whatever needs to be done) might not add too much load time. But yeah, it would be worth testing it out first in a separate branch.

**Comment by RyanTG** [comment]
I'm still thinking about this issue.

Scenario: 
- Lookup all the locations in a city.
- The simple list of locations loads like normal, showing which machines are at each location.
- If you click a location, it expands to show the location details (like normal) BUT ALSO loads the list of machines.

I know it's been a while since I made this issue, but from your response I can't tell if you thought I meant something slightly different. I don't see why this would make loading initial screens slow. The list of locations will load just like they do now. Only when you click a location will the detailed list of machines load.

**Comment by RyanTG** [comment]
this doth it https://github.com/scottwainstock/pbm/pull/789/commits/8a87a5877efeaf2bb4435ea02cf6d5ad03c5bf9e

As an aside, I'm struggling to use similar logic to lazy load the other location detail elements. But I'll try some more.
