### ISSUE TITLE
Super admin all region weekly digest

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#421]
The super admins (me and you) receive a single email that contains ALL of the digests.

(thought I'd put this in a new issue, so it doesn't get lost)

**Comment by scottwainstock** [comment]
b3bb3d63ea259c5be8874d47f3c11b1e54217479

**Comment by RyanTG** [comment]
Just double-checking - will this be a single email sent to the super admins, or one per region? 

I see .uniq, so maybe that means it will just be a single email.

**Comment by scottwainstock** [comment]
It's one per region... I just tacked all super admins to the list of people that each region email gets sent to.

Is that going to be annoying? It was just easier to code up on my end, I can change it to be one email if this is too annoying.

**Comment by RyanTG** [comment]
Yeah, I think it will be too cumbersome to go through them if they're all separated. That's like 70 emails per week! Sorry =/

**Comment by scottwainstock** [comment]
Makes sense. Please hold.

**Comment by scottwainstock** [comment]
eb68dcdf71ca1e4bfac01085469a929ecd1c1523
