### ISSUE TITLE
Auth-enabled website

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#429]
@RyanTG https://github.com/scottwainstock/pbm/tree/auth_required

The changes were quick/easy, I'll add some tests once we pin down the specifics of how we want this to work.

I think the #1 missing thing now is a way to notify users how/where/why to login... basically all the UX stuff. Suddenly people will be losing the ability to just modify the map at will, and that'll confuse a lot of people I'm sure.

You can use this link: http://localhost:3000/users/sign_out  ...to sign your user out and see the differences in the way the site works.

I verified that the Android/iOS apps will be able to plug-in to the new user system without issue.

What say you?

**Comment by RyanTG** [comment]
When logged out, I can't see any machines at the locations. I can see the comments, though, and the pintips link. See screenshot: http://blueskiesabove.us/pbm/PBM-auth.png

I think it will be important for us to track users. If we know that someone is fucking with a location, we should then be able to figure out who did that and then remove them as a user.

**Comment by RyanTG** [comment]
I'll try to think of how best to add login info.

I'm thinking the header should have "sign up/log in". And it should be somewhere in the results, too: "login to update this location" or something.

**Comment by scottwainstock** [comment]
@RyanTG Whoops, I just pushed code that should fix that machine name issue you found.

Also I added some tests and the beginning of the "log what users are doing" logic. It's not done yet, but it shouldn't be much more work.

Is this something we want to think about using? https://github.com/merit-gem/merit

**Comment by RyanTG** [comment]
Yeah, that gem look good!

I just pulled da code.

**Comment by RyanTG** [comment]
Even when not logged in, I can still edit the location description. The text is gone, but I can still click an area just above "link to this map result."

Also, is there logic to use for users who are logged in, like, "- if logged_in?"

**Comment by RyanTG** [comment]
If we're adding merit stuff, we need to figure out:
- Which types of merits we want to include (points, badges, etc).
- How people can show off their merit points.

Like, should a location have a "last updated by SSW (5,525) on Jan 01, 2016" ?

And/or if a machine is added to a location, perhaps it should have a default comment on it that says, "updated by SSW (5,525) on Jan 01, 2016"

And any time a user adds a comment, they 1) get more points, and 2) the "updated by..." gets updated.

Other login stuff: 
- Will they have a profile page that they can edit? When they first login, are they redirected to the previous page, or to the profile page (I think it should be previous page, if possible).
- Limitations on usernames. Right now our admins just have emails. But we don't want to display emails for our regular users, so they should be required to create usernames. I think we should limit usernames to like 8 or 10 characters.
- If an admin updates a location, should it say, "updated by Pittsburgh Admin"? I'm just thinking that if we make usernames, some admins might not take the initiative of creating one for their login, so we should default to using, "region_name Admin" rather than displaying their email address.

**Comment by RyanTG** [comment]
SSL/TSL Encryption: If users are sending us credentials, I think the site should use encryption (so it has https instead of http). Here's a new free option: https://letsencrypt.org/

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/blob/auth_required/app/views/locations/_render_machines.html.haml#L11  shows you the "are they logged in?" logic.

Didn't Eric or someone have some ideas for what merits/badges/etc should be? I don't really have a strong opinion/idea about how any of that stuff should work. I've never really done much posting/interacting with websites that do stuff like this, so I don't know what people are into. I think it's worth doing in SOME form no matter what... even if it's just a silly/minimal version.

> Like, should a location have a "last updated by SSW (5,525) on Jan 01, 2016" ?

Yeah that makes sense. So 5,525 is their "score" or something? Their "legitness"? Is there a standard for any of these sorts of things? Seems like there'd be a standard by now...

> Will they have a profile page that they can edit? When they first login, are they redirected to the previous page, or to the profile page (I think it should be previous page, if possible).

I think there should be a profile page. I think redirecting to the previous page is the way to go. The profile page should probably be a pretty minimal thing, right? Like maybe just a profile CARD? I don't know.

> Limitations on usernames. Right now our admins just have emails. But we don't want to display emails for our regular users, so they should be required to create usernames. I think we should limit usernames to like 8 or 10 characters.

OK, we can do that.

> If an admin updates a location, should it say, "updated by Pittsburgh Admin"? I'm just thinking that if we make usernames, some admins might not take the initiative of creating one for their login, so we should default to using, "region_name Admin" rather than displaying their email address.

Yeah, I like the idea of noting (maybe even in a different color?) the data that was provided by the admins.

**Comment by scottwainstock** [comment]
@RyanTG I just pushed some code that makes the sign in/up rely more on username than email. But, I think the new username field needs some styling.

**Comment by RyanTG** [comment]
Thanks. I'll style it. But why is the username field a "textarea" rather than an "input"?

**Comment by RyanTG** [comment]
> Didn't Eric or someone have some ideas for what merits/badges/etc should be?

I'll ask him. I don't have a good idea, either. 

> Yeah that makes sense. So 5,525 is their "score" or something? Their "legitness"? Is there a standard for any of these sorts of things? Seems like there'd be a standard by now...

Yeah, it would be how many points they've earned. And they earn points from making updates. I think we'd have to make up a standard for our site. Like, 50 points for adding or removing a machine; 15 points for making a comment; 10 points for editing location metadata; 15 points for adding a high score; etc. 

> I think there should be a profile page. I think redirecting to the previous page is the way to go. The profile page should probably be a pretty minimal thing, right? Like maybe just a profile CARD? I don't know.

I agree about a really minimal profile page.

**Comment by RyanTG** [comment]
Right now we have the "delete comments" feature turned off. Idea: for users with sufficient privileges this feature will be back on.

There are times when I would like to delete a comments, so that the previous one is the top one again. This mostly comes up when operators leave worthless comments that clearly seem designed to hide a critical comment.

**Comment by RyanTG** [comment]
Or, alternatively, if I could delete comments via the admin panel, that would be cool.

**Comment by RyanTG** [comment]
There should be a mechanism for banning users. Like, if a user is abusing things, seems like the way to block them is to disable their account and prevent them from creating a new one with that email address.

**Comment by RyanTG** [comment]
When signing up, can we require that users verify their email? Like, you sign up and get an email, then you have to click a link to verify that it's legit?

**Comment by scottwainstock** [comment]
@RyanTG I think I have all of this handled now in the "auth_required" branch. Can you hammer on that for a little bit? I think the "change password" screen needs some styling.

There's a 6 character username max. You can login using your email or username. You have to verify your email. We can ban users. Email addresses can only show up once in the system. We log who add/remove machines.

I still need to log who adds machine comments. But that doesn't feel like a showstopper for launching this on the website. I will add the ability to DELETE comments from the admin screen.

What do you think?

**Comment by scottwainstock** [comment]
I just pushed the ability to edit MachineConditions to live... cae6746ec1dde9832c5a5591f14bc936b02c91da

**Comment by RyanTG** [comment]
Do I need to do anything more than git pull upstream auth_enabled to get up to date?

**Comment by scottwainstock** [comment]
Maybe bundle exec rake db:migrate

**Comment by RyanTG** [comment]
Thanks. 

I'm having trouble logging in! The reset only allows username, and I don't know if I even have a user name with any of my users. 

When I try to login in using email/pw, I don't get an error message, but it doesn't login.

**Comment by RyanTG** [comment]
Now I'm trying to create a new account with an unused email.

I haven't received the confirmation email yet.

**Comment by RyanTG** [comment]
Yeah, the email/pw isn't working.

I did:
git pull upstream auth_enabled
bundle exec rake db:migrate

I wonder if I'm still missing something.

**Comment by scottwainstock** [comment]
For NEW accounts you need to verify your email address. You should see the
verification emails in the log output of the window you run rails s in.

Does that make sense?

**Comment by RyanTG** [comment]
Yeah, I'll check the log. I was expecting an email.

What's strange is that I can't login with my existing dev accounts. No error, just nothing happens. Were all the users removed from the db?



On April 24, 2016 5:00:58 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>For NEW accounts you need to verify your email address. You should see
>the
>verification emails in the log output of the window you run rails s in.
>
>Does that make sense?
>On Apr 24, 2016 4:35 PM, "RyanTG" <notifications@github.com> wrote:
>
>> Yeah, the email/pw isn't working.
>>
>> I did:
>> git pull upstream auth_enabled
>> bundle exec rake db:migrate
>>
>> I wonder if I'm still missing something.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/scottwainstock/pbm/issues/429#issuecomment-214065804>
>>
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm/issues/429#issuecomment-214069146

-- 
Sent from on high.

**Comment by scottwainstock** [comment]
You should be able to login using the email/password for an existing
account in your dev db. Maybe reset the password for a dev account, and use
the email link in the rails log to reset the password...and try that?

I was able to login as an existing user.

**Comment by RyanTG** [comment]
Yeah, something's up with my setup. Pasting the confirmation link doesn't work.

I can't reset my password because the reset form requires a username rather than an email. And I don't have a username for any of my accounts.

**Comment by scottwainstock** [comment]
@RyanTG What kind of symptoms are you seeing with pasting the confirmation link that makes you say it doesn't work? It's confirmation for a new account, right?

We need to come up with usernames for existing accounts I guess. For your dev database you can do something like this:

psql pbm_dev
update users set username='rtg' where email='gratzer@posteo.de';
commit;
\q

Then you should be able to reset that account's password. But I guess you could also checkout the CLEAN code, and verify that you are able to login to the admin site using your email/password.

**Comment by RyanTG** [comment]
I was able to create that user, and reset the password. But I still can't login. I get that 401 error in the log. argh

**Comment by RyanTG** [comment]
When I'm logged in (as an admin), I'm not seeing any user names for the users. And it's not clear how to ban them.

And where is the log of adds/removals?

**Comment by scottwainstock** [comment]
Do another pull and a rake db:migrate.

Check the user section in rails_admin again. You should see username now, and you should have a "is disabled" feature you can user on them.

Adds/removals will show up in rails_admin as "user submissions".

**Comment by RyanTG** [comment]
I see "is disabled" and the checkbox to disable them. Cool!

I don't see a username, though. Also, if I edit a user, there's the "region" dropdown on that screen. But for normal users, they shouldn't be assigned to any region. If I needed to edit a user for any reason (say if I disabled one and want to re-enable them) how would I not assign them to a region? Or does that field not doing anything for regular users. Speaking of that, how do I tell which user is an admin and which is just a regular user?

**Comment by RyanTG** [comment]
And "user submissions" is not there yet, right?

**Comment by RyanTG** [comment]
When a comment is added, there's a timestamp that says, "Updated: 25-Apr-2016". Can we change that to "Updated: 25-Apr-2016 by username"? 

Same for, "Location last updated: 2016-04-25" change to "Location last updated: 2016-04-25 by username"

**Comment by scottwainstock** [comment]
Y.

**Comment by RyanTG** [comment]
I could probably do this, once I know the variable to use.

**Comment by RyanTG** [comment]
Oh, though in the beginning updates made via the apps won't have a user. And we wouldn't want it to say something like, "Updated: 25-Apr-2016 by " without any username.

**Comment by RyanTG** [comment]
I still don't have "User Submissions." Strange!

**Comment by RyanTG** [comment]
How do users even get to "change password." I saw it once, but now I can't find it anywhere.

**Comment by scottwainstock** [comment]
To get to change password:
http://localhost:3000/users/sign_in
Click: "Forgot your password?"

Getting to "User Submissions:
You have to be a "super_admin" to see this. Are you a "super admin"?

I'll take care of this "updated by username" thing next...

**Comment by RyanTG** [comment]
For email alerts (comments, removals), can we include username and email of users?

**Comment by RyanTG** [comment]
If a logged in user submits a locations or sends a contact message, can their user name and email be included in message?

And are we tracking activity, in case we add the points system in later? Like, could we retroactively apply points?

**Comment by scottwainstock** [comment]
Can we start making these separate issues? It's hard to keep track of these.

**Comment by RyanTG** [comment]
This is a note to myself, but I'm putting it here in case you have feedback. It might be useful to have more description on the Sign Up page. Like, some text that explains why you need to login. I mean the "you must login to edit this location" text is pretty straightforward. But it might be useful to have some additional text. 

Also, what do you think about how I removed "Sign Up" from the "Log in / Sign up" link in the header? Hopefully people won't have trouble realizing that they too can sign up.

**Comment by scottwainstock** [comment]
@RyanTG Is that standard practice? To just have it say "Log in" even if the action also allows them to sign up? I'm for doing whatever the standard practice is. (and I don't know what it is...)

**Comment by RyanTG** [comment]
One standard thing I often see, which I don't like, is a big sign up link, and a small separate log in link.

But perhaps we should have two separate links.

**Comment by RyanTG** [comment]
I checked in with FM the other day. He said he's a little behind schedule, but expects to have the update done in... a month or something.

What's our plan with the iOS app? Are you going to bust the auth stuff?

After we add the auth updates to the apps, we'll probably have to then remove the ability for people using old versions to update the site. Otherwise, that would be a big loophole. But we should allow for a period where it's still allowed.

**Comment by scottwainstock** [comment]
I guess I'll be busting the auth stuff, yeah. I don't think it'll be too bad.... it'll just take me a minute or two to come up to speed. It'll be an adventure. I trust that FM was a good citizen of the code.

We can leave the API open for a while and then lock it down when you think it's appropriate. That'll be fine.

We'll need to work out some kind of API token or user system for people like pinball nyc.

**Comment by RyanTG** [comment]
We'll have to wait for his update first, right? I think he's continuing to clean up code and stuff.

**Comment by scottwainstock** [comment]
@RyanTG I'd like to wait for his update, yeah. It'll give me time to do the Android app anyway. 

I think I have all the current website requests done, right? I'm going to start working on the Android app.

**Comment by RyanTG** [comment]
Yeah, I think they're all done.

**Comment by RyanTG** [comment]
"We'll need to work out some kind of API token or user system for people like pinball nyc." nyc doesn't use the API - they just scrape the site. So they might not be affected. But others use the API, I think, like pintips? I used it on the pins and needles website. Not sure who else uses it. But we can look through our emails and stuff. The apps use it too, of course! Would the apps need tokens?

**Comment by scottwainstock** [comment]
That's what I'm working through right now. The dumb/easy way to do this is with basic http auth, and just have people send login/password along with all their requests. That's kind of goofy though, so I'll probably look into having a full-fledged token system.

So, apps and whoever uses the API would need to get a token. But, I'm looking into the mechanics of that.

I have a basic UI for the login/registration on the Android app now, so that's something.

**Comment by RyanTG** [comment]
That's tight.

I know the IFPA uses a token for their API. The dev is an admin of ours. I can give you his email if you want to contact him.

**Comment by scottwainstock** [comment]
We'll see. I'm going to start off with this and see how far I get: https://github.com/gonzalo-bulnes/simple_token_authentication

**Comment by scottwainstock** [comment]
I added that simple token auth stuff. It seems pretty good! Right now I have it set to optional, but it's a one-line code change to make it required once all the apps are ready for it.

Each user is going to get their own auth token. That token will get saved on the app after they login, and then sent (along with their email) to auth mobile devices.

People hitting the API directly can do something similar. They'll send their token along with requests, and that's their validation.

So, now I'll try and wrap up the Android stuff. I want to try and finally get the Android Wear work done too.

**Comment by scottwainstock** [comment]
@RyanTG Just in case this is helpful to you at some point... I pushed the auth_required code to the staging server. I'm using that server to test mobile devices now.

http://pinballmapstaging.herokuapp.com/

**Comment by RyanTG** [comment]
Oh cool. Thanks. Yeah, I was just testing things out via desktop browser inspector. But it's nice to actually have it on hand. I definitely like how the mobile header looks now. I might minorly tweak a few things still.

**Comment by RyanTG** [comment]
Well, auth enabled website is live. so, closing this.
