### ISSUE TITLE
Super admin can add locations to any region

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#433]
A region dropdown in the "add location" form.

**Comment by scottwainstock** [comment]
c3962f4d63a7cc2e7d2be594b3bb7c920d2acf92

**Comment by RyanTG** [comment]
I'm not sure that it's working correctly. I just logged in as my Los Angeles admin account, and I have the "region" option when adding a location (this user isn't a super user). And the zone field is not a dropdown - it has a plus/minus button, and when clicked the values are 1, 2, 3, etc.

**Comment by scottwainstock** [comment]
@RyanTG This is on the "create new location" screen? That seems to be working fine in DEV with non-super admins.

**Comment by scottwainstock** [comment]
And you say "region" option... is that a dropdown option or just the word region with no text/select field next to it?

**Comment by RyanTG** [comment]
Yeah, that screen. I just logged in as the portland admin, which is a super user, and the Region option is just the word. And the zone field is still the number interval thing.

To clarify my previous comment, when logged in as LA admin, the Region field had a select field. I was able to pick any region from the dropdown.

**Comment by scottwainstock** [comment]
Your LA account is a super admin though.

  13 | gratzer@posteo.org         | la              | t

But, can you try again? I bounced the server... I'm wondering if it didn't pick up the new rails_admin templates.

**Comment by RyanTG** [comment]
Oh, I didn't know that account was a super admin. It doesn't have access to Machines, or Users. While my portland admin does.

I just tried again as LA, and the "Zone" is still the interval thing. I can't pick actual zones from it.

**Comment by RyanTG** [comment]
I just tried to add a location to a different region, and it didn't work. While logged in as the LA admin, I tried adding Desoto Lounge to the Asheville map. But it still added it to the LA map. What do I do!

**Comment by scottwainstock** [comment]
I don't see that location in the database, so I'm guessing you deleted it?

I poked around at it a little bit, but I can't figure out why it's not honoring the region_id from the dropdown. It changes it at the last second. I've got a lot of work stuff going on under next weekend, but I can try and find time before that.

In the short-term, I can either revert the change I made for the super admin thing, or you can update the region on new locations directly in the database. What one is easier?

**Comment by RyanTG** [comment]
Yeah, I deleted it. It's easier to just move my roving admin account to the region I'm editing. You don't need to revert anything.

**Comment by scottwainstock** [comment]
This was tricky, but I think I got this nailed down in: cf4027da519dfd2b1cd39c9cc0418a93792cf22e

**Comment by RyanTG** [comment]
Nice! Seems to be working great. This will be really helpful.
