### ISSUE TITLE
Machine removals in API

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#434]
Read-only endpoints for machine removals.

**Comment by scottwainstock** [comment]
812c90804b8a5eecd1bd9ce514d9138105473747

I added a user_submissions endpoint. It's listed in the API documentation. I limit the results to ONLY be remove_machine submissions, the other types had people's emails/etc in them.

Here it is for Portland:
http://pinballmap.com/api/v1/region/portland/user_submissions.json

**Comment by RyanTG** [comment]
The json file doesn't seem to have all the removals in it. Like, yesterday two machines were removed from places in Portland, but they aren't listed in the json. Do you know why?

**Comment by scottwainstock** [comment]
I do know why. I put the code in a BAD PLACE... so it wasn't getting picked up by deletions coming through the API. I fixed it though. Fixed it well. Moving forward, we should get all the removals logged appropriately.

9976a16f6a98c2e5ffdecb2cdcc4b393ca59b72d

**Comment by RyanTG** [comment]
Sweet. Thank you.

Do you have any recommendations for what tools to use to "check the json file to see if there's an update, and then print something based on the update"? Tools, as in python or javascript (a specific library?) or php, etc. My initial search for python ideas is not coming up with much. But I'm giving up yet - just wanted advice.

**Comment by RyanTG** [comment]
I think with python I could figure out how to check once a day for any submissions that match TODAY, and then print those. That's not very refined, though.

**Comment by scottwainstock** [comment]
I could add the user_submission ID to the feed. That way you could keep
track of what the most recent one you've seen is. Does that seem good?

**Comment by scottwainstock** [comment]
Uh, it's just an auto-incremen

**Comment by RyanTG** [comment]
Seems like that would be good. If you add it, I'll try to use it.

**Comment by scottwainstock** [comment]
Oh wait, it's already in there. The field is called "id".

**Comment by RyanTG** [comment]
Tight!
