### ISSUE TITLE
Merge these two star trek machines

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#437]
Merge 1793 into 2165, retaining 2165.

(with names, this is merging "Star Trek (Stern)" into "Star Trek (Pro)", and "Star Trek (Pro)" should be the resulting name.

Thanks.

**Comment by scottwainstock** [comment]
glowing-dusk-5085::COBALT=> select machine_id, count(*) from location_machine_xrefs where machine_id in (1793, 2165) group by 1;
 machine_id | count
------------+-------
       2165 |   154
       1793 |    28
(2 rows)

glowing-dusk-5085::COBALT=> update location_machine_xrefs set machine_id=2165 where machine_id=1793;
UPDATE 28
glowing-dusk-5085::COBALT=> select count(*) from location_machine_xrefs where machine_id=1793;
 count
-------
     0
(1 row)

glowing-dusk-5085::COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT
glowing-dusk-5085::COBALT=>

**Comment by RyanTG** [comment]
Thanks.
