### ISSUE TITLE
Machine name autocomplete stops working

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#445]
If I pull up a bunch of locations (say, from a "lookup by operator" query), and add a machine to one of the locations, sometimes the autocomplete will stop working on any subsequent locations.

I'll try to replicate it tomorrow. But for now, the steps are:

- lookup by operator (or any query that have multiple results)
- expand a location's details, and add a machine (and/or remove a machine)
- expand another location, add a machine

At that point the autocomplete may stop. It seems inconsistent. But still, it happens regularly.

You suggested that it might be a JS issue.

**Comment by scottwainstock** [comment]
I'm able to repeat this in dev.

**Comment by scottwainstock** [comment]
@RyanTG OK I think this is fixed now... but we lost some styling on #add_by_machine_id and #add_by_machine_name. I wasn't sure how you wanted to address that, so I left it alone. It seems like the move here is to add classes to those inputs in app/views/locations/_render_add_machine.html.haml.

But, I left that for you... 

519e65e9402e8334501d7b522c33e40b8ad0015a

**Comment by scottwainstock** [comment]
I don't think this EVER worked, btw... autocomplete with multiple search results. So that's weird.
