### ISSUE TITLE
Redding restore

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#447]
Our old admin just got mad 'cause someone noted that one of his machines is out of order, and he removed every machine in the region from the map. I added them back manually, and added back some recent comments. But I didn't add back the older comments, and didn't add the operators to each location because I don't know that info.

If we restored the location to yesterday's data: 
1) can we just restore redding?
2) will the comments and operator tags be added back?

He didn't remove everything until after midnight, so if we restored midnight's data, then we'd be good. So if the answers to those questions are Yes, can you restore the redding data?

**Comment by scottwainstock** [comment]
So, this one would be good to try and restore?
Mar 26 2016, 2:44am

**Comment by RyanTG** [comment]
Aye.

**Comment by RyanTG** [comment]
Seems like it worked? I see that the operators are assigned to locations now.

**Comment by scottwainstock** [comment]
I don't think I did anything, so that's odd!

I restored the database locally... pretty sure I didn't do anything remotely.

**Comment by RyanTG** [comment]
Oh, huh. A user in the area might have assigned them.

**Comment by scottwainstock** [comment]
My backup has the same number of lmxes that the live system does. What kind of things should I be looking to restore?

DEV (restored version)
```
pbm_dev=# select count(*) from location_machine_xrefs where location_id in (select id from locations where region_id=62);
 count
-------
    26
```

LIVE
```
glowing-dusk-5085::COBALT=> select count(*) from location_machine_xrefs where location_id in (select id from locations where region_id=62);
 count
-------
    26
```

**Comment by RyanTG** [comment]
Machines, comments, scores, operators assigned to locations. I think that's it.

**Comment by scottwainstock** [comment]
I'm going to have to delete new data before I can get the old stuff restored... so expect things to look weird for a little bit here...

**Comment by scottwainstock** [comment]
I think this is good now, but let me know what you think. I deleted all the locations, then reloaded all the locations and lmxes. All the old descriptions and stuff should be left.

I didn't see any high scores for that region.

```
pbm_dev=# select * from machine_score_xrefs where location_machine_xref_id in (select id from location_machine_xrefs where location_id in (select id from locations where region_id=62));
 id | location_machine_xref_id | score | created_at | updated_at | rank | ip | user_id | initials
----+--------------------------+-------+------------+------------+------+----+---------+----------
(0 rows)
```

**Comment by RyanTG** [comment]
I think it's all good! Thanks.
