### ISSUE TITLE
Auth - include username & email in email alerts

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#453]
For email alerts (comments, removals), can we include username and email of users?

If a logged in user submits a location or sends a contact message, can their user name and email be included in the message?

(I think those two questions can be bundled together.)

**Comment by scottwainstock** [comment]
24f0437debca48be5026ff64345882f8c831eb20

**Comment by RyanTG** [comment]
I can't test this on dev, but I'll close it.
