### ISSUE TITLE
Auth - include username in "updated by" message

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#454]
When a comment is added, there's a timestamp that says, "Updated: 25-Apr-2016". Can we change that to "Updated: 25-Apr-2016 by username"?

Same for, "Location last updated: 2016-04-25" change to "Location last updated: 2016-04-25 by username"

Include logic so that the " by username" doesn't show up if user is logged in (only relevant so long as apps don't have user support).

**Comment by RyanTG** [comment]
After this is in, I'm going to see how long we can make usernames. I've been thinking that six may be too few. An operator like Quarterworld may want to use their entire name. If we can fit it in this "updated by" space, then perhaps we should.

**Comment by scottwainstock** [comment]
I think this is done now...

ef19e2c770741ef7ebf84fee73a6603ceab93d8a
3c3c9ef150cf7d881f7a56f5d89176ca02cf4c49

You'll need to rake db:migrate for this.

**Comment by RyanTG** [comment]
Hold on, I'm raking the backyard.

**Comment by RyanTG** [comment]
I see it in the location description, but not for machine comments.

**Comment by RyanTG** [comment]
Do you know how I'd add a span tag after the word "by"? I'd like to change the color of the username. All my attempts break the if statement.

**Comment by scottwainstock** [comment]
09e65efd3af009cf16e1ccb4d28adbc11e965e38

**Comment by scottwainstock** [comment]
This is probably done now.

**Comment by RyanTG** [comment]
Thanks!!
