### ISSUE TITLE
Auth - https

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#457]
This is probably a big one. But maybe it's easy. I think if we have a login, then we should have encryption. This is a free service that is widely used: https://letsencrypt.org/

**Comment by scottwainstock** [comment]
The main issue here is that it's $20 per month to support this on heroku...
https://elements.heroku.com/addons/ssl

... even though the certificate is free.

**Comment by RyanTG** [comment]
Dang! Fuck that.

**Comment by RyanTG** [comment]
I added a "please use a unique password" suggestion to the sign up form. In case our lack of encryption is ever an issue (which seems unlikely anyway), hopefully people will have listened to me (seems unlikely, as well)!

**Comment by RyanTG** [comment]
I'm still thinking about this. It just seems wrong not to have SSL. It could expose user passwords, and those passwords are pretty likely to be ones used on other sites, too.

One option is to setup up a donation button to pay for this. I have a feeling we can make $30/mo to pay for our hosting. But I can't guarantee that.

**Comment by scottwainstock** [comment]
Alright, let me look into some other options too. I just looked into the
heroku-provided one.

**Comment by RyanTG** [comment]
Reopening then. I didn't know that there were other options.

**Comment by scottwainstock** [comment]
Looks like this opened up on 5/18: https://devcenter.heroku.com/articles/ssl-beta#enable-the-labs-flag-and-install-the-heroku-certs-plugin

BUT...

```
scottwainstock@Scotts-MacBook-Pro-3 ~  $ heroku labs:enable http-sni -a glowing-dusk-5085
Enabling http-sni for glowing-dusk-5085... !!!
 ▸    Heroku SSL Beta is full, please try again later.  If you need SSL right now, we recommend checking our SSL:Endpoint add-on.
```

So, I guess we just have to keep trying back.

**Comment by RyanTG** [comment]
https://blog.heroku.com/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours

**Comment by scottwainstock** [comment]
Oh whoops... we'd have to be at least "hobby" level in order to do the free ssl stuff.

https://www.heroku.com/pricing

**Comment by RyanTG** [comment]
And Hobby is $7/mo + our existing $9/mo for addons? Is that how much we're paying right now (I don't think I see the full info when I log in)? If so, an additional $7/mo is cheaper than the $20/mo for SSL.

**Comment by scottwainstock** [comment]
Yeah it's definitely cheaper than $20/mo, plus we'd see performance
benefits.

We're paying $9 a month right now for the expanded DB size.

**Comment by RyanTG** [comment]
Latest documentation: https://devcenter.heroku.com/articles/ssl

This walkthrough for a rails app might be better: https://medium.com/should-designers-code/how-to-set-up-ssl-with-lets-encrypt-on-heroku-for-free-266c185630db#.7cndbkdqd

Seems fairly straightforward.

Or a gem (also handles renewal): https://rubygems.org/gems/letsencrypt-rails-heroku/versions/0.2.4

But apparently there's another solution that handles renewal. https://github.com/dmathieu/sabayon

Not sure if it's worth it.

**Comment by RyanTG** [comment]
Latest update to this thread: when we forced SSL, it messed up the current apps since those want to access the api via http. 

So the possible solution is here: https://github.com/RyanTG/pbm/issues/160

````
config.force_ssl = true
config.ssl_options = {
  redirect: {
    exclude: -> request { request.path =~ /api/ }
  }
}
````

**Comment by RyanTG** [comment]
I think we're good on this one.

**Comment by RyanTG** [comment]
Actually, I don't know if this is totally resolved. It's still really easy to cruise around all day on http rather than https. There doesn't seem to be anything that switches you to https when you click a link.

**Comment by scottwainstock** [comment]
@RyanTG Can you tell me how to reproduce this? I just messed around for a while in Chrome and was always redirected to https.

**Comment by RyanTG** [comment]
I'll try to figure out some specific steps. When I visit the site using Chrome while at work, I'm on http the entire time:

![not-secure](https://user-images.githubusercontent.com/632682/29087190-f50e497e-7c29-11e7-869d-e90bd4ec0e8c.jpg)

I get to the site by typing in "pi" in the address bar, and that sends me to http. I'm guessing that Chrome is just remembering what I've done in the past.

**Comment by scottwainstock** [comment]
Ah ha, OK... I did this in an incognito window, and I'm able to reliably
reproduce the bad behavior.

**Comment by RyanTG** [comment]
Possible simple solution:

https://www.chromium.org/hsts

Perhaps we need an "HSTS enabled server"...

**Comment by scottwainstock** [comment]
This seemed to work...
https://stackoverflow.com/questions/27377386/force-ssl-for-heroku-apps-running-in-eu-region

https://github.com/scottwainstock/pbm/commit/9b20c908af06e562d548e2ef79e4aed580f3d367

...but jeez that seems too easy. Works in my incognito window though.

**Comment by RyanTG** [comment]
That's pretty similar to one of the things we tried before (https://github.com/scottwainstock/pbm/commit/fbb752af3bb32aeb929ecd0455a2fb792efd5f5d) But I guess the difference here is that we're specifying it's only within production.

**Comment by scottwainstock** [comment]
Yeah... does it work though? Looks like it works!

**Comment by RyanTG** [comment]
Looks like it works, yeah. CLOSING.
