### ISSUE TITLE
Auth into the future

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#459]
Some ideas for the future:
- Rate places (a star rating is probably best). And it's visible to all.
- Check into a place. This might be sort of useless. But some people might want to have a record of how many times they played at a place.
- Mark a location as a favorite (and remove a place from the favo list). And then they can do a search just for their favorites.
- Email users when a machine has been added/removed to one of their favorite spots. A daily digest might work. This should probably be opt-in. And it may be a bad idea, due to the occasional errors people make when adding/removing. We don't want them to receive an email saying, "Adams Family was added; Adams Family was removed; The Addams Family was added."
- ~~When adding a high score, the "initials" section is automatically filled in with their username.~~ And each user can track their own high scores (like the high scores page will highlight their own scores). ~~We can also make it so only logged in users can add a high score (or did we do this already?).~~ (strikethroughs indicate completed ideas)

Just some ideas!

**Comment by RyanTG** [comment]
More future ideas:

- Simple profile page for users. On it, they can see how many machines they've added/removed, how many comments they've left. And which regions they've made their updates in.

**Comment by gibbousGH** [comment]
I'd like to see push notifications when a pinball machine is nearby!

**Comment by scottwainstock** [comment]
Thanks @gibbousGH, that's a good idea. I added issues to create this feature in iOS and Android.

https://github.com/scottwainstock/pbm-android/issues/63
https://github.com/scottwainstock/pbm-ios/issues/55

**Comment by RyanTG** [comment]
This would be related to "favorite locations"... a user suggested: "sending email updates when a chosen/followed location gets updated with new games or comments"

But email updates for new games or comments should be opt-in (two separate options).

**Comment by RyanTG** [comment]
- User can delete their own scores, should they choose.

**Comment by RyanTG** [comment]
We should just track things in their own issue. closing.
