### ISSUE TITLE
Notice and flash notice

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#460]
After signing out, you're sent to the home page, and there's a "signed out successfully" message. Looking at the code, this message is displayed twice.

Once as:
<div id="welcome">
<p class="notice">Signed out successfully.</p>

And once as: 
<div id="flash-message">
<div id="flash_notice">Signed out successfully.</div>
</div>

That second one is outside the welcome div (above it). At the moment the flash-message div is positioned off screen, so no one sees it. **Is it possible to not have the welcome notice, and instead just use the flash_notice?** The flash_notice div (which is inside flash-message div) doesn't load when there isn't a message, whilst the welcome notice div always loads (though sometimes it has no content). I think I'll have a better time styling the flash_notice. Thanks.

**Comment by scottwainstock** [comment]
d7b4fb1a9b0454949e37a3f6926acdfffef37dbd
