### ISSUE TITLE
Auth - Some final things

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#462]
~~1) Allow all admins to ban users.~~

~~2) Change username character limit to 15.~~

~~3) Show username and email in User Submissions (right now it shows user ID#).~~

4) Can we include machine comments and machine additions in User Submissions?

~~5) Allow all admins to see User Submissions for their own region. Right? It's seems important for admins to be able to track activity and ban people.~~

**Comment by RyanTG** [comment]
Oh, and I think it would be nice if after logging in or out, you get redirected to the previous page rather than the home page.

**Comment by scottwainstock** [comment]
username character limit change:
f31ad023208566ffbc51010c61439843e3935770

**Comment by scottwainstock** [comment]
Allow all admins to ban users:
7334bb9035bf2a42b931b06c42bbcb9028387ccd

**Comment by scottwainstock** [comment]
Show username/email in user submissions, allow all admins to see their own region:
56c134b083a6ea8350c7ab0c465cc5fd957312bd

**Comment by RyanTG** [comment]
Seems like admins can ban other admins now.

**Comment by RyanTG** [comment]
7) If a user has been banned, and then the try to login, it would be nice to have a message show up, "Your account has been disabled."

**Comment by scottwainstock** [comment]
It might be good to start making new issues for these... I'm going to lose track of this.

**Comment by scottwainstock** [comment]
New lmxes generate usersubmissions:
7eecdfbac58f503d1329855fe3b0876cf85367ea

**Comment by scottwainstock** [comment]
@RyanTG Maybe NEW issues beyond these can be new issues, please?

**Comment by RyanTG** [comment]
Done. I removed 6 and 7, and put them in new issues. 

But what about for "Seems like admins can ban other admins now"? That was a response to one of the original issues here.

**Comment by scottwainstock** [comment]
@RyanTG The original request was "Allow all admins to ban users". Admins are users, so what you are reporting seems like a new issue to me!

But hey here's a fix for that anyway... c8eda1d15b6a7162de03623644719583f38e61dc

**Comment by RyanTG** [comment]
That's true. I should have been more clear. Thanks.

**Comment by RyanTG** [comment]
I think you did all these. Closing.

**Comment by scottwainstock** [comment]
Naw, I still need to add machine comment makes user submission. I'll do
that tonight.

**Comment by RyanTG** [comment]
Ah ok. I wasn't sure if "New lmxes generate usersubmissions" encompassed that. Reopening.

Then I think that will cover all the crucial to-dos before launching. I'm working on an email for the admins, telling them about it and asking them to send us username requests.

**Comment by scottwainstock** [comment]
Alrighty. I'll get through the rest of  these and then get moving on the
Android app.

**Comment by RyanTG** [comment]
I don't have much experience with apps that have logins, so I don't know how much help I can be. My only real thought is that logging in should be a set it and forget it thing. Like they log in/sign up once, and then never have to do it again. I mean, they CAN log out if they want to. But if they don't want to, then they'll always be logged in.

Side note: A friend showed me this app the other day: https://play.google.com/store/apps/details?id=com.untappdllc.app&hl=en
And it has some great features:
- notify me when a place nearby has this beer.
- show popular beers
- check-ins
- ratings
etc.

Could be good for inspiration at some point.

**Comment by scottwainstock** [comment]
I don't have much experience with apps that have logins either... so I'll definitely run stuff past you as I'm coding it up. Is your phone situation one where you'll be able to check out beta builds?

user submissions when machine conditions are made:
c04a8b9a9f6dd092f0ac1b76d1eca7545f5a8893

**Comment by RyanTG** [comment]
new issue related to this incoming.

**Comment by RyanTG** [comment]
I'll install a new rom on my phone, with Google apps. Then I can test.
