### ISSUE TITLE
Auth - redirect after signing in/out

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#466]
I think it would be nice if after logging in, you get redirected to the previous page rather than the home page.

After logging out, I think it makes sense to stay on the current page.

**Comment by scottwainstock** [comment]
5479c22cdf52473b7c1b21e06aaf3bc23285a912

**Comment by RyanTG** [comment]
Re-opening. Right now after signing IN, it redirects you to the home page. Can we change it so that when you sign in, it redirects you to the previous page? For example, if you're at /portland, then you go to users/sign_in and sign in, it should redirect to /portland.

**Comment by scottwainstock** [comment]
afda1e72b2c87b377103eb9474e32263753c07e9

**Comment by RyanTG** [comment]
Sweet. thank ye.
