### ISSUE TITLE
Auth - message for banned users

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#467]
If a user has been banned, and then the try to login, it would be nice to have a message show up, "Your account has been disabled."

**Comment by scottwainstock** [comment]
I think this is close...
37ce98cbf9ece047e9d327c557760ddc1b86b71e

I see a flash error message in the DOM, but I don't see it displayed on the screen. Do you have any idea what might be going on?

**Comment by RyanTG** [comment]
Oh yeah. I'll unhide it.
