### ISSUE TITLE
Auth - more user submission points

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#470]
This morning, someone removed all the machines from a Redding location, AND they removed the phone number, website, operator, and type. Thanks, dude!

So now I'm wondering if we can include all those updates in User Submissions.

Phone number
Website
Operator
Type

**Comment by RyanTG** [comment]
Those Redding removals turned out to be legit!

**Comment by scottwainstock** [comment]
@RyanTG What about location description?

**Comment by RyanTG** [comment]
Yes, please.

**Comment by scottwainstock** [comment]
acb0edc430a5bc20f763f2c4a95427dd8b01c29a
7b60fe946e04ed8f17f479e5a979bd9467a4ae11

**Comment by scottwainstock** [comment]
Should be good... took a while because I had to refactor a bunch of stuff.
