### ISSUE TITLE
You are not authorized to access this page - flash message

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#474]
When not logged in, and visiting /users/sign_in there's a flash message that says "You are not authorized to access this page." I don't remember that being there. I think it was blank before.

When I log out from the rails admin, it sends me to /users/sign_in and that message is there rather than "You have successfully logged out."

So, seems like something changed here. It could be related to how we were showing a different notice div before. 

Solution: when logged out and visiting /users/sign_in, there shouldn't be any flash message. After logging out from rails admin, it should say, "You have successfully logged out."

**Comment by scottwainstock** [comment]
This one is interesting (to me)... what's going on is that when you logout from the admin page, we try to redirect you to the last page you were at (the admin page). You get sent there, you aren't authorized, so you are sent to the login page with an error message.

I added some logic to send you to the main page if you logout from the admin site.

24d1a212ec2117bbcd2e8b787bb31e2276bea6a7

**Comment by RyanTG** [comment]
Oh yeah, now that I think about it, when I said "When not logged in, and visiting /users/sign_in" I was actually visiting /admin, and then it forwarded me to /users/sign_in and gave me that message.

**Comment by scottwainstock** [comment]
So are we good here?

**Comment by RyanTG** [comment]
Yes.

and I just realized that I need to keep styling this message. When you're looking at a map and then you log out, the message is in a weird place. Is it possible for this flash message to be similar to the "Phone format invalid, please use ###-###-####" message that pops up and then disappears after a few seconds?

**Comment by RyanTG** [comment]
I realized I said, "yes" but then had another request. I'm going to make a new issue.
