### ISSUE TITLE
Super user unable to create new operators for OTHER regions

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#480]
On my super user account (the one where I can add locations to any region). I can create new operators, and choose which region I want them added to. But after I click save, they're always added to the los angeles region.

This is not a high priority.

**Comment by scottwainstock** [comment]
@RyanTG This should handle that...

e742a2295d77cb2b0bca39684dfa35c9ff5ee3ad

**Comment by RyanTG** [comment]
I finally tested this. The dropdown is there. But no matter what I choose on the dropdown list of regions, it still adds the operator to Los Angeles (which is the region that I primarily administer with that login).

**Comment by RyanTG** [comment]
not important.
