### ISSUE TITLE
More automation when adding new locations

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#481]
**For simplification, a synthesis of the proposed solution:**

When a user submits a location, the fields are automatically cleaned up by the google maps api, and the results are stored within rails admin. These submitted locations are flagged as hidden. Then the admin verifies the info, and "enables" the location.

More details below. The google maps api can geocode addresses based on incomplete data - and we would want to populate the fields with the geocode output (aka, with the cleaned up address data).

**Original first post:**

For a website that is so automated, adding new locations is pretty manual. I wonder if we can make this process simpler for admins. 

Current state:
- Locations are submitted by users
- They are sent via email
- Admins read the email, and copy/paste the data into the new location form

Pros:
- This manual copy/pasting forces admins to look at each of the fields and fix mistakes
- Users often submit bad/incomplete information, so we don't necessarily want to use their values

Cons:
- Admins have to keep track of these emails, and there is no record of them within /admin
- It leaves room for admin mistakes (misspellings)

Further research:
- I want to look at similar sites to see how they deal with this. Other site examples: Yelp, Google Maps

Solutions:
- pending...

**Comment by scottwainstock** [comment]
It would be possible to have these emails CREATE the locations, but flag them as hidden or something. Then we can include hidden locations in the admin weekly emails... to remind them to fix the data and unhide them.

Just a thought.

Or we could have the location submissions create "reminder" items that are sent to admins until they are acknowledged? That would be easier to implement.

**Comment by RyanTG** [comment]
The reminders would be within rails admin? And then you viewed them would they contain all the values that were submitted?

**Comment by scottwainstock** [comment]
It could be that way, yeah. We could email the reminders to admins a couple times a week or something?

**Comment by RyanTG** [comment]
When submissions are not valid for one reason or another (the location already exists, submitted to wrong region, etc), the admin would have to log in and shut off the reminder. I kind of think that would drive them nuts.

I think the best approach here is to simplify adding locations, as opposed to reminding them to do their duties. So, your first idea might be better for that.

**Comment by RyanTG** [comment]
Yelp's page: https://www.yelp.com/writeareview/newbiz

"Please note: This business page will not appear in search results until it has been approved by our moderators."

So I'm assuming the data is stored somewhere, and the moderators review/cleanup/approve the location.

**Comment by RyanTG** [comment]
Also notable is that although Yelp is sorta broken up into regions/territories, you don't specify a region in the form. I guess the location categorization happens automatically.

It would be cool to get more insight from a content moderator at Yelp* about their role, and how the form looks to them... but maybe that isn't necessary.

*Note that facebook and foursquare do not moderate new submissions. And people complain that there are lots of duplicates on those sites.

**Comment by RyanTG** [comment]
I think we should move forward with "It would be possible to have these emails CREATE the locations, but flag them as hidden or something. Then we can include hidden locations in the admin weekly emails... to remind them to fix the data and unhide them." I think this will really help to motivate admins to keep up with their queue. 

And, per Brian's email, perhaps the google maps API can help clean up the data (like, fix addresses). If not, that's probably ok.

If we wanted to include the machines, and have then automatically added when a location is added, then the submissions would have to include machine id (right?). Right now on the apps, machine names are taken from the database (more or less), while on the website, the machine names aren't autofilled.

**Comment by RyanTG** [comment]
I think this is related: It would be nice to have a record of deleted locations. Like, a tab in the admin menu that lists them.

I'm going through submitted locations that haven't been added, and as I go back in time the chances increase that a location has been added and since removed (I'm not so on top of my records that I know ALL the locations that have been added - I just have the list of submitted ones in an "In" box and I put the ones I know have been added into an "Out" box). So it would be nice to easily check if a location was already added (and if it's still on there, it will be listed in the Locations tab, and if it's been removed it will be listed in the proposed "Deleted" tab.

**Comment by RyanTG** [comment]
As part of a more automated way to add locations, we will also probably need to adjust the restrictions on the phone number format. Right now only xxx-xxx-xxxx is allowed, but google maps uses (xxx) xxx-xxxx. So we'd have to have it allow both of those styles (which I think is a good idea anyway, because it's sort of annoying to have to remove the parentheses each time we add locations).

**Comment by RyanTG** [comment]
Some news about google maps API updates https://maps-apis.googleblog.com/2016/11/address-geocoding-in-google-maps-apis.html

I wonder if we could use the Place API Place Autocomplete service to autocomplete the addresses that people submit. If we did, we'd have to switch to just one field for the entire address (rather than separate fields for address, city, state, zip). Some UI people think that's a better way to do address input forms anyway - one field. Or we could have it autocomplete the address based on a user typing in the location name (using Place Search service). All of this would probably only work on the website, and not the apps - right?

Just something to think about. It's unclear to me at this point how possible it is with our current geocode setup to do something like:

- User fills out address info
- We geocode it to generate lat/lon
- If the submitted address (or the lat/lon) matches a validated address (one that is already in google maps), then the validated address populates the submission fields. Then the admin simply has to approve the location without a need to fix the address spelling/punctuation.

**Comment by RyanTG** [comment]
I tagged this as post auth, though I know it's probably a big one.

**Comment by RyanTG** [comment]
I removed some unnecessary posts from this issue. And I put a "synthesis" at the very top.

I'm going to delete this comment.

**Comment by RyanTG** [comment]
Note from our chat: IF name/address/city fields are not filled in, don't let google maps geocoder correct the fields.

**Comment by scottwainstock** [comment]
@RyanTG Behold: http://pinballmapstaging.herokuapp.com/

To test... suggest a location via the form, then look at the "SuggestedLocations" object in rails admin. There's a button to promote the suggestion to a location.

If you like it, I can push it live. It's staging only right now.

https://www.youtube.com/watch?v=jVOZeT2W6Bo

https://github.com/scottwainstock/pbm/commit/ca4ec5fe84ba12fbeee0182e47418658672df819
https://github.com/scottwainstock/pbm/commit/464628891a2877779514270c3f20feb4b664b450

**Comment by RyanTG** [comment]
Initial impression is that this is dope. The location I submitted had a full address. I'll try it next with a half-assed address.

But for those cases, I think this issue https://github.com/scottwainstock/pbm/issues/658 needs to be addressed before we implement this. Because if the address needs to be cleaned up, and the lat/lon is wrong, then admins will have to manually type in the lat/lon when editing the location. 

However, what is more likely to happen is that the admin won't bother to delete the lat/lon so that it can be freshly generated. In those cases, we'll end up with a wrong lat/lon. So, I suggest that when Save is pressed the lat/lon be generated, regardless of whether those fields are filled in or not (right now they only generate if the fields are empty). I'll note this in the issue.

**Comment by RyanTG** [comment]
**Issue:** When I submitted the location, I included two machines. But they weren't added when I promoted the location. And once the location is promoted, the only record of the machines is in the email.

**Comment by RyanTG** [comment]
This what I've observed. Correct me if I'm wrong: 

- The SUPER admin (tzr on staging) can see submitted locations across all regions. Regular admin (ssw on staging) only see their own regions. 
- SUPER admin can edit a location before it's been promoted. Regular admin can not. Regular admin can only edit it after it's been submitted.

**Comment by RyanTG** [comment]
Man, this works really well! I'm psyched.

I haven't done too much experimentation with submitting bad addresses - so far I've just left out the ZIP field. And it's filled it in!

Two machines were added. Great!

Only suggestion I have is to display the machines in the review page. Like how "User inputted address" is a field, we could also have "User submitted machines" just so there's a record. Of course, if not all the machines get added (say they didn't use the autocomplete for one of them), then once the admin presses Promote, then that record disappears (except in their email). But oh well. We can see how this goes once it's in action.

**Comment by scottwainstock** [comment]
@RyanTG 

Always geocode locations when admins make changes to them:
https://github.com/scottwainstock/pbm/commit/000b455bfccbc26b6bca06ca1eb8ac4ca434e7a2

Always geocode SuggestedLocation on save, show machines suggested for SuggestedLocation
https://github.com/scottwainstock/pbm/commit/53aefa3c08fde7bcbcc560b432052f5c88c6d571

This is on staging now, what do you think?

**Comment by RyanTG** [comment]
The only thing that's missing is if you clear out the lat/lon field and then press save (when editing a location), it says "please fill out this field." Can that be fixed? Of course, you could make the argument that you now don't ever need to clear out those fields. But I think there will still be times when that happens.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/eee341e86a921889fcb4fa91f4bd06dfc6ff4e7c

Pushed to staging.

**Comment by RyanTG** [comment]
Awesome! Let's make it live. 

I just drafted an email to the admins telling them about this. AND I made an instructional video in case they don't want to read. Drive is processing the video, but I'll share it with you in a moment. It's my first take, and I ramble a bit. But I think it's ok.

**Comment by RyanTG** [comment]
Drive saved it as a micro video. Trying youtube.

**Comment by scottwainstock** [comment]
@RyanTG Is live.

**Comment by RyanTG** [comment]
I'll keep an eye on Quotaguard. If we're often getting close to hitting 25, then we should reevaluate my great plan to regenerate lat/lon each time a location is admin-edited.
