### ISSUE TITLE
bug - fix region crash on unavailable machine

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#482]
BC issue: 
  app/models/region.rb:18:in `block in machines'
  app/models/region.rb:17:in `machines'
  app/controllers/pages_controller.rb:33:in `region'

**Comment by scottwainstock** [comment]
80fcf415819d611aebe5fd97a27b2f7c16e80597

Someone keeps crashes Sacramento with this bug... so, hopefully this fixes things.

**Comment by scottwainstock** [comment]
FYI @RyanTG

**Comment by RyanTG** [comment]
Sweet. I don't get errors for this, so I didn't realize that Sacramento was breaking.
