### ISSUE TITLE
Remove "rank" part of high scores

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#483]
I was thinking about this last night (as I watched someone use the app to enter a high score): I don't think we need to record (or ask people to record) Rank. The scores alone are sufficient. Rank changes all the time, so that data point goes out of date quickly. While a "personal high score on x machine at x location" does not go out of date.

To remove, I guess we'd also have to do the apps simultaneously. And we should probably add something that automatically orders the scores for a machine based on the digits.

**Comment by scottwainstock** [comment]
@RyanTG Fuck rank.

3f396f476b7c9509aa79e56a9d77b8f37d80c074
