### ISSUE TITLE
Lookup by machine - include Lookup by City

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#484]
What do you think of this? Right now, if you lookup by machine, it ALWAYS shows you every instance of that machine through the entire region. Seems like it would be useful to have the option to limit that lookup by city (within the region).

Style-wise: There's a second dropdown (for city) underneath the machine dropdown/autocomplete. And it defaults to ALL. Note, it should only be a dropdown - doesn't seem like we also need an autocomplete.

What ye think?

**Comment by scottwainstock** [comment]
@RyanTG I think it's a good idea, but I feel like we're inching into "advanced search" territory, you know? I mean why wouldn't we also have a city option on the lookup by operator or type?

So, maybe it'd be better to have some kind of advanced search option or something?

**Comment by RyanTG** [comment]
Good point. I could see an advanced search option being like: small text underneath the lookup by dropdown/autocomplete that says, "advanced search" and when you click it it simply expands to show the additional options.

We'd have to come up with a matrix of what additional options should be shown for each lookup option.
