### ISSUE TITLE
One time script to blank out LMX comment with no machine conditions

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#485]
See scott's comment https://github.com/scottwainstock/pbm-android/issues/65#issuecomment-236450844

**Comment by scottwainstock** [comment]
Just ran this on staging...
{code}
update location_machine_xrefs set condition=null, condition_date=null where id in (select x.id from location_machine_xrefs x inner join locations l on l.id = x.location_id inner join machines m on m.id = x.machine_id inner join regions r on r.id = l.region_id where condition is not null and x.id not in (select distinct location_machine_xref_id from machine_conditions) and r.name='portland' and condition_date is not null);
{code}

Here are some locations that were affected by this (so we can verify that things work OK in the app):

{code}
-[ RECORD 143 ]+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
name           | portland
name           | Rialto Poolroom Bar & Cafe
name           | The Sopranos
condition      | Needs a little service, but still very playable. Don't expect to here the solenoid pop though.
condition_date | 2014-02-07
-[ RECORD 144 ]+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
name           | portland
name           | Wilshire Tavern
name           | The Wizard of Oz
condition      |
condition_date | 2014-08-07
-[ RECORD 145 ]+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
name           | portland
name           | Sam's Hollywood Billiards
name           | The Sopranos
condition      | loose legs/machine moves all around. but 3 plays for a dollar!
condition_date | 2014-06-06
{code}

**Comment by RyanTG** [comment]
Seems all good. I just checked on iPad and android.

**Comment by scottwainstock** [comment]
```
glowing-dusk-5085::COBALT=> update location_machine_xrefs set condition=null, condition_date=null where id in (select x.id from location_machine_xrefs x inner join locations l on l.id = x.location_id inner join machines m on m.id = x.machine_id inner join regions r on r.id = l.region_id where condition is not null and x.id not in (select distinct location_machine_xref_id from machine_conditions) and r.name='portland' and condition_date is not null);
UPDATE 2
glowing-dusk-5085::COBALT=> update location_machine_xrefs set condition=null, condition_date=null where id in (select x.id from location_machine_xrefs x inner join locations l on l.id = x.location_id inner join machines m on m.id = x.machine_id inner join regions r on r.id = l.region_id where condition is not null and x.id not in (select distinct location_machine_xref_id from machine_conditions) and condition_date is not null);
UPDATE 165
glowing-dusk-5085::COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT
```
