### ISSUE TITLE
Move locations into new region

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#486]
I created a California Central Coast region. And we want to move some locations in other regions into this one.

Move these locations from 8 to 93. 

3472
1569
6399
1563
1645
6869

Move these locations from region 5 to 93:

4613
5055
6640
6641

**Comment by scottwainstock** [comment]
Should be all set.

glowing-dusk-5085::COBALT=> \e
UPDATE 6
glowing-dusk-5085::COBALT=> \e
UPDATE 4
glowing-dusk-5085::COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT

**Comment by RyanTG** [comment]
FUCK! I meant to type region 92, not 93. Ugh sorry. So, I meant to say to move those to 92.... :(

**Comment by scottwainstock** [comment]
No big deal:

glowing-dusk-5085::COBALT=> update locations set region_id=92 where id in (
4613,
5055,
6640,
6641
);
UPDATE 4
glowing-dusk-5085::COBALT=> update locations set region_id=92 where id in (
3472,
1569,
6399,
1563,
1645,
6869
);
UPDATE 6
glowing-dusk-5085::COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT

**Comment by RyanTG** [comment]
Thank ye.

**Comment by RyanTG** [comment]
This is interesting. The locations are tagged with Zones, but those zones aren't in the new region. So, when Eric in the bay area went to delete that zone (since it's empty now), it warned him that it was going to delete the locations associated with it (even though those locations are in a different region). Not sure what to do. I could manually remove the zone tag from those locations.

**Comment by RyanTG** [comment]
I manually fixed them.

**Comment by scottwainstock** [comment]
Oh yeah, that makes sense, sorry... I just switched the region, zone and
everything else will stick around.

I guess we could write some scripts to handle this stuff in the future so
it's less error prone? Or, I could just be more careful.
