### ISSUE TITLE
Location Machine Xref in the admin panel - what is the point

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#491]
I can't even remember the point of http://pinballmap.com/admin/location_machine_xref 

If you click "Add New" you just get a comment box to edit. But that box isn't associated with a machine, and filling it out produces an error. If you click the Edit button on a machine, you get the same thing.

What is the point of showing Location Machine Xref in the admin panel? It could be just for deleting machines via the admin panel. But, you can easily just delete machines via the website. Not sure if we need this section!

**Comment by scottwainstock** [comment]
@RyanTG Should be done...

b5471c19a80bee25854dfe173a6f76711eca63f8
