### ISSUE TITLE
Erase existing high scores

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#498]
If I type the word "fuck" into the high score field, this gets generated: "User: hammer; Score: ; Date: Aug-30-2016"

It's a blank score. So the value was rejected, but the submission itself went through. If a score isn't valid, then the submission shouldn't go through.

**Comment by scottwainstock** [comment]
2222ad0a4ff4eff92230352fa32a92c29cc64f69

**Comment by RyanTG** [comment]
Should we also run a script that cleans out any that have no score?

**Comment by scottwainstock** [comment]
Good idea. Just did this on live. There were some blank scores.

**Comment by RyanTG** [comment]
Cool. So when auth goes live, all of the old scores will basically be invalid because they won't contain usernames, right? Or will they just stay in there, and all the new ones will have usernames?

**Comment by scottwainstock** [comment]
The old scores will show up with "unknown" or blank for users. But, I think
we should remove them anyway. High score reboot.

**Comment by scottwainstock** [comment]
I mean or we just leave it... whatever.

**Comment by RyanTG** [comment]
Reboot sounds good.

**Comment by scottwainstock** [comment]
```
delete from machine_score_xrefs;
```
