### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#509]
Initial mockup included here https://github.com/scottwainstock/pbm/pull/508

The things for you to fill in are in [brackets]

Tell me if any of these data are difficult to pull/display. If so, we can scrap them. And tell me if you can think of any other stats to include.

We should also talk more about POINTS. I need to check in on where we left off with that. If it's feasible, I think we should add it. And obviously we'll come up with the points quantities first.

We should add a profile page to the apps, too.

**Comment by scottwainstock** [comment]
@RyanTG What constitutes "[# of locations edited]"? Here's the current list of things we're tracking...

  NEW_LMX_TYPE = 'new_lmx'
  CONTACT_US_TYPE = 'contact_us'
  NEW_CONDITION_TYPE = 'new_condition'
  REMOVE_MACHINE_TYPE = 'remove_machine'
  SUGGEST_LOCATION_TYPE = 'suggest_location'
  LOCATION_METADATA_TYPE = 'location_metadata'

... also high scores.

**Comment by RyanTG** [comment]
I was thinking if anyone does anything at a location ( so, not suggest a location), then it counts. Is that helpful, or more unclear?

On September 8, 2016 8:10:13 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>@RyanTG What constitutes "[# of locations edited]"? Here's the current
>list of things we're tracking...
>
>  NEW_LMX_TYPE = 'new_lmx'
>  CONTACT_US_TYPE = 'contact_us'
>  NEW_CONDITION_TYPE = 'new_condition'
>  REMOVE_MACHINE_TYPE = 'remove_machine'
>  SUGGEST_LOCATION_TYPE = 'suggest_location'
>  LOCATION_METADATA_TYPE = 'location_metadata'
>
>... also high scores.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm/issues/509#issuecomment-245806842

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by scottwainstock** [comment]
@RyanTG So, deleting and adding machines counts?

**Comment by scottwainstock** [comment]
@RyanTG I don't really have strong opinions about this stuff, just trying to get the code in order is all.

**Comment by RyanTG** [comment]
Yeah, that counts. My thought is "here is how many locations you've contributed to. And we also list them, if possible. It would give users an idea of where they hang out.

On September 8, 2016 9:25:48 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>@RyanTG I don't really have strong opinions about this stuff, just
>trying to get the code in order is all.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm/issues/509#issuecomment-245816281

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by scottwainstock** [comment]
@RyanTG Sounds good. I almost have this done, but I'm going to need to add a bunch of stuff to user submissions to track locations better.

**Comment by RyanTG** [comment]
Thanks. In the future, I think it might be worth adding RATINGS (like a star rating system) and points. I'm not sure if there's any tracking stuff you can set up now that will help with that later on.

And the profile page would then show points accumulated, as well as, say, top ten rated locations.

**Comment by RyanTG** [comment]
I know last night, I said "not suggest a location" and then I just contradicted that in a recent email. Now I'm thinking we should include "# of locations suggested". But that stat should still NOT contribute to [# of locations edited].

Should I add it to the mock-up?

**Comment by scottwainstock** [comment]
@RyanTG No, that's OK. I can add it without a mock-up.

**Comment by scottwainstock** [comment]
1a8fd9d3a9a1fed6c3c884dbd6769b23372b2273

**Comment by RyanTG** [comment]
Moving the comments that are on the commit to here.

Ryan: 
Wow, nice.

Just thinking, I guess one downside to our high score system is that those scores disappear when the machine is removed.

With this stat tracking system, seems like we could add a points system to it if we wanted. Like, just multiply each stat by a number, then total them.

Do you think we should have also added "# of comments left". Not sure why I didn't think of that one...

Scott: 
Hi, my name is Scott. I can add a # comments thing, sure. And, I have some code coming that should fix the "scores disappear" thing. That's basically a bug right now. If you delete the LMX associated with a high score, the profile page will error. So, I'll fix that.

**Comment by RyanTG** [comment]
I enhanced the style on the profile page. There's some space between the numbers and the "Machines Added" text. That's so when the numbers become double or triple digits, they won't push the text. Hopefully it doesn't look weird.

Only thing I couldn't do (as I mentioned in the mess of commit comments) is adding comma delimiters to the high scores. Can you do that?

**Comment by RyanTG** [comment]
> If you delete the LMX associated with a high score, the profile page will error.

To add to that, this page errors, as well: "admin/machine_score_xref" (logged in as an admin user whose score was deleted)

**Comment by scottwainstock** [comment]
bedbd85ce0ce5bd521047e2cfc9b1c6eae106bbe

**Comment by scottwainstock** [comment]
# of comments left added: 3ed925da339f084c5dcabb837c71bffa91cf7ab3

Your styling looks good. Huge improvement.

Still need to do the deletion protection.

**Comment by RyanTG** [comment]
Heads up that the scores are showing "UNKNOWN" for the values.

**Comment by scottwainstock** [comment]
@RyanTG Check the user_submissions table. If you see submission_types of "new_msx" with blank user_ids, this is why you see "UNKNOWN".

In theory, this situation won't ever happen once we go live. new_msx is a new type on the auth_required branch.

**Comment by scottwainstock** [comment]
@RyanTG Oh wait sorry... I mean any OLD new_msx entries will cause this. I had to put the score in the submission field and parse it out of there. It's part of the "retain scores for locations/lmxes that are deleted" plan.

So, I'd delete any old "new_msx" entries and make new ones.

You'll need to do this again in the future... as I "harden" this.

**Comment by RyanTG** [comment]
Okay, cool.

I think this page is coming along great! I think it's a nice enhancement, and I think users will like it. Thanks for all your work.

**Comment by scottwainstock** [comment]
@RyanTG Yeah no problem, I think it's an important thing to add... and I think we can expand on it a lot in the future, so all this stuff kind of lays that groundwork.

**Comment by scottwainstock** [comment]
1665811f1a1550334f0ad0d8eb51be01142b59a3 protect against lmxes that disappear and mess up high score listing

**Comment by scottwainstock** [comment]
0a4dc56634a390527e955edff0ccc84c5e9bf8a5 fix rails admin crash (rank)

**Comment by scottwainstock** [comment]
@RyanTG I think everything in this ticket so far is addressed now.

**Comment by RyanTG** [comment]
CLOSING

**Comment by RyanTG** [comment]
Er, one more thing.

I couldn't add comma delimiters to the high scores. Kept getting errors.

**Comment by scottwainstock** [comment]
@RyanTG 30bd73b1b993c0043de11d9deb6616f64eb2b939 That should do it.

**Comment by RyanTG** [comment]
thx!
