### ISSUE TITLE
Can only edit metadata or add location description ONCE

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#513]
If you SAVE one of these edits:
location metadata
location description

Then you can't re-open the edit dialog. 

I just verified that this issue exists on the live site.

(reloading fixes it, of course)

**Comment by scottwainstock** [comment]
There are some big issues with the edit icons for locations... load up a zone with > 1 location, expand >1 locations... click the edit icon on one location... you'll see the edit functionality toggle on all expanded locations.

**Comment by RyanTG** [comment]
I think I fixed this. 

The solution is:
in _render_update_metadata
change the click function at the bottom to include #location_detail_location_#{l.id} .location_meta .meta_image`
instead of `.location_meta .meta_image`

I can commit it. But I figure you're working on these files.

**Comment by RyanTG** [comment]
I changed it on my end, if you want it.

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/pull/514 to fix that js error you mentioned. But this does NOT fix the initial problem (of the edit section not reopening after you've saved)

**Comment by scottwainstock** [comment]
a5c41ee4bca18f42c49f4ca289b9bee5aa17a338

@RyanTG This should fix the initial problem.
