### ISSUE TITLE
Remove "their name" and "their email" fields from location suggestion

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#517]
I removed those fields from the submission form. But those fields are still transmitted in the message to the admin.

I found them in these files: 
https://github.com/scottwainstock/pbm/blob/a839592751db8eef44547d72e0d19af50ce1dd36/app/controllers/application_controller.rb
https://github.com/scottwainstock/pbm/blob/a839592751db8eef44547d72e0d19af50ce1dd36/spec/controllers/pages_controller_spec.rb
https://github.com/scottwainstock/pbm/blob/4570504d5c631e10ef9b97e8436d39a32ae3d693/spec/requests/api/v1/locations_controller_spec.rb
https://github.com/scottwainstock/pbm/blob/auth_required/app/controllers/api/v1/locations_controller.rb

The "submitter_name" and "submitter_email" params are also in those files. (sorry, those files are from two branches.)

I'm hesitant to do it myself, because I don't want to break anything.

Also, I think it's fine for the "contact us" messages to be transmitted by unlogged in users.

**Comment by scottwainstock** [comment]
@RyanTG This is on the auth_required branch... but here it is....

2fcdd8fbd095513952a04d066cd62144c5af049a

**Comment by RyanTG** [comment]
Thanks. I only had master branch on there because github only allows you to search that branch.
