### ISSUE TITLE
title/meta properties in application.html.haml need refactoring

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#519]
It's too big and difficult to work with, the logic needs to be moved to a controller and tested.

**Comment by RyanTG** [comment]
But that's my masterpiece code!

**Comment by scottwainstock** [comment]
It'll still be there, just easier to read.

**Comment by RyanTG** [comment]
I meant that the unreadable mess is my masterpiece. It's modern art.

**Comment by scottwainstock** [comment]
a67fa09123d5c47b7409107732904e3e0db2460f
