### ISSUE TITLE
Remove unnecessary fields from submissions

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#526]
Even though I removed the NAME and EMAIL fields from the 'contact admin' and 'suggest region' forms (on android), those fields still show up (empty) in the sent emails.

e.g.

`Their Name:

Their Email:

Message: testing

Username: ssw

Site Email: scott@gmail.com`

So, those fields need to be removed from somewhere deeper inside (controller, api??). I'll try to take a look at it, but I might not be able to figure it out. You're the expert.

Forms:
Contact Regional Admin
Suggest New Region

**Comment by RyanTG** [comment]
The "Suggest New Region" messages aren't coming through (to me, at least). Not sure if that's because I'm on staging. But the other forms come through on staging.

**Comment by RyanTG** [comment]
@scottwainstock Do you think ONLY logged in users should be able to contact a regional admin? I'm torn on that.

**Comment by scottwainstock** [comment]
I think anyone should be able to.

**Comment by RyanTG** [comment]
Seems wise.

I just realized that we don't need to include the captcha on the location submission form, given that only logged in users can fill it out.

**Comment by RyanTG** [comment]
Note that on the Android app, only logged in users can contact the admin.

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/pull/538
https://github.com/scottwainstock/pbm/pull/535
