### ISSUE TITLE
Weekly ALL region email is not coming through

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#530]
Not sure why! The individual region emails are working.

**Comment by scottwainstock** [comment]
@RyanTG I looked at sendgrid... didn't see anything bouncing. My theory is that the emails have gotten so long that they are getting dropped somewhere downstream? I don't know.

So, I changed the all region emails to send the region info as a text attachment. Let's see if that helps. I've seen this sort of thing help at work.

**Comment by RyanTG** [comment]
Sounds good!

**Comment by RyanTG** [comment]
Was it supposed to send today?

**Comment by scottwainstock** [comment]
It was, and it did not.

**Comment by scottwainstock** [comment]
Running the process by hand (minus emailing the regular admins) worked fine.

It's possible we're being throttled for sending too many emails at once. I'll move the "email all" logic out to a separate task.

**Comment by scottwainstock** [comment]
9df8f272193a2d9ea5aa39dfd660f66135bae6e4

This is set to run at 1pm on Friday now. Running it by hand seems to work.

**Comment by RyanTG** [comment]
Could you tell if any of the admins aren't getting the message due to throttling?

**Comment by scottwainstock** [comment]
I didn't see anything bouncing in send grid, but I can't tell much more
without a paid subscription.
