### ISSUE TITLE
IFPA events not working

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#533]
SOME ifpa events are being posted, but many are not. I don't know why some are working. 

Example:
https://www.ifpapinball.com/tournaments/view.php?t=15171#calendar
is not showing up on the http://pinballmap.com/la/events page.

**Comment by RyanTG** [comment]
Did you do something? Looks like a buttload of tourneys were just added.

**Comment by scottwainstock** [comment]
I did nothing.

**Comment by RyanTG** [comment]
Weird. Well, I'm going to close this for now.
