### ISSUE TITLE
auto complete machine names in location submission

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#534]

**Comment by RyanTG** [comment]
They should be able to add multiple machine. They should also be able to NOT use the autocomplete, in case they're adding a brand new machine.

**Comment by scottwainstock** [comment]
@RyanTG I'm going to try and knock this one out... I should add an operator dropdown too, right? Like we did with Location Type? I figure the more data we can normalize here, the easier it'll be to do the "auto location creation" task.

**Comment by RyanTG** [comment]
Yes, op dropdown sounds ok. I think I didn't specify it in https://github.com/scottwainstock/pbm/issues/555 because sometimes there will be NEW operators. But I guess that's what the "comment" field is for.

I'm adjusting the style on that new fields commit right now.

**Comment by RyanTG** [comment]
Operator dropdown should default to blank.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/514071a9a548eb3fd1193dd02571bde8fc020afb

**Comment by RyanTG** [comment]
ganny.
