### ISSUE TITLE
Consider: send email to admins once a day

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#543]
We can discuss this:

Admins receive an email digest of the machine comments once per day (just like how operators get them once a day), instead of in "real time."

I sent this survey out to admins to assess their feelings: https://www.surveymonkey.com/r/XFF3FZF

Awaiting responses.

**Comment by RyanTG** [comment]
@scottwainstock How feasible do you think a radio button would be? Like, the admin can choose how they receive the emails. If we have a radio button, then I'm assuming it would be under /region and thus would apply to all the admins for that region (because that's where the email machine removal button is).

**Comment by RyanTG** [comment]
So far the results are pretty overwhelmingly in favor of a daily digest.

I'll keep updating this post with the results:

1. Do you want to receive an email every time a user leaves a machine comment, or do you want a single daily email containing them all?

**2** - Email for each comment 
**13** - Daily digest of comments


2. What about for when machines are removed from locations?

**2** - Email for each machine removal
**13** - Daily digest of machine removals

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/1ab389b8a96f0e330c52d3bc61cb5db0fac5ecc3

**Comment by scottwainstock** [comment]
One runs at 1am and sends data for the previous day. The other runs at 2am and sends data for the previous day.

**Comment by RyanTG** [comment]
Righteous! Thanks. I'll send the news to admins.

I'll close this. I'll test it on some of my regions.

**Comment by RyanTG** [comment]
Last night I got a blank email for Hawaii (after signing up for digests yesterday). However, no comments were left on Hawaii machines yesterday. My suspicion is that it's sending the email even when there aren't any comments. But I'll confirm this tomorrow.
