### ISSUE TITLE
/admin/user on staging - error 500

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#546]
Can't view or edit existing users on staging. It's just a blank page. 

On dev, I can see the error:

 Showing /home/rgratzer/.rvm/gems/ruby-2.1.2/gems/rails_admin-0.8.1/app/views/rails_admin/main/index.html.haml where line #99 raised:

undefined method `last_login_at' for #<User:0x007f137e4a2c00>
If you want to use a RailsAdmin virtual field(= a field without corresponding instance method),
you should declare 'formatted_value' in the field definition.
  field :last_login_at do
    formatted_value{ bindings[:object].call_some_method }
  end

`                - if @other_left_link ||= other_left && index_path(params.except('set').merge(params[:set].to_i != 1 ? {set: (params[:set].to_i - 1)} : {}))
                  %td.other.left= link_to "...", @other_left_link, class: 'pjax'
                - properties.map{ |property| property.bind(:object, object) }.each do |property|
                  - value = property.pretty_value
                  %td{class: "#{property.css_class} #{property.type_css_class}", title: strip_tags(value.to_s)}= value
                - if @other_right_link ||= other_right && index_path(params.merge(set: (params[:set].to_i + 1)))
                  %td.other.right= link_to "...", @other_right_link, class: 'pjax'`

Jesus, can't format this. Here's a screenshot.

![user_error](https://cloud.githubusercontent.com/assets/632682/20912521/a6e379b6-bb24-11e6-98d9-927e89e3c487.png)

**Comment by scottwainstock** [comment]
Deploying this now:
https://github.com/scottwainstock/pbm/commit/88a3abfbf14e16140d656dafd9e85a74ce14d0fa

**Comment by RyanTG** [comment]
DAMNIT. Me again, screwing things up. I tried not to be sloppy when I changed the urls, but I clearly missed a couple things. :<
