### ISSUE TITLE
Giving usernames to current admins

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#549]
Discussion about this.

I don't want to give the beta test to admins right now, because they don't have usernames. And they can't login with their email address and give themselves a username.

Some things to consider:
auth_tokens

When we go live, it would be nice to have usernames in place for EVERY admin.

**Comment by RyanTG** [comment]
And do we want to give admins the ability to change usernames. In light of the fact that we're probably going to auto-generate names for them, I think they should be able to edit their own username. And the super admin should probably be able to do that, too (for all users).

**Comment by scottwainstock** [comment]
@RyanTG Is it safe to assume that I can get this data in a csv with the following header...

email|username

?

**Comment by RyanTG** [comment]
Yes, that's the exact format I have it in right now.

**Comment by RyanTG** [comment]
I'll send you the csv this Friday. I doubt it will grow much after that.

**Comment by scottwainstock** [comment]
```
update users set username='foo', confirmed_at=now(), confirmation_sent_at=now() where email='bar';
```
