### ISSUE TITLE
When super admin edits a user, they automatically become an admin

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#552]
If the super admin edits a user - for example, to change their username or password - the "region" dropdown will select a region (at the moment, Toronto is at the top of the list). There's no way to not select a region. So I think we need to have a blank entry at the top of the region list, or something.

![selection_016](https://cloud.githubusercontent.com/assets/632682/20950213/3355364c-bbd3-11e6-9e52-ad2a58f6e329.png)

**Comment by scottwainstock** [comment]
This should do it: https://github.com/scottwainstock/pbm/commit/36247e65a48d87db7684cbc2ad5608e149a660ad

**Comment by RyanTG** [comment]
AWESOME

![snl_1627_04_girlfriends_talk_show](https://cloud.githubusercontent.com/assets/632682/22193379/b8e1099e-e0ef-11e6-9545-1a69fb48e2a7.png)

**Comment by RyanTG** [comment]
You down with that reference?
