### ISSUE TITLE
Additional fields for submit location form

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#555]
In the form, we do not include:
zone
type
description

I don't think we should include zone. But I think we should add dropdowns for Type and Operator. Not sure about including Description, because people might use it to write notes to us (which is fine, except if we eventually add more automation to location submissions, then we'd probably want a separate "notes" field).

If we add these fields, we should also do it on the apps.

**Comment by bpoore** [comment]
I'm new to Open Source, but have bee a huge fan of the Pinball Map for years. I would like to start working on this enhancement. 

To make sure I'm getting off to the right start, I would update the form to have the additional input fields and have the input values populate the database?

I agree the zone shouldn't be included in the submission as most users are unaware of their zone id.

**Comment by RyanTG** [comment]
Cool! Scott can probably give way more details than I. But no, the submission doesn't populate the database. It's just sent as an email to admins.

Though this may change in the future. See https://github.com/scottwainstock/pbm/issues/481

Also, the auth_required branch is WAY ahead of master right now (though it's going to be merged in about a week). That's something to keep in mind. You might want to work on auth_required - or fork that branch.

**Comment by bpoore** [comment]
Ok, cool! Thank you for the info, I'll work from the auth_required branch.

**Comment by RyanTG** [comment]
@bpoore We merged auth_required into master. Just FYI!

**Comment by bpoore** [comment]
Thank you for the heads up! Sorry, I haven't been able to make progress yet. I have never used Ruby on Rails before this and having to watch some tutorials to get myself familiar with what's going on.

**Comment by RyanTG** [comment]
No problem! Take your time. Hope you learn something from it! And if you decide to bail on the issue, just let us know. No pressure - and thanks for helping out!

**Comment by bpoore** [comment]
Thank you for your patience as I tried to make sure I understood the code base better. I like the new updates! With auth_required now, how do I go about being able to see the updates I've made to the page from my local version of pbm.dev? If I try to select Join or Login I get "pbm.dev refused to connect". If you don't mind walking me through what I'm missing, I can update the README to include these new steps. Thanks!

**Comment by RyanTG** [comment]
I just relooked at those instructions. I don't do "open http://pbm.dev".

I start the rails server with `bundle exec rails s` and then visit the local site at http://localhost:3000/

Does that help at all? Also, I made some really brutish url changes on the site, where even dev uses https for the protocol. But in a local environment, that messes things up. So you need to change the url to http on the login page. But it might produce other problems, too (like, logging out seems problematic right now).

Lastly, with your database dump you might not have a login account on your local setup. Tell me/Scott if you need one.

**Comment by bpoore** [comment]
Thanks! That worked! Just asked Scott for the database dump and to see if it has a login account.

**Comment by scottwainstock** [comment]
We do generate an entry in the user_submissions table when people make a location suggestion. You'll see reference to what we expect to happen here:
https://github.com/scottwainstock/pbm/blob/master/spec/controllers/pages_controller_spec.rb#L141

https://github.com/scottwainstock/pbm/blob/master/spec/controllers/pages_controller_spec.rb#L171 is where we test the user_submission in the database bit.

**Comment by bpoore** [comment]
#634

**Comment by RyanTG** [comment]
This is great @bpoore!! Thanks!

I'm making some small css adjustments. Those textboxes within %li are annoying. When they resize, they don't push down the li below. So I removed the resize for now ;p

**Comment by RyanTG** [comment]
While I don't disagree with adding a "Comment" field - I just can't remember discussing that. Did we discuss that in another issue, or was that your own initiative?

**Comment by bpoore** [comment]
Sorry, that should have been description! Should I change it to description? My bad! Seems like description was even up in the air to include... don't mind changing or removing!

**Comment by RyanTG** [comment]
Let's think about it. Because it might be worth having both Comments and Location Description. Now that Scott just made Operator a dropdown, there might be instances where someone wants to type in a NEW operator. And we wouldn't want them to do it in the Description field. So in this case, a Comments field makes sense.
