### ISSUE TITLE
Allow html in MOTD

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#563]
There are a lot of MOTDs that contain links. But the links aren't hyperlinks, but rather just a string. It would be cool if this field can support HTML. Or, better yet, if it could recognize http://....com and automatically turn it into a hyperlink.

**Comment by bpoore** [comment]
#643

**Comment by scottwainstock** [comment]
Thanks!

**Comment by RyanTG** [comment]
Yeah, thanks! That's really cool.
