### ISSUE TITLE
Show closest locations broken?

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#572]
This doesn't seem to be working on the live site right now.

**Comment by RyanTG** [comment]
What browser, and version, are you using? If Chrome 50+, I'm aware of this issue https://github.com/RyanTG/pbm/issues/151

I should probably only make issues on your issue page, and then assign mine to me.

**Comment by scottwainstock** [comment]
Oh yeah OK, sorry. Version 55.0.2883.95 (64-bit)

Works great in Firefox 45.0.2.

**Comment by scottwainstock** [comment]
Dupe of: https://github.com/RyanTG/pbm/issues/151
