### ISSUE TITLE
How to deal with changing a region name

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#574]
Once we have a system in place for changing a region name:

Change:

- Central Indiana to Indiana
- Burlington to Vermont

We should probably go back and change all the other region's where I've updated the name:

- Oklahoma (formerly Oklahoma City)
- Massachusetts (formerly Boston)
- West Michigan (formerly Grand Rapids)
- Wisconsin (formerly Milwaukee)

I think that's it, though I'm just going by memory... 
However, in those cases, we wouldn't be changing the name from what it currently is. Not sure if that's a problem. 

**The System**

This will involve copying data to a new region. 

It needs to include user data, too. So, for example, if a user edited location 1234 in Burlington, they should have a record saying they've edited location 1234x in Vermont (and the old Burlington record should be wiped). On that note, the location IDs are likely going to change.

Admins will need to be carried over, too.

What else?

**Comment by RyanTG** [comment]
I know we tested what happens on the iOS app when we delete a region: the app just goes to the region select screen. Next I'm going to check on what happens in Android. Just so we know for sure.

Steps:
Open Android app to a region that I'm about to delete.
Close Android app.
Delete region.
Open Android app.

The reason I'll close the app is that we should just assume that no one, or almost no one, will be using the app when we delete and create a renamed region. Some people might be actively using it. I'm guessing in that case they'll see the 400 or whatever error. I guess I could test that, too.

I'm just going to delete some little-used regions on dev.

**Comment by RyanTG** [comment]
It crashed the android app. And there was no way to get around it. Issue incoming.

**Comment by scottwainstock** [comment]
@RyanTG We probably should have talked about this on Sunday. Am I correct here in saying:

If we wanted to move "portland" to "foo":

* create region called "foo" (not this script)
* move all data from Portland to "foo" (this script)
* delete region called "portland" (not this script)

?

Basically, this script just moves data and leaves an empty region when its done?

**Comment by RyanTG** [comment]
Yeah, that's the gist.

BUT, note that I'd like to also copy a few regions and retain the same name. I'm not sure if that's possible. But some regions are screwed up (on the iOS app, for some users) because of how we changed their names previously. I'd like to start them fresh. For those could we do:

- Create a region called "temp"
- move all data to temp
- delete old region
- create new region "Oklahoma"
- move all data from temp to Oklahoma.

**Comment by scottwainstock** [comment]
OK, that should be possible.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/d4762a7a59c088fa8654c84fd0581f0401fc9484
https://github.com/scottwainstock/pbm/commit/a11aa8ad09983bb2412596266af93bfa9e8c78d3

**Comment by scottwainstock** [comment]
That should do it. I recommend playing around with it in dev for a little bit before we use it in live. It seemed ok on my machine.

You can test it by typing...

```
bundle exec rake move_region_contents FROM_REGION_NAME TO_REGION_NAME
```

**Comment by RyanTG** [comment]
I'll give it a try!

So, just to be sure: the admin of the from_region gets copied to the to_region? And same for user_submissions, events, etc. 

I'm assuming that location_ids change, right?

**Comment by scottwainstock** [comment]
All the stuff that changes is here:
https://github.com/scottwainstock/pbm/blob/master/app/models/region.rb#L158

It's just a change of "region_id". No other IDs should change... I just
point all the objects from one region to another.

**Comment by RyanTG** [comment]
Oh right, because it doesn't COPY a region, but rather MOVES a region. I'll test it out! 

On live, I presume you'll be running the script? I don't know how to do that on live...

**Comment by scottwainstock** [comment]
I can run it or you can run it... up to you. It's just sending that bundle
exec command through the heroku cli.

**Comment by RyanTG** [comment]
On my first test, it all but one location. There's one location chilling in the old region.

I'll again. And I need to do a region that isn't totally empty on dev...

**Comment by RyanTG** [comment]
Second test was swell.
Can't wait to use this! Thanks for putting it together.

**Comment by RyanTG** [comment]
I don't use the heroku cli for much. Is it `heroku --app app-name bundle exec etc` or `heroku run bundle exec etc` ?

**Comment by RyanTG** [comment]
Not sure what I did wrong:

````
heroku run bundle exec rake move_region_contents burlington vermont --app glowing-dusk-5085
Running bundle exec rake move_region_contents burlington vermont on glowing-dusk-5085... up, run.7794 (Hobby)
rake aborted!
Don't know how to build task 'move_region_contents' (see --tasks)
/app/vendor/bundle/ruby/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.1.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
(See full trace by running task with --trace)
````

**Comment by scottwainstock** [comment]
Code isn't deployed. I didn't push it to heroku last night.

**Comment by RyanTG** [comment]
word.

**Comment by RyanTG** [comment]
Just changed Burlington to Vermont. Checked on iPhone, and it was great!

**Comment by scottwainstock** [comment]
Nice. I'm glad that ended up being easy to do.

**Comment by RyanTG** [comment]
I found that if a phone number contains an empty space at the end of it, that location will fail to move over. Wisconsin had 47 locations like that! Since I had all the rest of the locations in a temp region, I had to quickly manually edit those 47, and then join them together. All is well now.

**Comment by RyanTG** [comment]
Note to self:

mid-michigan to michigan-mid

redirects: burlington; central-indiana
