### ISSUE TITLE
Include date on user_submissions

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#576]
On the Admin page, when reviewing user_submissions, it would be nice to know when the actions were taken.

So, make DATE a new column.

**Comment by scottwainstock** [comment]
This was already available on the list page, you have to click the "..." to see it.

I added it to the show page though: https://github.com/scottwainstock/pbm/commit/4e7fbfa8c8685ec59e5e197c87bb5632c78e58a4

**Comment by RyanTG** [comment]
My bad. I'm a kook.
Thanks for adding it to the show page!
