### ISSUE TITLE
Timestamp added when a new machine is added to a location

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#577]
When a machine is added to a location, it automatically adds "Updated: Feb-06-2017 by ssw" - which is essentially an empty comment with a timestamp (right?).

BUT, I just tried to replicate this, and I failed, using the website and the Android app. I added a machine to a location via the website and also via the Android app, and it did NOT automatically include the empty comment/timestamp. So, does this only occur with additions made via iPhone?

**Comment by scottwainstock** [comment]
Looks like additions on iOS are creating blank user comments if people don't enter one at creation time. I'll make an iOS issue to fix this.
