### ISSUE TITLE
Provide permalinks for searches

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#581]
We currently provide permalinks for individual locations. And we _have_ permalinks for (most/all?) searches, but we don't display those permalinks after a search is conducted.

So, we should include a permalink for each search. A use case is: Someone searches for all the locations with 5 of more machines, or all the locations by an operator, etc. And then they can copy the link for that search and share it. Once shared, the next user will see the same search. 

The link will popup after a search is conducted. For individual location lookups, it will be redundant with "Link to this map result" - so we should consider removing that and just using one consistently-designed link. File structure-wise, I guess it should be located at the very top of the lookup div? Then I'd position it somewhere on the page so it stands out.

Would be cool to include a "LEFT click to copy to clipboard" functionality.
http://stackoverflow.com/a/22581382
or a 10kb library https://github.com/zenorocha/clipboard.js

**Comment by RyanTG** [comment]
Tried to figure this out on my own. My assumption is that the [url variable](https://github.com/scottwainstock/pbm/blob/e742a2295d77cb2b0bca39684dfa35c9ff5ee3ad/app/assets/javascripts/application.js.erb#L108) generates the url. But I couldn't figure out how to get it out after the form is submitted. url is undefined, etc.

**Comment by RyanTG** [comment]
Dang, almost have it.

I did this: 
When the Search form is submitted, the serialized url (well, the suffix (example: `utf8=%E2%9C%93&by_location_id=2360&by_location_name=`)) is stored as a variable. 

Then in the _locations file, the variable is included in a href (tacked onto the end of `http://#{request.host_with_port}/#{@region.name.downcase}?`). 

It works at first. The problem is that when you click the link and the search loads, the link on the newly-loaded page no longer has the string on it... because that string is generated when you click search. So the url becomes `http://localhost:3000/portland?undefined`

Maybe I could add, "if search_link is undefined, then take window.location.href"
# **EDIT** I did that, and now everything seems to work!

Here's a screenshot, just for fun.
![selection_023](https://cloud.githubusercontent.com/assets/632682/22852136/c9c6782a-efea-11e6-8120-e089256001f4.png)

This took a lot of work for me to figure out. And the code probably sucks anyway. Let me know.

pending review: https://github.com/scottwainstock/pbm/pull/578/commits/03cba9575e7e54278365fb63fc997b761d98918c

**Comment by RyanTG** [comment]
The main thing that makes me skeptical of this code is that the permalink looks like: 
`http://localhost:3000/portland?utf8=%E2%9C%93&by_location_id=2360&by_location_name=`

rather than:
`http://localhost:3000/portland?by_location_id=2360`

So maybe it's pulling the url from the wrong place. But that's the only way I could figure it out.

**Comment by RyanTG** [comment]
For me to do: even when the div has a fixed positiion, it still scrolls (I guess because the div it's inside is not fixed. So, try putting it somewhere else. I put it in the #form div, and that didn't work. It ended up loading even before you loaded a location.

**Comment by RyanTG** [comment]
Completed that last task https://github.com/scottwainstock/pbm/issues/581#issuecomment-279150111

**Comment by RyanTG** [comment]
I think the potentially confusing thing to users who use this link is that if they load a search, and then they conduct some other searches, the url in the address bar will still show the original url that they loaded. But seeing a url with a bunch of stuff in it might lead them to assume that the url is for the current page. So they may copy it, thinking it's the current search, when in fact the url is for a prior search.

But that might not crop up too often...

**Comment by scottwainstock** [comment]
This should make the "by n machines" filter work on load:
https://github.com/scottwainstock/pbm/commit/1e357974ace5c80f9163b28d3b927ccbad5bb1d9

This is some of the worst code on the entire site (all my fault).

**Comment by RyanTG** [comment]
Cool!!!

I'm going to do a little more styling for mobile.

**Comment by RyanTG** [comment]
Nevermind - I'm fine with how it looks on mobile. It's within the search box. I could move it outside of it. But I dunno - it seems ok as is.

![search_link](https://cloud.githubusercontent.com/assets/632682/22948460/78419fd6-f2b3-11e6-9dfa-83275dc05d6c.PNG)
