### ISSUE TITLE
What region is this location in?

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#588]
https://pinballmap.com/admin/location/3545
Arcade Odyssey. We have two locations with the same name/address. But only one of them is showing up in the region it should be in (south florida). I manually looked in EVERY other region, and couldn't find it.

**Comment by RyanTG** [comment]
Man, I have zero patience. Should be working, but instead I installed heroku and postgres at work just so I could run:

 select r.name as region_name, l.id as location_id, l.name as location_name, m.name as machine_name, m.id as machine_id from location_machine_xrefs x inner join locations l on (l.id = x.location_id) inner join machines m on (m.id = x.machine_id) inner join regions r on (l.region_id = r.id) where l.id IN (3545);
 region_name | location_id | location_name | machine_name | machine_id
-------------+-------------+---------------+--------------+------------
(0 rows)

I don't know what's up with this location. It's not assigned to a region. Deleting it!

**Comment by RyanTG** [comment]
Strangely, there are machines assigned to the location. If I query one of those machines, the location isn't listed.

I'm not going to delete this for now. Seems to not be harming anything to keep it. And it might be worth it to investigate this later.

**Comment by RyanTG** [comment]
@scottwainstock Can you solve this mystery for me? The location listed above shows up in admin, yet it's not on any maps. When I queried it, the location wasn't found.

Is this some sort of remnant from back when we could disable locations?

**Comment by scottwainstock** [comment]
```
glowing-dusk-5085::COBALT=> select coalesce(r.name, l.region_id::text) as region_name, l.name as location_name, count(*) as num_machines from locations l left outer join regions r on r.id = l.region_id where l.name='Arcade Odyssey' group by 1,2;
-[ RECORD 1 ]-+---------------
region_name   | southflorida
location_name | Arcade Odyssey
num_machines  | 1
-[ RECORD 2 ]-+---------------
region_name   | 37
location_name | Arcade Odyssey
num_machines  | 1
```

Looks like that second location is associated with a region (37) that no longer exists. The other location is in south florida.

**Comment by RyanTG** [comment]
ah ok. Thanks. Maybe we should delete all locations that are associated with deleted regions. When I've deleted regions, I just assumed the locations went up in smoke, too.

I'll create an issue for that.
