### ISSUE TITLE
Staging bugs

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#590]
On staging right now:

When I try to [JOIN](https://pinballmapstaging.herokuapp.com/users/join), I get an error in the email field: "Please lengthen this text to 255 characters or more (you are currently using 20 characters)"

**Comment by RyanTG** [comment]
This should be easy to solve.

<input aria-required="true" autofocus="autofocus" class="string email required" id="user_email" maxlength="255" minlength="255" name="user[email]" required="required" size="255" type="email" value="">

I don't know where that minlength value is coming from, but it needs to be removed (or specified as "4" or something). Those variables are not in the 
https://github.com/scottwainstock/pbm/blob/auth_required/app/views/devise/registrations/new.html.erb#L22

But I'm sure they can be specified in that file: :minlength => '4'

It's annoying that you can't SEARCH branches other than master on github.

**Comment by RyanTG** [comment]
NOT A BUG: https://pinballmapstaging.herokuapp.com/users/password/new
Might be nice to allow people to enter their username OR their email address here. Right now it only accepts username. People might forget their username... I'll think about this, and perhaps make a new issue. Not trying to clutter up this thread.

**Comment by scottwainstock** [comment]
I'm pretty sure people can login to the WEBSITE using either their email or
username.

**Comment by RyanTG** [comment]
Yeah, they can. I just did it.

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/pull/591
Closing. If I find more bugs, I'll open more issues.
