### ISSUE TITLE
Let admins add machines through the admin interface

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#604]
This is requested all the time. This issue can be considered a sibling to https://github.com/scottwainstock/pbm/issues/481

Mandatory: 
When machines are added, they must hit the RSS.

I don't love this feature idea, because it means that admins can add locations without looking at the map to make sure the pin is in the right place. But some admins DO NOT enter locations because this process is too annoying to them. So, if we can automate things a bit more, then great, whatever.
If this feature CAN'T be done, fine.

**Comment by scottwainstock** [comment]
@RyanTG Added to create location..

https://github.com/scottwainstock/pbm/commit/ee974da303c4f1282803fb97699f49153a9927d5

It shows up in the feed.

**Comment by RyanTG** [comment]
I can't get any machines to show up in the list. Searching doesn't do anything. Am I doing something wrong?

**Comment by scottwainstock** [comment]
I dunno... this is working for me in live right now. What browser are you
using? I'm using Chrome Version 56.0.2924.87 (64-bit).

**Comment by RyanTG** [comment]
Oh, I switched users and it works. It works with my portland admin account. But not with my global one (the account where I can add a location to any region).

**Comment by RyanTG** [comment]
But I should note that this feature is mostly for the other admins. So if it doesn't work for my global account, then so be it.

**Comment by RyanTG** [comment]
Really cool. Thanks! This had been requested dozens of times over the years. And some admins were adding locations but not machines because they couldn't be burdened with loading the map. I'm sure you know my opinion of that. Regardless, this will make many admins happy.

**Comment by scottwainstock** [comment]
Hey no problem... turns out it was sort of easy to do.

**Comment by RyanTG** [comment]
Reopening because I don't think this is currently working. I've tried on a couple different admin accounts, and I've heard from one other admin that it's not.

I'll also check via different browsers.
