### ISSUE TITLE
lat/lon is currently REQUIRED when adding a new location

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#607]
I tried to add a location, but it's requiring the lat/lon fields, rather than letting them autopopulate.

**Comment by RyanTG** [comment]
I haven't been able to figure this out. But I made it a priority issue.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/49c2acb2ca1278b9f064af1a54b38ee63090ff37

**Comment by RyanTG** [comment]
Seems good. I just added a location and it went smoothly. Thanks!

If the lat/lon fails to automatically generate, will users see an error?
