### ISSUE TITLE
if admin logs in, provide /admin link in menu

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#612]
Admins are complaining that they need to type in /admin. Not sure if we have logic to recognize if a user is an admin - but if so, add a link in header or menu.

**Comment by scottwainstock** [comment]
Jeez, ok.

**Comment by RyanTG** [comment]
I can understand it. Previously when you logged in it sent you to /admin. But now it sends you to the last page you visited. And if you arrived to the​ site at /admin while logged out, it redirects you to /users/login, and once you login it does not send you back to /admin. It's like it doesn't recognize that as your previous page.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/8c0f81f75b1d0eb2c626c2c33f92b2b510c2f70b

@RyanTG This needs styling, so I didn't push it to the live site just yet.

**Comment by RyanTG** [comment]
K.

**Comment by RyanTG** [comment]
Closing. Thanks!
