### ISSUE TITLE
Add zone filter to GET /api/v1/region/:region/machine_score_xrefs.json 

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#621]
Do this for Will, and then let him know it's done.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/facdfccc87c73fa47a8cd587259d54fc506e5286

**Comment by RyanTG** [comment]
Is this closable?

**Comment by scottwainstock** [comment]
I was waiting to hear back from Will before I close it... it probably is.
But I'll take care of it.

**Comment by RyanTG** [comment]
Checking on this again. Did you hear back from Will?

**Comment by scottwainstock** [comment]
Have not. Close away.
