### ISSUE TITLE
Events - Some aren't displaying

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#624]
https://pinballmap.com/portland/events

The "Leagues" section is blank. That "League" text shouldn't be visible if there's no event listed under it. But, there should be an event under it! For example, this event: https://pinballmap.com/admin/event/375/edit

I haven't explored why that event is not showing up. Because there are no start/end dates?

**Comment by RyanTG** [comment]
The Android app is displaying the hidden event. Just noting that.

**Comment by RyanTG** [comment]
iOS app is also not showing events. For example: Wisconsin is showing zero events, according to Stephen.
The website is showing some of them, and Android is showing all of them.

I'll make an iOS issue.

**Comment by RyanTG** [comment]
Some website testing reveals: Events with no date (say, for leagues) aren't showing up.

**Comment by scottwainstock** [comment]
@RyanTG Just started looking at this... I'm seeing events here: https://pinballmap.com/portland/events ... under leagues.

Did you change something?

**Comment by scottwainstock** [comment]
@RyanTG OK, I'm seeing that you added dates. Can you give me a heads up on that kind of stuff? It saves me some time.

**Comment by scottwainstock** [comment]
@RyanTG I think I have the code to handle this, I'm going to drop the start/end date from that Portland league entry after I deploy.

**Comment by RyanTG** [comment]
Sorry - yeah, I just added a date to that one league event. I thought I stated that in the issue here, but I realized that I only stated it in an email to Stephen.

**Comment by scottwainstock** [comment]
@RyanTG Ain't no thing.

https://github.com/scottwainstock/pbm/commit/123afa1a868e9b64239b52b8ceaf14bf7ba4bed6

**Comment by RyanTG** [comment]
Sweet. Yeah that seems to fix the website!

iOS still seems to have an issue, though. https://pinballmap.com/wisconsin/events has lots of events with no dates, and they aren't showing up when I just checked the iOS app.
