### ISSUE TITLE
No https in non-production mode

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#628]
Make it http unless we are in production mode.

**Comment by scottwainstock** [comment]
FYI @RyanTG , I'll try to crank this out real quick... just didn't want to duplicate efforts.

**Comment by scottwainstock** [comment]
Use routes.

**Comment by scottwainstock** [comment]
This should do it: https://github.com/scottwainstock/pbm/commit/56a9b88d512438b02fd976949e39bc59a8719d18

**Comment by RyanTG** [comment]
Thank you for cleaning my mess!
