### ISSUE TITLE
Routes on RSS feed entries are not working

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#629]
Example: https://pinballmap.com/portland/location_machine_xrefs.rss

````
    <item>
      <title>Spider-Man was added to Putter's Bar &amp; Grill</title>
      <link>/portland/?by_location_id=7784</link>
      <description>Added on Thu, 16 Mar 2017 21:24:42 +0000</description>
      <guid>39232</guid>
      <pubDate>Thu, 16 Mar 2017 21:24:42 +0000</pubDate>
    </item>
````

**Comment by RyanTG** [comment]
It looks like `region_homepage_path(@region.name.downcase)` is just producing `/portland` rather than `https://pinballmap.com/portland/

**Comment by scottwainstock** [comment]
I'll get that fixed tonight.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/c9344a2d740217702c9847ea1bf7135ae7672f78
