### ISSUE TITLE
Deleted high scores are still displaying in Profile

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#631]
Example: https://pinballmap.com/users/569/profile
This user accidentally entered the same score three times. 
I went to https://pinballmap.com/admin/machine_score_xref and deleted two of them. But the profile is still showing all three.

**Comment by scottwainstock** [comment]
The profile is driven by user_submissions, not machine_score_xrefs.

**Comment by RyanTG** [comment]
Ooh, gotcha. Makes sense.
