### ISSUE TITLE
Lock down write access to the API

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#636]
This Thursday/Friday/Weekend: lock down write access, so that app users HAVE to upgrade and log in.

Additionally:
If any regions have MOTDs that are still the standard "buy a shirt", let's change those.

So: IF motd is "Buy a Pinball Map t-shirt on our store! http://pinballmap.com/store" OR IF motd is blank, THEN change motd to "App users: update the app! Only logged in users can edit maps, so update and login!"

MOTD is the only way to tell users to upgrade, right? No server-side option, similar to toast messages like, "please confirm your account"?

**Comment by scottwainstock** [comment]
Try to send back "update your app" messages in error codes.

**Comment by scottwainstock** [comment]
This is going to take more work than I expected... but we'll be able to send back meaningful error message to API users.

**Comment by RyanTG** [comment]
If you agree, then I think we should proceed with this.

And if the MOTD is BLANK or if it's "Buy a Pinball Map t-shirt on our store! http://pinballmap.com/store" then let's replace that with:

"Don't forget to update the app! You can only edit the map with the latest version!"

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/1811803c079e5940744942fff5b3fc3f2efe3cb0
https://github.com/scottwainstock/pbm/commit/f1ea4437b9ac0d7873e3467f08fde0ffd0a26e4d

MOTDs updated.

**Comment by RyanTG** [comment]
Closing!
