### ISSUE TITLE
Sort list of regions on home page... by name, not full name

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#642]
In the region list dropdown, the region list is sorted by name, even though full name is displayed. This is great, and this is what I want for the list of regions on the home page. I'm having trouble finding the commit that added this sort behavior for the dropdown list. 

Simple test: Is "West Michigan" in W or in M?

**Comment by bpoore** [comment]
I made a PR for this issue- I think it addressed what you were looking to change. If not, let me know and I'll keep poking around.

**Comment by RyanTG** [comment]
Thanks @bpoore! This does address it. But still, I want to think about whether this is the right thing to do. Both names and full names are inconsistently formatted. So I need to figure out which one is better to make consistent, and then we'll use that for the sorting method.

**Comment by bpoore** [comment]
Ahh, I see. The db dump I have doesn't explicitly have scenarios where any names aren't following the desired pattern. I don't know if it would break anything, but if I got a full db dump, I could do an UPDATE statement of names to catch ones that aren't in the correct format. There aren't that many regions.. it wouldn't be terribly much work. If we did that, hopefully in the future we'd remember to make up names in such a way that they follow the correct pattern.

**Comment by RyanTG** [comment]
I could manually check that pretty quickly (which I do below). 

I think the best solution is to use your update, and for me to update all the names to fit into a standard. 

Looking at the list, these are wrong:

centralpa --> penn-central
dc --> washington-dc

There are other inconsistencies, too. Like, some names are abbreviations or initials (la, dfw), and some have hyphens. If I had planned all of this out ahead of time, I would include hyphens, and have no (or minimal) initials. To contradict the beginning of this comment: it would be much simpler to edit the full names than to correct all of these inconsistencies (especially because changing the name of a region requires creating a new region and copying over data, and then deleting the old region - due to an issue with the iOS app. But changing the full name is simple).

**Comment by bpoore** [comment]
If changing the full name is simple and won't break things, that seems like the best way to go. Especially if it's not tied to anything else in the database. Doing the sorting based on the full-name and having the ability to update it at any time without major fallout definitely seems to make the most sense. I'll retract my PR.

**Comment by RyanTG** [comment]
Alright, I changed the full name of Central PA to Pennsylvania, Central. And that seems to resolve this issue. I'll close it.
