### ISSUE TITLE
RFE: Add option for location services when app is running

### ISSUE THREAD

**Issue by alberttwong** [scottwainstock/pbm#644]
I personally turn off location services for app that use it all the time.  problem when I do that with pinball map, when I use nearby, it doesn't work even when I'm running the app.   I either get always or never.

**Comment by RyanTG** [comment]
That option is necessary for the Apple watch app. Note that we collect zero information about you and your location. The app is not actually collecting any info when you're not using it.

**Comment by RyanTG** [comment]
And you're referring to the ios app, right? If so, this issue should be on that project.

Ah, I just used the zillow app and saw that they have a "when app is running" option in the location settings.

**Comment by alberttwong** [comment]
IOS app...    and I'll open issue over there.
