### ISSUE TITLE
Consider: Search that acts more like a search, and not only like sort

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#647]
Right now, if you type in a location name, you HAVE to use the autocomplete and select a location or a machine. What if, if you don't choose an autocomplete item but you still have a string in the input field, then the results show items "like" that string.

For example, you type "chuck" and press enter. Normally, there'd be a message saying nothing is found in the region. But instead, the results show anything with chuck in the name (like chuck e cheese).

**Comment by RyanTG** [comment]
Another totally opposite option would be to do what the https://dashboard.heroku.com does: If you type something in the search box, and there's no result, then "submit" is disabled, and the dropdown says, "can't find any matching results"

**Comment by scottwainstock** [comment]
Location name search is now fuzzy and case insensitive. If you want the other thing... can you make a new ticket for it?

https://github.com/scottwainstock/pbm/commit/c365dbf174c1634e4a22bc715ee093ba19f12b79

**Comment by RyanTG** [comment]
That is VERY cool. I definitely prefer this over the other option. I tested a few and it works great. Sweet addition.
