### ISSUE TITLE
If Metadata is updated, change the "last updated by"

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#650]
Right now, if you edit location metadata, the location's "last updated by" data doesn't change. But I think those updates are worthy of triggering an update to "last updated by."

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/a07461f5ab31702445032337dec654aec5de7206

**Comment by RyanTG** [comment]
Thanks!
