### ISSUE TITLE
Random location link

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#652]
Might be cool to have a link that brings up a random location. I'm picturing it here:

**Welcome to the Los Angeles Pinball Map!
To begin: Search! Or click here for a random location!**

And when clicked it does something like https://pinballmap.com/la?utf8=%E2%9C%93&by_location_id=RANDOM&by_location_name=

Obviously the random location has to be within that region.

(I'm trying to think of ways to "help people get started" when they first hit the region home page...)

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/3479371e28652de64f6fe86cee4769274b9f08f9

**Comment by RyanTG** [comment]
On mobile, there's no link: https://github.com/scottwainstock/pbm/blob/3479371e28652de64f6fe86cee4769274b9f08f9/app/views/pages/_intro.html.haml#L8

I could probably make that if else statement a little more efficient...

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/6fb0f9a17d01cf1bdf7197d40dfd3fb105b9c4b5

**Comment by RyanTG** [comment]
Sick! Awesome.
