### ISSUE TITLE
Profile - reverse the sort order of locations edited

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#656]
Currently, the most recently edited location is at the bottom of the list. Switch the order!

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/31b92ec9a74aa7183bff4d258378a017d27b2364

**Comment by RyanTG** [comment]
This didn't work. If a user has edited more than 1 location, their profile page is completely blank. Example: https://pinballmap.com/users/472/profile

For users that have edited 1 or 0 locations, their profile page displays.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/0ebde41bd9ca7d23db5f5de5af670b68bf14cd2b

...should fix the bug.

**Comment by RyanTG** [comment]
And so it does. For that I thank you.
