### ISSUE TITLE
Investigating memory exceeded issues

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#666]
[This](http://stackoverflow.com/questions/23858694/rails-4-error-r14-on-heroku-memory-quota-exceeded) might be the easiest thing to try: 

* Upgrade Ruby from 2.1.7 to [2.3.4](https://devcenter.heroku.com/articles/ruby-support#ruby-versions). Because 2.1.7 has had reported problems with memory. 
* And upgrade Rails from 4.1 to 4.2.

**Comment by scottwainstock** [comment]
@RyanTG I did both upgrades and pushed the code to staging. It's a big change, so we should poke around on the site there. Tests all pass... site SEEMS ok.

**Comment by RyanTG** [comment]
Cool! Yeah seems big. What's the main risk - gems not working?

**Comment by scottwainstock** [comment]
Yeah, things just quietly not working... stuff breaking that wasn't tested. I think the risk is pretty low, but I didn't want to go directly to the live site. Probably I'll do that early next week unless we notice something between now and then.

**Comment by RyanTG** [comment]
Potential issues:

- When leaving a machine comment, clicking "save" just once doesn't submit the comment. It only submits after I click it twice!
Console Error: application-0eb72ea….js:10255 GET http://pinballmapstaging.herokuapp.com/portland/location_machine_xrefs/upda…tion?id=18719&utf8=%E2%9C%93&id=18719&new_machine_condition_18719=comment. 500 (Internal Server Error)

- Not receiving an email about the machine comment.

**Comment by scottwainstock** [comment]
500 error:
```
2017-04-18T02:55:17.624148+00:00 app[web.1]:
2017-04-18T02:55:17.624163+00:00 app[web.1]: NoMethodError (undefined method `send_digest_comment_emails?' for #<Region:0x007f4e08962fa0>):
2017-04-18T02:55:17.624164+00:00 app[web.1]:   app/models/location_machine_xref.rb:51:in `update_condition'
2017-04-18T02:55:17.624165+00:00 app[web.1]:   app/controllers/location_machine_xrefs_controller.rb:67:in `update_machine_condition'
2017-04-18T02:55:17.624165+00:00 app[web.1]:
2017-04-18T02:55:17.624166+00:00 app[web.1]:
```

**Comment by scottwainstock** [comment]
@RyanTG Just needed to run migrations on the staging server, so that's cool.

Comments appear to work too. I'm guessing they were getting knocked down by the lack of migration before.

**Comment by scottwainstock** [comment]
@RyanTG Wudduh you think? Push it?

**Comment by RyanTG** [comment]
P-PUSH IT REAL GOOD DVVVRT D-DRVT DRVT DRVT DRVT DADADADADA

**Comment by scottwainstock** [comment]
Shit's live.

**Comment by RyanTG** [comment]
Heroku is showing zero memory exceeded errors since this was deployed. Cool!

**Comment by scottwainstock** [comment]
Yeah, let's see how it does over the weekend. If this continues to look
good, I'll scale back the number of reboots we perform. Sounds like people
are catching those reboots and seeing the site "hang" for ~30 seconds. So
that's not great.

**Comment by RyanTG** [comment]
Now heroku is showing errors in the past 24 hours (685).

**Comment by RyanTG** [comment]
I think we determined that the response times on the site are still a-ok, and that heroku is trying to scare us into upgrading stuff. I'll just close this for now.
