### ISSUE TITLE
After a score is added, clear the form

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#671]
When you add a score, there's no feedback saying the score was added. It looks like nothing happens, and the score is still in the input field. 

1. After adding a score, remove it from the input field.
2. Some sort of feedback. I guess a window dialog is easiest: "Thanks for adding that score!"

**Comment by RyanTG** [comment]
Not quite related, but this line should have a ; at the end: https://github.com/scottwainstock/pbm/blob/master/app/views/machine_score_xrefs/_add_high_score.html.haml#L19

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/pull/672/commits/5064c673c6958503384925571c0142aef0337f05

**Comment by scottwainstock** [comment]
@RyanTG I'm not seeing where they reset... can you send me a link to some code that shows this? Otherwise, no.. we're not explicitly resetting the form.

**Comment by RyanTG** [comment]
On other textboxes? No, I can't show you some code. That was _my_ question. Like, the machine comment box gets cleared out (well, the whole thing disappears), after you submit it.

Anyway, whatever. So I guess this commit adds something.
