### ISSUE TITLE
If super admin edits and then promotes a location, the location ends up in the super admin's home region

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#676]
**Important note:** This only occurs if the super admin EDITS the location before promoting it. Editing the location somehow reassigns the location to the super admin's home region.

Example (on staging), user TZR edits and then promotes a location that was submitted to Los Angeles. The location ends up in the Portland region.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/8d10dcc54b32f6ff2fcf119e6242d6564c5818d0

**Comment by RyanTG** [comment]
This still occurs. For example: This [Massachusetts](https://pinballmap.com/admin/suggested_location/20/edit) location. There was no address, so I added it and pressed save and the location was reassigned to los angeles. 

And if I edit and choose the correct region, the edit doesn't hold (it just reverts to my home region).

**Comment by RyanTG** [comment]
This might provide guidance: https://github.com/scottwainstock/pbm/commit/cf4027da519dfd2b1cd39c9cc0418a93792cf22e
from this issue https://github.com/scottwainstock/pbm/issues/433

**Comment by RyanTG** [comment]
I solved this! https://github.com/scottwainstock/pbm/pull/683/commits/855b4a93bbe960de4c9766255306e0489ae5b3a7
