### ISSUE TITLE
Remove Quotaguard

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#677]
25 per day is apparently not enough. And since we're not pulling in more donations, we shouldn't pay the $10/mo for a higher quota.

So: remove quotaguard.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/956d5abc639338e82f65ef1ec0c45a7d97f97636

**Comment by RyanTG** [comment]
Thanks. Sorry about going back and forth with this!
I really hope the problem we're seeing right now is with quotaguard. I have some doubt, because they're poorly designed chart does not make it clear that we've exceeded the quota in a 24 hour period. We'll see.
