### ISSUE TITLE
Do not create location if lat/lon isn't present

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#678]
Timeline of how things used to be:

1. Back in the day, admins could leave the lat/lon fields empty when creating or editing a location. If the fields were empty, the lat/lon would be generated. If the lat/lon failed to generate, then the location was not created/edited and there was an error message.
2. Something changed: when admins _edited_ a location and the lat/lon were empty, they couldn't press Save and they would see a "this is a required field" message. 
3. This commit https://github.com/scottwainstock/pbm/commit/f27b48a6aba050a3774deb14e6bf3befd803dd22 from a couple days ago removed that "this is a required field" constraint, **but it also removed the error message when a lat/lon failed to generate**. So, it went too far.

**Solution:**

GREEN text = let's show this; RED text = let's not show this.

![latlon](https://cloud.githubusercontent.com/assets/632682/25448487/7b8a6622-2a6d-11e7-8b35-a06300e89f01.jpg)

The green message should show up if the lat/lon fails to generate.

**Comment by scottwainstock** [comment]
Sorry, I'm getting kind of confused about what we're going for here. I'm going to revert my commit from above. That seems like it gets you what you want? But also it seemed like that commit got you something you wanted too... so now I'm not sure what you're losing by me reverting it.

**Comment by scottwainstock** [comment]
Seems like we WANT the "this is required" constraint, right?

**Comment by scottwainstock** [comment]
Oh wait, hang on... I think I get it now.

**Comment by RyanTG** [comment]
red text = do not want. green text = want.

**Comment by RyanTG** [comment]
I know you get it now. But I think this would have been a situation where talking on the phone would have helped. I had a lot to explain (context and such), and I tried to make it clear, but I know it's complicated.

**Comment by scottwainstock** [comment]
It's cool, your description makes sense... a big part of the problem is that I only have ~1 hour to look at this stuff when I look at this stuff, so I don't read as carefully as I could.

I think this does what you want: https://github.com/scottwainstock/pbm/commit/09af8e7946a183e7a2db0f30d6e86fd7e46b3937

lat/lon are required again... but the fields are listed as OPTIONAL when editing, so you can remove them and they'll get autofilled.

Not super clear why people would ever want to do that though. If you are editing and you put in a new address and stuff, it'd just auto-enter the new lat/lon, wouldn't it?

**Comment by RyanTG** [comment]
Based on the code you added two days ago, yes it would re-generate a new lat/lon. But prior to that, it would not (back in those days, I would regularly clear out the fields when I'm changing the address of a location, with the intention of letting it auto-regenerate).

This also covers for cases where the lat/lon isn't generated for a NEW location. Admins have a tendency to not notice that there's no lat/lon. Now they have to notice.
