### ISSUE TITLE
Check for required fields when promoting location

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#682]
Look at https://github.com/scottwainstock/pbm/commit/09af8e7946a183e7a2db0f30d6e86fd7e46b3937
all the "validates" stuff

For: https://github.com/scottwainstock/pbm/blob/09af8e7946a183e7a2db0f30d6e86fd7e46b3937/app/models/suggested_location.rb

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/pull/683/commits/b072c047677de6203bffe4df7373e7b1aa8834ef

I couldn't get it to display a message with validates_presence_of

I can work on adding some spec stuff next.

**Comment by RyanTG** [comment]
For tests, try `expect(SuggestedLocation.count).to eq(1)` or something. Still dunno why it broke, though.
Also, check to see if the validation occurs during promotion AND during editing.

**Comment by RyanTG** [comment]
The problem is that [the validation](https://github.com/scottwainstock/pbm/pull/683/commits/b072c047677de6203bffe4df7373e7b1aa8834ef) is occurring when the location is first submitted, rather than when the suggested location is edited. I haven't figured out how to specify that it only validates when editing. I don't see anything on location.rb to use as an example.

**Comment by RyanTG** [comment]
This is beyond me. I give up on this, so I'm passing it back to @scottwainstock. 

**Synopsis:**
Because the SuggestedLocation is _created_ when the user submits the form, [this validation](https://github.com/scottwainstock/pbm/pull/683/commits/b072c047677de6203bffe4df7373e7b1aa8834ef) occurs during that creation (resulting in SuggestionLocations failing to create if the validation doesn't pass). But instead, we want the validation to occur when the location is _promoted_ or edited by an admin prior to promotion - not when it's created,

**Comment by RyanTG** [comment]
Just for clarity: you correctly did everything I asked for with the lat/lon stuff. The problem was that I failed to account for something (explained here https://github.com/scottwainstock/pbm/issues/684). In other words, my instructions were faulty. And then I corrected the problem.

**Comment by scottwainstock** [comment]
@RyanTG Can you check staging for this? I just pushed some code there that I think addresses this. The one issue I haven't been able to sort out is notification that you failed validation when you promote a SL to an L. It just redirects you to the SL "show" screen. Not ideal, but close.

**Comment by RyanTG** [comment]
Yeah I'll give it a looksee tomorrow. Thanks for working on this!

**Comment by RyanTG** [comment]
The validation when editing an SL works great!

Perhaps for the promotion, we could redirect to the "show" screen (as it's doing now), but also supply a generic message: "Some fields did not validate. Please edit the location and correct them."

**Comment by scottwainstock** [comment]
Right, figuring out how to do that last part has been tricky.

**Comment by scottwainstock** [comment]
@RyanTG You want me to push what I have for now?

**Comment by RyanTG** [comment]
Go for it, brah.

**Comment by scottwainstock** [comment]
K,live. I'll leave this open to add the "here is why you just got redirected to the SHOW action" logic.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/ae18ec00683cc0e2c3c64816ecdf10687e660c5d

**Comment by RyanTG** [comment]
Cool! Works great.
