### ISSUE TITLE
Locations suggested through the app - the machines don't get auto-added during promotion

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#685]
With location submissions coming through iOS and Android, the machines in the submission aren't formatted in a way that allows them to be auto-added to the location during Promotion.

_**iOS** machines in a location submission look like:_
Machines: Pabst Can Crusher-Stern,Elvira and the Party Monsters-Bally,Dr. Dude-Bally,The Getaway: High Speed II-Williams,

_Through **Android**, they look like:_ 
Machines: Breakshot [Capcom - 1996], 

_Through the **website**, they look like:_
Machines: Lord of the Rings (Stern, 2003), Hook (Data East, 1992),

**Comment by scottwainstock** [comment]
Ugly hack: https://github.com/scottwainstock/pbm/commit/e1c5d849cb2cbc4b2c80f76a686a9222e0252294

**Comment by RyanTG** [comment]
This uggo hack is just for Android? I just want to be sure what I'm looking for in my review.

**Comment by scottwainstock** [comment]
Just for Android, yes. iOS will need a code change in iOS.
