### ISSUE TITLE
Daily Digests - Still receiving individual emails for removals

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#696]
When daily digest is enabled, the real time emails for _machine removals_ still come in (the digest emails arrive, as well). 

It seems that the individual machine comments don't come through, though (which is good).

**Comment by RyanTG** [comment]
Closing. This seems to only affect the Super Admin (aka Portland). So, not worth addressing.

**Comment by RyanTG** [comment]
Reopening because this does occur for all regions, but only for machine removals. deleting this comment in a moment.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/5b48c71533cb1f2061d9a3fcf43a81b231d961d5
