### ISSUE TITLE
Daily Digests - Empty Daily Comment emails are still sent

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#697]
The emails arrive regardless of whether that region actually had comments that day.

Note, this is only for Comment emails, not removals.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/97fd5a7407139137dcf5881db6d37e75d7dde7e0

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/5b48c71533cb1f2061d9a3fcf43a81b231d961d5

**Comment by RyanTG** [comment]
Awesome, thanks! This is fixed.

I'll wait to verify the other issue when someone removes a machine. 

I'll send an email to the admins saying that if they tried it before and were having problems, then all is now well.
