### ISSUE TITLE
Daily Digests - include user info in machine removals email

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#698]
On the comments email, usernames and emails are included for each submission. But that info is missing on the removals email. 

I couldn't figure it out myself. I see that there's #{submissions} in the def. But I'm not sure where the definitions for those are!

**Comment by RyanTG** [comment]
Woops, I closed the wrong issue.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/235c91f10f80bba6b9e04157ccc3d411508b4b72

**Comment by RyanTG** [comment]
Today's digest didn't include the user info. But I'm going to wait another day before I come to a conclusion here.

**Comment by RyanTG** [comment]
Seems good. User emails aren't included, but that's probably alright.
