### ISSUE TITLE
Weekly digests aren't being sent

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#704]

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/90fc7af6a41e1b708de85d3a62a29ab2c3298366

**Comment by scottwainstock** [comment]
I moved all the dreamhost cron jobs over to heroku. The commit above is kind of a hack to piggyback on the daily scheduler system they have.

Affected jobs are:
notify_admins
notify_super_admins
notify_operators
send_daily_digest_machine_condition_email
send_daily_digest_machine_removal_email

**Comment by scottwainstock** [comment]
The fact that we've been getting daily notifications and NOT the weekly ones is heartening to me. Let's see what happens Friday I guess.

**Comment by RyanTG** [comment]
Were the daily notifications already on heroku?

**Comment by scottwainstock** [comment]
N. The only thing on Heroku was the event refresh.

**Comment by RyanTG** [comment]
Oh ok. But the daily notifications were working before you moved things to heroku. 
Anyway, Friday is the day.

**Comment by RyanTG** [comment]
Friday update: Weekly Digests were not sent.

I also noticed on the heroku dashboard that the dynos aren't being regularly restarted.

**Comment by RyanTG** [comment]
Hold the phone - I received ONE weekly digest! For Toronto. Usually I receive 9 of them, though. So, it kind of worked!

**Comment by scottwainstock** [comment]
Super admin task appears to work.

Regular admin one is failing with:
```
ArgumentError: An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address.
/app/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/check_delivery_params.rb:10:in `check_delivery_params'
/app/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:99:in `deliver!'
/app/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:253:in `deliver!'
/app/vendor/bundle/ruby/2.3.0/gems/pony-1.11/lib/pony.rb:176:in `deliver'
/app/vendor/bundle/ruby/2.3.0/gems/pony-1.11/lib/pony.rb:166:in `mail'
/app/lib/tasks/notify_admins.rake:14:in `block (2 levels) in <top (required)>'
```

**Comment by scottwainstock** [comment]
It looks like maybe we have regions setup with no admins for them? I'm going to add some checks in the code for this.

**Comment by RyanTG** [comment]
Just California Central valley. I just made that and merged Bakersfield into it, and am going to make our CA Central valley an admin there. But I'm waiting for him to make a second account... We can makea temp one. I can do it, but not right now.

On June 29, 2017 9:01:24 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>It looks like maybe we have regions setup with no admins for them? I'm
>going to add some checks in the code for this.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm/issues/704#issuecomment-312169132

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by scottwainstock** [comment]
It's cool, my code will make it a moot point. But I think that was the root cause here. The region emailer looped through regions... found no admins for them, tried to send an email to no one, and that blew things up. I think I'm about to deploy a fix. I'm going to run the "send weekly update" process to test it though... so, people will get another one tomorrow if this one works out.

**Comment by scottwainstock** [comment]
OK, looks like it works now.

**Comment by RyanTG** [comment]
Damn, I fucked up. I should have put that together!

Thank you.

On June 29, 2017 9:09:55 PM PDT, Scott Wainstock <notifications@github.com> wrote:
>OK, looks like it works now.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scottwainstock/pbm/issues/704#issuecomment-312170131

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
