### ISSUE TITLE
Password reset form: username is case sensitive; can't enter email address

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#706]
The form on this page: https://pinballmap.com/users/password/new
is case sensitive. I think it should not be case sensitive (just like the login page isn't case sensitive).

ALSO: it would be great to allow people to reset their password using their email address, as well.

**Comment by scottwainstock** [comment]
This should be case insensitive and allow username OR email resets.

https://github.com/scottwainstock/pbm/commit/e3df91597b67a9aab75d053aa89df4c8008f36fa

**Comment by RyanTG** [comment]
Cool! Thanks. Works great.
