### ISSUE TITLE
Global MOTD: donation

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#707]
IF: the current MOTD is either blank or "Don't forget to update the app! You can only edit the map with the latest version!"

THEN: update the MOTD to: "To help keep Pinball Map running, consider a donation! https://pinballmap.com/donate"

**Comment by scottwainstock** [comment]
Updated database and added this code: https://github.com/scottwainstock/pbm/commit/69782c4dab3d16e57cb028aab7ad4e066d302417
