### ISSUE TITLE
promo flier page

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#709]
Assigning myself.

Create a region page called /flier that contains four quarter page fliers that can be printed out, cut into four, and then dropped off at places. Prepopulated with region name.

TODO:
- figure out the correct dimensions (try 670x900 = 7x9.5)
- finalize the style
- What about including a QR code?
- create print media query that hides the header:
````@media print {
    .page_home, .flier_desc {
        display: none;
    }
    .divivivivi {
        width: 50%;
    }
````

Current content:
`%p.flier_desc Print out this page, cut it into four, and then spread the word! THANKS!`
````
Find pinball machines to play on the Portland Pinball Map!

https://pinballmap.com/portland

Download the free app!
ios app store logo google play store logo

Help keep the map up to date!

Pinball Map Logo
````

**Comment by RyanTG** [comment]
@scottwainstock What do think about including a QR code on the fliers? There's a gem that could generate  a code based on the path: https://richonrails.com/articles/generating-qr-codes-in-your-ruby-on-rails-application

**Comment by scottwainstock** [comment]
I like it a lot.

**Comment by RyanTG** [comment]
Looks like this right now. And printing at 100% fills a page pretty well. 
![screenshot_20170629_002408](https://user-images.githubusercontent.com/632682/27676078-6fa5800a-5c61-11e7-9cfb-657427a242fa.png)

**Comment by scottwainstock** [comment]
Pretty sweet!

**Comment by RyanTG** [comment]
Let's just release this without the QR code for now. I sought some feedback, and apparently no one uses QR codes.

But! I'm going to try some textual edits tonight. I'll remove the PR until then.

**Comment by RyanTG** [comment]
I remember trying to add something like: 
````
We are tracking #{@location_count} locations and #{@lmx_count} machines.
````
And the counts did not render. I'm not sure what I'm missing. I'm not seeing any special code in https://github.com/scottwainstock/pbm/blob/master/app/views/pages/_intro.html.haml that would make the counts work.

**Comment by RyanTG** [comment]
Nevermind. I could add this to the controller: https://github.com/scottwainstock/pbm/blob/ec111874e71687b1952ed94d96b225e2289c99fe/app/controllers/pages_controller.rb#L6

**Comment by RyanTG** [comment]
@scottwainstock Do you know how to display the # of machines across ALL regions?

Like `@lmx_count = @region.machines_count` but for all regions?

**Comment by scottwainstock** [comment]
@RyanTG LocationMachineXref.all.count

**Comment by RyanTG** [comment]
PR https://github.com/scottwainstock/pbm/pull/715

**Comment by scottwainstock** [comment]
Looks good.
