### ISSUE TITLE
Suggest machine searches when machine name search comes up empty

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#717]
Steps:
- Lookup by machine
- type in "whatever" (or a machine that isn't present in that region. aka, anything that isn't autocompleted)
- Press "Search"

Results: It loads ALL (or, more accurately, it loads whatever is in the dropdown select list).

Instead, it should act the same as the lookup by location - it should give the "not found" message.

**Comment by RyanTG** [comment]
And, an interesting stretch goal:

"No Wizard of Oz found, but other similar machines are: ________ here" 
some formula weighting company + year to define similar

But, for that to work we'd need to a way to identify that "whatever" shouldn't match with anything, while "wizard of oz" should.

**Comment by scottwainstock** [comment]
Here's the bug fix. I'll leave this open (and update the description) to capture the stretch goal. It's non-trivial.

https://github.com/scottwainstock/pbm/commit/62886226f7ecd0cadcd021b45c5a295d2acabe6b

**Comment by RyanTG** [comment]
Thanks. Yeah, definitely seems non-trivial. The idea came from a coworker. It's interesting to watch people use it who are unfamiliar with the site and are very used to swiping/typing/clicking VERY quickly. So I guess this idea would fit into the general "make things easier for new people" umbrella.
