### ISSUE TITLE
Suggested location machine auto-add not using "global" machine list

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#718]
Kind of looks like it's limiting the list of machines it comes to when auto-promoting to ONLY be the machines in the region rather than every machine in the database.

**Comment by RyanTG** [comment]
Can't believe I didn't notice this! But I can verify it now. I just promoting a location in a region with only a couple machines, and the machine - despite being properly formatted - was not auto-added.

**Comment by scottwainstock** [comment]
Which machine? I can't reliably reproduce this.

**Comment by RyanTG** [comment]
Machines: Star Trek (Pro) (Stern, 2013), 

(entered from 192.159.8.109 via Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

**Comment by scottwainstock** [comment]
Machines with extra ()s in them were the problem.

https://github.com/scottwainstock/pbm/commit/8fddc211f22de8e857a30edc973452a76a9b3521

**Comment by RyanTG** [comment]
I just promoted a location that had Aerosmith (Pro) (Stern, 2017) and it worked! Closing.
