### ISSUE TITLE
For location searches, allow the textbox to take priority over the dropdown box

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#719]
Currently when doing a location search:

- If the dropdown list is anything other than ALL, then that value will take priority over any value in the textbox. For example, if "Mark's Pub" is selected in the dropdown (from a prior search), and you type "cafe" in the textbox and then press enter (without choosing any of the autocomplete options), the search results will be for Mark's Pub. This made sense prior to https://github.com/scottwainstock/pbm/issues/647, because you could _only_ complete a search based on values in the dropdown select.

But now:

- But now that you can type in "cafe" and still get results without choosing an autocomplete option, then the contents of the textbox should take priority over the select.

Let me know if: this doesn't make sense; or if I'm missing something and you think it's a bad idea.

**Comment by scottwainstock** [comment]
I "feel" you and I will try to make this change... but the behavior I'm seeing is that if you have something in the dropdown selected AND you enter a search string -- it'll use both of those items as filters in your search. I'll change it to have it ignore the dropdown if you have a text search.

```
Started GET "/portland/locations?utf8=%E2%9C%93&by_location_id=2360&by_location_name=cafe" for ::1 at 2017-07-21 21:53:00 -0700
Processing by LocationsController#index as */*
  Parameters: {"utf8"=>"✓", "by_location_id"=>"2360", "by_location_name"=>"cafe", "region"=>"portland"}
  Region Load (0.2ms)  SELECT  "regions".* FROM "regions" WHERE "regions"."name" = $1 LIMIT 1  [["name", "portland"]]
  CACHE (0.0ms)  SELECT  "regions".* FROM "regions" WHERE "regions"."name" = $1 LIMIT 1  [["name", "portland"]]
  Location Load (0.3ms)  SELECT "locations".* FROM "locations" WHERE (lower(name) ilike '%cafe%') AND (id in (2360)) AND "locations"."region_id" = $1  ORDER BY locations.name  [["region_id", 1]]
  Rendered locations/_locations.html.haml (0.3ms)
Completed 200 OK in 6ms (Views: 1.9ms | ActiveRecord: 0.5ms)
```

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/0df29035ce15b2b2e421550270f7acb2414335f3

**Comment by RyanTG** [comment]
Seems legit.
