### ISSUE TITLE
When you click on a map pin, jump to that location in results

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#722]
Steps:

- Do a search that results in multiple locations (such as search by type "Pizza Parlor" or search ALL).
- All of the results are listed on the left, and all the pins are dropped on the map.
- If you click on a result on the left, the map pin displays the location info. Great!
- BUT it doesn't work the other way around: if you click on a map pin, the results on the left don't jump to that location. So if you click on a map pin that for "John's Cafe" and you want to see the full location details (and add/remove machines at it), you then have to scroll down to J in the results on the left. 

Instead, it would be cool if the results auto-scrolled to whichever map pin you clicked on.

Doth that make sense?

**Comment by bpoore** [comment]
Hey @RyanTG, 

I took a stab at this one. Open to suggestions with regard to where to place the scrolled results. I wasn't sure the best approach with regard to getting the selected location to be right under the form since the form is sitting on top of the area the locations scroll through (my CSS isn't fantastic). What I ended up with doing for now was to place the location in the middle of the screen.

**Comment by RyanTG** [comment]
Oh, yeah I can see how that could be problematic. I'll check it out and get back to you. Your solution sounds good, though!

**Comment by RyanTG** [comment]
I think it's works well enough as it is. The middle works well. When locations are at the bottom or top of the list, then those can't jump to the middle - but that's just how it is.

**_Important:_** it should be completely disabled on mobile. I've done [crap like this ](https://github.com/scottwainstock/pbm/blob/master/app/assets/javascripts/application.js.erb#L365)to detect mobile in js, but I'm not sure if that's the best.

**Comment by bpoore** [comment]
Cool. I'll include that and make a PR then. I'm not certain what best practices are, but if that's working, it seems ok. It's probably possible to create a variable like isMobile. I might look into that down the road.

**Comment by RyanTG** [comment]
Closing!

**Comment by RyanTG** [comment]
Reopening! This isn't working in our mapbox gl setup. I think Scott intentionally removed it because it didn't work when we transitioned over.

Is this the only feature we lost when we moved to mapbox gl @scottwainstock ?

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/2b269c5589a508b42bcf5aeb9d8567a25bfc23b1

**Comment by RyanTG** [comment]
This works, BUT it also has an unintended behavior: if the location details are expanded, and you click the map marker, then the location details contract and turn into the location overview. And if the location details are contracted, then clicking on it expands them. Basically, clicking the map marker toggles it.

Are you seeing that (and does that make sense?)? At first I thought this behavior was kind of cool! I mean, there's no other way to retract the location details like that. But in the end, I'm not sure if we should be seeing this behavior.

**Comment by scottwainstock** [comment]
@RyanTG This was intentional, yes. I call a js method that toggles the state of the location div. If you want me to remove it, I can pretty easily do that.

**Comment by RyanTG** [comment]
Ok cool. Let's keep it for now.
