### ISSUE TITLE
Auto-deletion of empty locations isn't working

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#723]
As reported by a Chicago admin. I've verified that they have auto-delete checked, and that their list of empty locations has had the same locations on it for a couple of weeks.

**Comment by scottwainstock** [comment]
Looks like this is another dreamhost cron that quietly stopped working.... it's running daily on heroku now.

**Comment by RyanTG** [comment]
Daily? I thought this was running weekly before?

**Comment by scottwainstock** [comment]
Oh OK... well I can change that.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/977cf8b59243422c5f945b18804777d3e0bc75e0
