### ISSUE TITLE
Include date on Suggested Locations

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#730]
I would luv to see the date of location submissions. 

It could either be displayed when you click the (i) of a suggested location, or could be one of the fields on the full list at http://pinballmap.com/admin/suggested_location

**Comment by RyanTG** [comment]
Assigning self.

https://github.com/scottwainstock/pbm/blob/master/config/initializers/rails_admin.rb

Possibly:

field :updated_at, :datetime
or
field :created_at, :datetime

Also, interesting that this https://github.com/scottwainstock/pbm/blob/2cbbaa9cd5dc15f2ba880e87097dd4fa3b3b1eb2/config/initializers/rails_admin.rb#L553
uses :date instead of :datetime. But it still seems to work.

**Comment by RyanTG** [comment]
Unassigning myself for now. I couldn't solve it.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/687034d7cd02e34dd201c9139d8d78781c138dcd

**Comment by RyanTG** [comment]
Thanks!
