### ISSUE TITLE
Change text of t-shirt link

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#740]
Right now it says "We have a t-shirt for sale."
We should either remove that link entirely from each region, or just change the text to say "We have nothing for sale right now."

**Comment by scottwainstock** [comment]
@RyanTG Not sure where you are seeing this... I see the text you are describing in app/helpers/pages_helper.rb, but I'm not seeing it show up as any kind of t-shirt link anywhere.

**Comment by RyanTG** [comment]
Sorry. It's on the [About page](https://pinballmap.com/portland/about) of every region.

I just remembered: https://github.com/scottwainstock/pbm/issues/331
And I realize that I could have just run that command in the last comment.

**Comment by scottwainstock** [comment]
@RyanTG OK. That's from the region_links table. Do you want me to remove it?

**Comment by RyanTG** [comment]
Yes, please.

And I swear I edited the original post on this issue to be more descriptive. I guess I didn't click Save.

**Comment by scottwainstock** [comment]
```
glowing-dusk-5085::COBALT=> delete from region_link_xrefs where description = 'We have a t-shirt for sale.';
DELETE 55
glowing-dusk-5085::COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT
```
