### ISSUE TITLE
Pictures - make thumbnails larger

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#743]
These thumbnails are tough to style! They are so teensy right now. Perhaps they could be larger.

Would be nice to include a max height to the container they're in, then you could click to expand it and see all the pictures (just in case a place has 10 pictures - we wouldn't want them taking up too much space).

Another option is to have one larger picture (not huge, but enough that you can see what's in it), and that picture is basically the location's main photo. Then you can click it to see more. We would need a way to designate one picture as the main one, and then a way to display the rest of them.

Not sure if we'll need to ditch highslide for this.

Also, we could include text that says, "uploaded by user". And we could even track picture submissions in the user submission section (I'd make a separate issue for this).

height = x
if height > x, then overflow: hidden; & show "show more" link
When show_more is clicked, overflow: auto;

````
<html>
  <head>
    <title>jQuery Read More/Less Toggle Example</title>
  </head>
  <body>
    <div class="morecontainer">
      <div class="more">
      Lorem ipsum dolor sit amet, consectetur adipisicing </div>
      
    </div>
    <div class="morelink"></div><div class="lesslink"></div>
  </body>
</html>


.morecontainer {
  max-height: 30px;
  overflow: hidden;
  border: 1px solid red;
}
.morelink:before {
  content: "see more";
  font-size: 16px;
  color: red;
  height: 20px;
  width: 100px;
}
.lesslink:before {
  content: "see less";
  font-size: 16px;
  color: red;
  height: 20px;
  width: 100px;
}


$(document).ready(function() {
    $(".morelink,.lesslink").css("display","none");
    if ($('.more').height() < $('.morecontainer').height()) {
      $(".morelink,.lesslink").css("display","none");
    }
    else if ($('.more').height() > $('.morecontainer').height()) {
      $(".morelink").css("display","block");
      $(".lesslink").css("display","none");
    }
    $(".morelink").click(function() {
      $(".morecontainer").css("max-height","none");
      $(".morelink").css("display","none");
      $(".lesslink").css("display","block");
    });
    $(".lesslink").click(function() {
      $(".morecontainer").css("max-height","30px");
      $(".morelink").css("display","block");
      $(".lesslink").css("display","none");
    });
});
````

**Comment by RyanTG** [comment]
@scottwainstock Do you happen to know/remember where the picture thumbnail size is defined? They seem to have a max width of 25px. I don't see that defined in the css, so I'm guessing the js generates them at that size. But I can't find where that's happening.

https://github.com/scottwainstock/pbm/blob/master/app/views/location_picture_xrefs/_show_thumbs.html.haml

If we wanted to resize them, I'm not sure if we'd have to regenerate them all.

**Comment by RyanTG** [comment]
Ooh nevermind. I see that there's a "medium" version already generated. Example: http://s3.amazonaws.com/pbm-images/location_picture_xref/photo/405/medium/GalaxyPinball2.JPG?1389896935

I think I can just work with that.

**Comment by RyanTG** [comment]
Notes:

- Problem when multiple locations are loaded, since the picture div classes are not unique. After giving them unique IDs, I have yet to figure out how to reference those IDs in the javascript. But something like this will probably work: https://github.com/scottwainstock/pbm/blob/master/app/views/location_machine_xrefs/_remove_machine.html.haml#L5

- I probably shouldn't use "if height is greater than" logic, but instead just say, "if there are pictures". Like: `- if (lpx.photo? && lpx.approved?)`. Because this "more" button will be present even if there's just one picture (the basic idea is that part of the thumb will be concealed below a flap, so that the thumb doesn't take up too much real estate).

**Comment by RyanTG** [comment]
@scottwainstock Two questions. 

- I want to add js to this file https://github.com/scottwainstock/pbm/blob/master/app/views/locations/_locations.html.haml. But given that multiple locations can load, I'm not sure where to insert that js. If it's at the end of the file, I don't think I can reference an individual location_id (like `#{l.id}`) because it's outside of the .each loop. Is it ok to insert it somewhere within the .each loop? Maybe I need to call a function within the .each loop, rather than putting the js inline.

- In the js, I want to use the ID(s) of the location(s) being loaded. And it's not working, no matter what I try. The file uses `l`. I've tried a lot of variations of `#{l}`
Maybe it doesn't work because it's outside of the .each loop, and `l` only exists within it.

**Comment by RyanTG** [comment]
@scottwainstock What do you think about this? Here's it in action: https://pinballmap.com/la/?by_location_id=6784

I'll probably tweak it a bit. It doesn't feel perfect to me. I'll probably remove the opacity on the images, for one.
The whole concept (showing the top of the pictures) is a little weird. But in case locations have tons of images (which barely any do), I didn't want them all taking up too much space. Another options is to make the thumbs a little smaller, and completely show the first row of them. And then if there's a second row, THEN add the little "click more" button.

**Comment by scottwainstock** [comment]
I'm torn. On the one hand it looks cool and acts great... on the other hand
it's another CLICK, you know? But in general I'm into it.
