### ISSUE TITLE
merge the location type "bar/club (gay)" into "bar"

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#755]
Seems a little weird to have that be its own category.

**Comment by RyanTG** [comment]
Merge (and delete the old ones):

33 and 38 into 4.

56 and 66 into 20.

27 into 5.

And I'm sure about these ones:
Comic Book Store
Game Room

Aren't game rooms usually also comic book stores (or some other kind of store)?

**Comment by scottwainstock** [comment]
glowing-dusk-5085::COBALT=> select count(*) from locations where location_type_id in (33,38);
 count
-------
    14
(1 row)

glowing-dusk-5085::COBALT=> update locations set location_type_id=4 where location_type_id in (33,38);
UPDATE 14
glowing-dusk-5085::COBALT=> delete from location_types where id in (33,38);
DELETE 2
glowing-dusk-5085::COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT

**Comment by scottwainstock** [comment]
```
glowing-dusk-5085::COBALT=> select count(*) from locations where location_type_id in (56,66);
 count
-------
     9
(1 row)

glowing-dusk-5085::COBALT=> update locations set location_type_id=20 where location_type_id in (56,66);
UPDATE 9
glowing-dusk-5085::COBALT=> delete from location_types where id in (56,66);
DELETE 2
glowing-dusk-5085::COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT
```

**Comment by scottwainstock** [comment]
```
glowing-dusk-5085::COBALT=> select count(*) from locations where location_type_id = 27;
 count
-------
    22
(1 row)

glowing-dusk-5085::COBALT=> update locations set location_type_id=5 where location_type_id = 27;
UPDATE 22
glowing-dusk-5085::COBALT=> delete from location_types where id=27;
DELETE 1
glowing-dusk-5085::COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT
```

**Comment by scottwainstock** [comment]
@RyanTG I think comic book store and game room should be separate.
