### ISSUE TITLE
Accept email address in the resend confirmation field

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#759]
Right now it only accepts username.
https://pinballmap.com/users/confirmation/new

see: https://github.com/scottwainstock/pbm/commit/e3df91597b67a9aab75d053aa89df4c8008f36fa

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/pull/760/commits/a43ae5eac4923d2a4958ecf7a284fe2862385c68

**Comment by bpoore** [comment]
This is still a problem? No guarantees I'll figure it out, but I can give it a look if it hasn't been figured out yet.

**Comment by RyanTG** [comment]
Still a problem. I think I had a PR that I closed after I failed with it.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/4ce60ec55e902d8d7e7b90d06591b6b6a9394efb

**Comment by RyanTG** [comment]
Sweet! Thanks.
