### ISSUE TITLE
Script to standardize state names

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#767]
I know this is really tedious. I've been editing state names so they consistently use abbreviations. But for the ones listed below, there are too many to efficiently update. So I'm hoping for a one time script to fix these. If you gave me to script fu for one of them, I could apply it and do the rest. I could probably look at similar commands you've previously made (like for https://github.com/scottwainstock/pbm/issues/755), but I don't want to fuck it up.

If State = Indiana, change to IN

If State = Maryland, change to MD

If State = Michigan, change to MI

If State = Nebraska, change to NE

If State = New Jersey change to NJ

If State = New Jersery change to NJ

If State = New Mexico change to NM

If State = New York change to NY

If State = North Carolina change to NC

If State = Ohio change to OH

If State = Ontario change to ON

If State = Oregon change to OR

If State = Pennsylvania change to PA

If State = Virginia change to VA

If State = Washington change to WA

**Comment by scottwainstock** [comment]
```
glowing-dusk-5085::COBALT=> update locations set state='IN' where state ilike 'indiana';
UPDATE 41
glowing-dusk-5085::COBALT=> commit;
WARNING:  there is no transaction in progress
COMMIT
```

**Comment by scottwainstock** [comment]
@RyanTG Make sense?

**Comment by RyanTG** [comment]
Yes, thanks!

**Comment by RyanTG** [comment]
Done! Perusing a full data dump allowed me to spot these. I found other types of mistakes, too. It's a nice way to quickly check for consistency.

````
glowing-dusk-5085::COBALT=> update locations set state='MD' where state ilike 'Maryland';
UPDATE 13
glowing-dusk-5085::COBALT=> update locations set state='MI' where state ilike 'Michigan'; 
UPDATE 44
glowing-dusk-5085::COBALT=> update locations set state='NE' where state ilike 'Nebraska'; 
UPDATE 16
glowing-dusk-5085::COBALT=> update locations set state='NJ' where state ilike 'New Jersey';
UPDATE 18
glowing-dusk-5085::COBALT=> update locations set state='NJ' where state ilike 'New Jersery';
UPDATE 4
glowing-dusk-5085::COBALT=> update locations set state='NM' where state ilike 'New Mexico';   
UPDATE 6
glowing-dusk-5085::COBALT=> update locations set state='NY' where state ilike 'New York';
UPDATE 152
glowing-dusk-5085::COBALT=> update locations set state='NC' where state ilike 'North Carolina';
UPDATE 11
glowing-dusk-5085::COBALT=> update locations set state='OH' where state ilike 'Ohio';
UPDATE 24
glowing-dusk-5085::COBALT=> update locations set state='ON' where state ilike 'Ontario';
UPDATE 32
glowing-dusk-5085::COBALT=> update locations set state='OR' where state ilike 'Oregon';
UPDATE 23
glowing-dusk-5085::COBALT=> update locations set state='PA' where state ilike 'Pennsylvania';
UPDATE 39
glowing-dusk-5085::COBALT=> update locations set state='VA' where state ilike 'Virginia';
UPDATE 11
glowing-dusk-5085::COBALT=> update locations set state='WA' where state ilike 'Washington';
UPDATE 6
````
