### ISSUE TITLE
Add google maps api key

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#771]
Google Maps API keys are free as long as we're under 2,500 geocodes a day. And we will be.

[Instructions for obtaining a key](https://stackoverflow.com/a/38049526):

> 1. Under Google Map's Api's choose Google Maps JavaScript API
> 2. Enable the Api.
> 3. Go to credentials section.Choose create Credentials.
> 4. Choose API Key from the popup,and then choose browser key from the proceeding popup.

Then edit [this line in the layout file](https://github.com/scottwainstock/pbm/blob/master/app/views/layouts/application.html.haml#L19) to be: `//maps.google.com/maps/api/js?key=123456ABCDEFG&sensor=true
BUT, should the key be hidden from github?

@scottwainstock Should we do this under your account?

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/9ee81145c5a81cca09bde4551e13ff9d3569751a

**Comment by scottwainstock** [comment]
Having some issues getting this to work in production, still looking into it.

**Comment by scottwainstock** [comment]
@RyanTG Are you using this "sensor=true" param for anything? Having that on is breaking the map when I use an API key.

**Comment by scottwainstock** [comment]
@RyanTG https://stackoverflow.com/a/8618552

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/1a65a941ea6f805b5d6eac8bf74e32160aad2e81

**Comment by RyanTG** [comment]
No. Not using it for nuttin. Console message always said it was
unnecessary.

On Sat, Sep 16, 2017, at 09:14 AM, Scott Wainstock wrote:
> 1a65a94


> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/scottwainstock/pbm/issues/771#issuecomment-329978057

**Comment by scottwainstock** [comment]
@RyanTG OK, should be done now.

**Comment by RyanTG** [comment]
Thanks! Closing. I'll monitor the geocoding.
