### ISSUE TITLE
Footer positioning should follow page length

### ISSUE THREAD

**Issue by scottwainstock** [scottwainstock/pbm#773]
https://pinballmap.com/users/472/profile

... footer seems to be stuck.

**Comment by RyanTG** [comment]
Shoot, I had been dealing with that issue, and had resolved it. But I think I reintroduced it with a later edit.

**Comment by RyanTG** [comment]
https://github.com/scottwainstock/pbm/commit/18cf977adc4bad4e788ee0682d44c946cc436752

`position:relative;` fixes it, but breaks the map. Guess I can include that line on all the non-map pages.

**Comment by RyanTG** [comment]
fixed. https://github.com/scottwainstock/pbm/pull/774
