### ISSUE TITLE
If you edit a Suggested Location, the location type is lost

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#777]
Steps:

- Location is submitted, and a Location Type is included in submission.
- Edit the suggested location (before promoting it). Edit the phone number or something.
- Promote the location.

Outcome: the location type won't be added to the location.

**Comment by RyanTG** [comment]
Plus, if you're editing a suggested location, you can't use the Location Type dropdown. Nothing happens when you click it.

**Comment by scottwainstock** [comment]
@RyanTG Do you still have this issue? I'm not seeing it on my machine.

**Comment by RyanTG** [comment]
Yes, I still experience this. I've tried two browsers.

**Comment by RyanTG** [comment]
Did not experience this using the portland admin. Firefox, windows something.

**Comment by RyanTG** [comment]
@scottwainstock I think you fixed this one, as well, with https://github.com/scottwainstock/pbm/commit/63a1fc04a2f34b564af615da24020e9f8b0e408a#diff-c100f67a0c77b4347d21fc7daeed2dd5R4

**Comment by RyanTG** [comment]
Closing. For the admin category that can edit location type, this field doesn't clear out when you edited a suggested location.
