### ISSUE TITLE
Add "Zone" functionality to "Suggested Locations"

### ISSUE THREAD

**Issue by ericwagericwag** [scottwainstock/pbm#790]
**Background:**
Some (not all) Regions use a field called Zone.  This can denote a wide area such as in the Bay Area Region, where the list of Zones includes San Francisco, East Bay, South Bay, Greater Bay Area North and Greater Bay Area East.  This field is useful for geographic queries in geographically large Regions in cases where a user wants to narrow down their search to a smaller search area than the whole Region.

When Admins receive user submissions for New Locations, the Zone field is not included in the submission.  Further, there is not even a Zone field to manually add to the record when the Admin is reviewing it in Suggested Locations prior to promoting it to an official Location.  So the Admin has to promote the Suggested Location to a full Location without a Zone and then has to edit the Location record to add the Zone.

**Request:**
In Regions which have Zone functionality enabled,...
(A) The user submission form should include a Zone field that users can (optionally) populate when submitting new locations.
(B) The Admin's Suggested Locations screen should list the Zone submitted by the user and enable the Admin to change it.
(C) When an Admin promotes a Suggested Location to a full Location, the Zone field as listed in the Suggested Location screen should be used to populate the Zone field in the new Location record.
(In Regions which do not have Zone functionality enabled, no change is necessary.)

Thanks!

Regards,
Eric Wagensonner

**Comment by RyanTG** [comment]
Thanks, Eric. This is something we've thought about. So thanks for making an issue of it! I'll add this to the pbm-ios and pbm-android projects, too.

Similar to Location Type, it would be a dropdown containing the existing Zones.

**Comment by RyanTG** [comment]
Marking as priority. We need to this before we can add it to the apps.

**Comment by RyanTG** [comment]
Notes to self

https://github.com/scottwainstock/pbm/blob/a5d12695950983809db6244e3b0b622b2393f6bb/app/models/suggested_location.rb

https://github.com/scottwainstock/pbm/blob/82605d613a8cc25acc8119bfadc9c4bdf1c44959/app/controllers/application_controller.rb

Reference: https://github.com/scottwainstock/pbm/blob/696422e868ce91bc5c8e0f29be972ab41cde7d85/app/models/location.rb

Test https://github.com/scottwainstock/pbm/blob/402286df40a8ac2785b3cae0358e849f1d31a1f1/spec/controllers/pages_controller_spec.rb

Test https://github.com/scottwainstock/pbm/blob/7a6ccc1d23c8904cd7809c18b357f2347988bcb6/spec/requests/api/v1/locations_controller_spec.rb

https://github.com/scottwainstock/pbm/blob/7a6ccc1d23c8904cd7809c18b357f2347988bcb6/app/controllers/api/v1/locations_controller.rb

**Comment by RyanTG** [comment]
Passing this on to @scottwainstock to add zone to the api. whatever needs to be done to get the form to work, and "zone" to be included in the email and suggested location, etc.

**Comment by RyanTG** [comment]
Passing back to me! I resolved the first issue I was having, and now the form doesn't error. 

The issue was that I was using `Zone: #{zone ? zone.name : ''}\n` rather than `Zone: #{params['location_zone']}\n` in https://github.com/scottwainstock/pbm/blob/master/app/controllers/application_controller.rb

So I'll keep plugging away.

**Comment by RyanTG** [comment]
Nevermind. I can't get past this. Can't get the fields to show up in rails admin. I'm bowing out.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/b45f287cf25831afe3d889b7c4dfd43fedd6d4e8

This is on staging now.

**Comment by RyanTG** [comment]
The next step will be adding this field to the apps. Not sure if anything first needs to be added to the api for that.

**Comment by scottwainstock** [comment]
@RyanTG API support was added here: https://github.com/scottwainstock/pbm/commit/1357562cc204044ec03dadde93be3197fceb2f00
