### ISSUE TITLE
Some Chicago locations are in Indiana. Move them to the Indiana map

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#795]
I'd guess that some of those locations on the Chicago map are already on Indiana, but some aren't. If so, then not all of them need to be moved. 

First step - delete the dupes.

Filter:

Region contains 'Chicago'
State is exactly 'IN'

27 locations found

Only TwinCade is a duplicate.

**Comment by RyanTG** [comment]
@scottwainstock Since this has come up a few times over the years (and you did it once, but didn't share the sql query or whatever), it might be helpful if I knew how to move a selection of locations into a different region. Can you share a sql query that does this:

Select from region XX all locations in State XY, and move them into region YY

**Comment by scottwainstock** [comment]
This shows you the locations within a region for a particular state.
```
select * from locations where region_id=ID_OF_REGION and state=STATE;
```

This UPDATES the region.
```
update locations set region_id=NEW_REGION_ID where region_id=OLD_REGION_ID and state=STATE;
```

**Comment by RyanTG** [comment]
This will kind of resolve itself come the new app...
Closing.
