### ISSUE TITLE
How to handle deleted users

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#796]
Users can delete themselves via: https://pinballmap.com/users/edit

In user_submissions, we don't track user deletions. 

When a user is deleted, the comments they've made get orphaned or something. I'm not sure what happens exactly, but the result is that all the machines at a location won't render. There might be other issues, too, such as if the user had left a location description.

I'm not sure what the solution is. Perhaps, if a user is deleted, then automatically delete all their comments. Or we can make it so their comments persist but the machines still render.

It would also be cool to have a record of deleted users.

**Comment by scottwainstock** [comment]
```glowing-dusk-5085::HEROKU_POSTGRESQL_COBALT=> select distinct r.name, l.name from location_machine_xrefs x inner join locations l on l.id=x.location_id inner join regions r on r.id = l.region_id left outer join users u on u.id=x.user_id where x.user_id is not null and u.id is null order by 1;
    name    |                name
------------+------------------------------------
 bayarea    | Round Table Pizza (Oakdale)
 chicago    | Peek Inn
 la         | The Slipper Clutch
 pittsburgh | Ace's Break Away & Play (Downtown)
 pittsburgh | Center Pizza
 pittsburgh | Games N At
 pittsburgh | Seven Springs Mountain Resort
 pittsburgh | Sterling Fox
 toronto    | Black Dice Cafe
 toronto    | Unlovable```

**Comment by scottwainstock** [comment]
https://pinballmap.com/nyc?utf8=%E2%9C%93&region=nyc&by_location_id=2571&by_location_name=

Fails.

**Comment by scottwainstock** [comment]
```undefined method `username' for nil:NilClass
  app/views/locations/_render_machine_conditions.html.haml:19:in `block in _app_views_locations__render_machine_conditions_html_haml__1498010851094067915_71701100'```

**Comment by RyanTG** [comment]
Sweet! For the record: Thank you.
