### ISSUE TITLE
If a user adds a high score, then machine is deleted, there's no way to delete the high score

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#806]
For example, this user - https://pinballmap.com/users/2038/profile - added a high score (of 1) to Black Rose at WVU Mountainlair. But that machine is no longer at that location. Since the score is 1, it's obviously a mistake, and I thought I'd delete it (so that it's not visible in his profile). But if I log in as a West Virginia admin, and go to https://pinballmap.com/admin/machine_score_xref that high score listing isn't there. So I can't delete it.

I think it's good that we retain high score for deleted machines. But it would be cool if we could access them within admin.

**Comment by RyanTG** [comment]
Labeled this as Priority since it seems related to https://github.com/scottwainstock/pbm/issues/796

**Comment by scottwainstock** [comment]
@RyanTG That score IS deleted. The profile page reads from UserSubmissions, not machine_score_xrefs.

```glowing-dusk-5085::COBALT=> select * from user_submissions where user_id=2038 and submission_type='new_msx';
  id   | submission_type |                                      submission                                      | region_id |         created_at         |         updated_at         | user_id | location_id | machine_id
-------+-----------------+--------------------------------------------------------------------------------------+-----------+----------------------------+----------------------------+---------+-------------+------------
 24093 | new_msx         | User tjgoad (tjgoad@gmail.com) added a score of 1 for Black Rose to WVU Mountainlair |        74 | 2017-07-12 16:53:03.315073 | 2017-07-12 16:53:03.315073 |    2038 |        5691 |        732
(1 row)```

So, do we make any changes here?

**Comment by RyanTG** [comment]
So, if I deleted it from user submissions it would be deleted from profile? If so, then nom no changes.

**Comment by scottwainstock** [comment]
Y
