### ISSUE TITLE
Dynamically update page title and description based on search results

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#817]
# @scottwainstock TODO

Move the page title/description stuff from:
https://github.com/scottwainstock/pbm/blob/master/app/views/locations/_locations.html.haml
to
https://github.com/scottwainstock/pbm/blob/master/app/helpers/pages_helper.rb

- - -

_Original post..._

**Problem:** 

When you post a location direct link to slack/twitter/facebook/etc, it displays a generic page title/description. Instead, we want it to display location info.

**End Goal:**

Direct links to locations should display a dynamic page title/description that shows location info.

See: https://github.com/scottwainstock/pbm/blob/bfdacb3e256d8a69989b323ca0650b4f333a259c/app/helpers/pages_helper.rb for other dynamic page titles/descriptions.

Like, title = "Kenton Club - Portland Pinball Map"
Description = Kenton Club on Pinball Map! 123 Kenton Blvd, Portland, OR 90210. Kenton Club has 3 pinball machines: Aerosmith (Pro), Monster Bash, Spider-Man.

So:
[Location.name] on Pinball Map! [Location.address]. [Location.name] has [machine.count] pinball machines: [3 machine names, separated by comma].

If machine.count = 1, then say "pinball machine" instead of "pinball machines"

If multiple locations are loaded in the results, then the page title/description should remain generic.

**Comment by RyanTG** [comment]
Also, on user profile page, have the title include the username. Like: `ssw's User Profile`

**Comment by scottwainstock** [comment]
https://stackoverflow.com/a/35195944

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/945de67160328334c16d75d0530acbaec15954e4

**Comment by RyanTG** [comment]
I **see** the location name in the title of the location page.
I **see** the username in the profile page.

I **do not see** the description in the location page.

I'm looking at the source and still seeing "'Find local places to play pinball! The Portland, Oregon Pinball Map is a high-quality user-updated pinball locator for all the public pinball machines in your area.'"

in the description and the og:description (og:description is for facebook/twitter/etc)

**Comment by scottwainstock** [comment]
Can you give me steps to run so I can see the no description thing? I have tests that tell me it’s there, and I have visually confirmed this.

**Comment by RyanTG** [comment]
- load /Portland
- lookup apex (optional, click the permalink for that location)
- then look at the source code and view the description.

What are your steps?

**Comment by scottwainstock** [comment]
Same steps:

<img width="1440" alt="screen shot 2018-03-24 at 8 42 51 pm" src="https://user-images.githubusercontent.com/179757/37871494-02518c6c-2fa4-11e8-8c91-6ec7d528565e.png">

**Comment by RyanTG** [comment]
Well, those are different steps. I was right clicking and viewing Source Code, not inspecting. When viewing source code I wasn't seeing that description. When inspecting, I do see it.

I'm guessing the source code is basically just showing the original page before the location actually loaded.

So then, this is really close to being good. It just needs the `og:title` and `og:description` to show the same content as the `title` and `description`. Sorry that I didn't specify that in the issue. The og stuff is obnoxious, but pretty important for SEO and stuff.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/0dd3347f93e5223d7e798f9434faefa8a6412f18

**Comment by RyanTG** [comment]
Awesome! I think this is a significant update, in terms of impact. 

I might mess with the description content, now that this is setup. Might be cool to list machines in there.

**Comment by RyanTG** [comment]
Ha, actually I spoke too soon (about it being significant). Because the page first loads without a location, and then the location loads a second later, the bots that pull out page title/description only see the initial information. They don't see the new title/description.

**Comment by RyanTG** [comment]
Description = Kenton Club on Pinball Map! 123 Kenton Blvd, Portland, OR 90210. Kenton Club has 3 pinball machines: Aerosmith (Pro), Monster Bash, Spider-Man.

So:
[Location.name] on Pinball Map! [Location.address]. [Location.name] has [machine.count] pinball machines: [3 machine names, separated by comma].

If machine.count = 1, then say "pinball machine" instead of "pinball machines"

**Comment by RyanTG** [comment]
Lil update that gets the wanted text: https://github.com/scottwainstock/pbm/pull/878/commits/d649e75c68520568826f2f5e7cd0049010ee6bf3

To do: 
I'm going to move the profile part OUT of pages_helper.rb, because I don't think I did that correctly. 
Then I'm going to fix a test.

Then I'll leave it up to you to move everything into pages_helper.rb because I think that's beyond me.

**Comment by RyanTG** [comment]
OK, one thing left on this Issue.

Move the page title/description stuff from:
https://github.com/scottwainstock/pbm/blob/master/app/views/locations/_locations.html.haml
to
https://github.com/scottwainstock/pbm/blob/master/app/helpers/pages_helper.rb
