### ISSUE TITLE
If a direct location link is loaded, update that url after an additional search is made

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#818]
For example, if a user goes to https://pinballmap.com/portland/?by_location_id=7451

But then after that they search for another location, right now the url stays the same. Instead, it should update to the reflect the new search.

If we added this, I guess we'd have to update the url even if someone starts at https://pinballmap.com/portland/ and does a search from there...

https://stackoverflow.com/questions/824349/modify-the-url-without-reloading-the-page/3354511#3354511

**Comment by bpoore** [comment]
Might be a bit hacky, but I think this does the trick: https://github.com/scottwainstock/pbm/pull/820.  Let me know if something seems off. I'm currently unable to run the test suite on my machine.

**Comment by RyanTG** [comment]
For our records, these are the options for searching:

````
It supports "by_location_id", "by_type_id", "by_zone_id", "by_machine_id", and "by_city_id".

You can pass multiple ids to each of those params, you just join the ids together with an underscore. (EXCEPT for "by_city_id". That only takes one id, and it's a city name)

So, and example of what I'm talking about is here:
http://www.pinballmap.com/portland/?by_location_id=3261_3803

You can combine types too. So, here is a search for all bars in Portland that have Family Guy or Attack From Mars.

http://www.pinballmap.com/portland?by_location_type_id=4;by_machine_id=664_643
````

I actually forgot about the underscore and the combining options. Pretty cool

**Comment by RyanTG** [comment]
Just noting this here: Once this issue is done, then this functionality will be unnecessary https://github.com/scottwainstock/pbm/blob/master/app/views/locations/_locations.html.haml#L8

**Comment by RyanTG** [comment]
I tried my hand at one of the failed tests, and I couldn't conquer it. For some reason - https://github.com/scottwainstock/pbm/blob/5ccb016561948011b3e29149db85a48ea91e4e2e/spec/features/location_machine_xrefs_controller_spec.rb#L578 - that test results in a really fractured page where only the js portion of this flie loads (https://github.com/scottwainstock/pbm/blob/master/app/views/locations/_locations.html.haml) and that's it! I don't get why, nor do I get how to fix it.

On another note, I'll be curious to see how to include the other search options (by_machine_id etc) in https://github.com/scottwainstock/pbm/pull/820/commits/7427b281c43960573a485e1c612d698d0593d4a2#diff-fa8f01f5d887696c8f6f532050299719R65. It seems to work if you substitute one in for another, but I don't know how to include multiple search options at once.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/167e22bfacd5f30b864da02af47fe7b3fd5b6593

**Comment by RyanTG** [comment]
Seems great! Thanks.
