### ISSUE TITLE
Include "Locations removed" in the weekly email

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#823]
Just a number. `# location(s) removed`

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/286dfe8f3dc7a28ac1d22199116151b56e6cb6b2

@RyanTG We'll need to build up a full week of deletes before the number is accurate. I did this with "user submissions".

**Comment by RyanTG** [comment]
Seems good!
