### ISSUE TITLE
Allow profile URL to support username

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#834]
Instead of just the user id in the URL, can it also use usernames?

**Comment by scottwainstock** [comment]
https://github.com/norman/friendly_id
https://stackoverflow.com/questions/37671409/how-to-get-friendly-id-gem-get-working-with-rails-5-0-0-rc1

**Comment by scottwainstock** [comment]
This should do it: https://github.com/scottwainstock/pbm/commit/5fa3c998385f5ffbb01d48c1de36f313bf7414fc

**Comment by RyanTG** [comment]
Sweet.
