### ISSUE TITLE
Suggested Location - super admin - When editing location, region changes to Albuquerque

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#836]
Super admins can change the region of a suggested location. It's a drop down. But when you go to the Edit screen, the drop down automatically selects the first item in the list rather than just staying on the current region.

It would be cool if it didn't change to a different selection unless you specifically do it.

**Comment by scottwainstock** [comment]
@RyanTG Yeah I think I fixed this with https://github.com/scottwainstock/pbm/commit/63a1fc04a2f34b564af615da24020e9f8b0e408a#diff-c100f67a0c77b4347d21fc7daeed2dd5R4
