### ISSUE TITLE
"Operator" field is not always being passed from Android Suggested Location submission form

### ISSUE THREAD

**Issue by ericwagericwag** [scottwainstock/pbm#847]
**Background**
When a User suggests a New Location, they fill out a form with the location's details -- name, address, website, operator, etc.  When the Suggested Location is submitted, it's added to a queue of Suggested Locations for the Region's Admin(s).  An Admin then reviews and promotes to a full Location.

One user claimed to have filled in the Operator field, but the Suggested Location came through to the Admin without an Operator listed.  In trying to find the problem, I think it is related to Android Suggested Location screen.

In the Web Suggested Location screen, the Operator field is a drop down list.  The User can leave it blank or choose one of the existing Operators, but cannot submit an Operator that is not on the drop down list.  However on the Android Suggested Location screen, the Operator is a free form field.  The user can type anything they want.

In testing the functionality, it seems that if the user uses Android to submit an Operator with the exact spelling of an existing Operator, that information will be passed through to the Suggested Location screen that the Operator will see.  However, if the submitted Operator is not an existing Operator, the data will be deleted with no warning.

**Notes**
(1) This was tested on the Web interface and on the Android interface.  But I do not have an iPhone, so I don't know how it works there.
(2) I did not test and do not know whether capitalization affects the match between a submitted Operator and an exiting Operator.

**Request**
To fix this problem, there are a few options...
(1) Change the Android Suggested Location submission form to include a drop-down list of the Operators associated with the region.  [This is probably the best option, if it is feasible.]
(2) Add a validation rule so that after a user submits a location, the Operator field is checked.  If it is not a match, give the user a message listing existing operators for a location and a "Pick One of These" prompt.  [Less preferred option.]
(3) Pass the data to the Admin on the Suggested Location screen, perhaps with a flag indicating it is not a match.  [Less preferred option.]

Thanks!

**Comment by RyanTG** [comment]
Thanks, Eric. We actually have fixed this on Android, but we haven't released the upside yet. See https://github.com/scottwainstock/pbm-android/pull/191

(Also note that the android app has its own github project page)

In that update we made the field an dropdown, and based on our testing it seems to work!

We're working on some back end code updates right now, but well release the android update soon!


And yes, this issue also exists on the iOS app. But we haven't fixed it yet. https://github.com/scottwainstock/pbm-ios/issues/153

**Comment by ericwagericwag** [comment]
Thanks Ryan!  Hope the baby is well!




----- Original message -----

**Comment by RyanTG** [comment]
Thanks, Eric! All is going great.

I'm going to close this issue because the fix is pending on android.
