### ISSUE TITLE
Do not geocode location submissions if some fields are blank

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#848]
Sometimes people submit locations with empty fields. Even when those fields are empty, the address is still geocoded. This means that the lat/lon coordinates are wrong. When you correct the address, they coordinates are not updated.

So I think we need to ONLY geocode the original submissions if they contain certain fields, like address, city, zip. Otherwise, don't (and leave the lat/lon fields blank).

**Comment by RyanTG** [comment]
Possible solution - something related to cutting this out https://github.com/scottwainstock/pbm/blob/82605d613a8cc25acc8119bfadc9c4bdf1c44959/app/controllers/application_controller.rb#L79

**Comment by scottwainstock** [comment]
Maybe this?

https://github.com/scottwainstock/pbm/commit/81e19c9a9a09cbc4ebab8f1c3ce49773b3d3e5f2

**Comment by RyanTG** [comment]
After thinking about it more, I think it's OK if State and Zip are missing. First off, State is almost never missing (on the website it's a dropdown - though it's not on the app). And second off, the geocoder is smart enough to fill in those blanks if Address and City are present.

I'm not sure if simply deleting `|| state.nil? || zip.nil?` would cut it here, or if that would break something. So I'll leave it up to you.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/fb18134f575d11520d0df2a9f332df3fca6ebf19

**Comment by RyanTG** [comment]
I think we need to revert this.

When submissions aren't geocoded, and then I fill in the necessary fields, the geocode then fails 100% of the time. I've replicated it about 15 times. I don't really know why, and I don't know if reverting this issue will solve the problem. But it's something to test.

**Comment by RyanTG** [comment]
I reverted this locally and geocoding still doesn't work. 

It fails when I create a new location. Fails when I edit a suggested location. Can't get it to work at all!

**Comment by RyanTG** [comment]
I'm closing this, because I think the issue is something else...

I'll start a new issue.
