### ISSUE TITLE
Staging: Rails admin - some dropdowns in edit screen are not working

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#853]
**Where: Fields**

Editing a suggested location: region
Editing a location: zone

This MAY only be a problem for super admins... But I don't have access to a non-super admin in staging.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/63a1fc04a2f34b564af615da24020e9f8b0e408a

This is on staging now. I tested it locally with regular/super admin and it seemed good. Another pair of eyes couldn't hurt though. Big-ish change.

**Comment by RyanTG** [comment]
Sweet! I'll check it tonight.

**Comment by RyanTG** [comment]
I can't access https://pinballmapstaging.herokuapp.com/admin/suggested_location

I'm logged in as tzr. 

The page is empty. It doesn't say "model not found" or anything. the other models seem to work (did not try them all).

Also, if rails admin on localhist is any indication, you may have also fixed this issue https://github.com/scottwainstock/pbm/issues/836

On localhost, the model loads, and the dropdowns work great.

**Comment by RyanTG** [comment]
Not cutting it for me. I've even restarted my computer (had to anyway). 

Do you still have plans to deploy tonight? If so, I think it's fine to do so. I looked on localhost (though only for a minute), and everything seemed great.

**Comment by scottwainstock** [comment]
Not going to deploy tonight, N. I might try tomorrow.

**Comment by RyanTG** [comment]
Cool, I'll do more testing tomorrow then.

**Comment by RyanTG** [comment]
Is this fixed for you on live? I know it was on staging.

But on live I'm still not able to use the dropdown for Location Type.

**Comment by scottwainstock** [comment]
@RyanTG This is working for me right now. Which object are you seeing location type's dropdown not work?

**Comment by RyanTG** [comment]
https://www.pinballmap.com/admin/suggested_location/1587/edit

Must be a browser/something issue for me.

**Comment by scottwainstock** [comment]
<img width="1440" alt="screen shot 2018-03-20 at 8 34 43 pm" src="https://user-images.githubusercontent.com/179757/37693625-26a51972-2c7e-11e8-8a17-294c9c290e41.png">

**Comment by RyanTG** [comment]
![screenshot_20180320_203634](https://user-images.githubusercontent.com/632682/37693673-835c6e9a-2c7e-11e8-95a8-00cde90eef1c.png)

I also just discovered that for super admins, I can choose Operators and Zones, but the values are for the super admin's "home" region. Like, for user pbm, the values are for Los Angeles operators and zones.

**Comment by RyanTG** [comment]
Logged in as:

- `pbm` (super admin) - can't edit location type
- `rom` (admin, but with machine and region editing capabilities - so maybe not a totally regular admin but not a super, either?) - CAN edit location type
- `rmainsd8` (regular admin for redding region) - can't edit location type
- `pinballmap` - (seems to have same privileges as rom) - CAN edit location type
- `rover` (regular admin) - can't edit location type

So, so far the only user that can edit location type on suggested locations is the one that has region/machine editing capabilities. I'm confused because we have three categories of admins.

**Comment by scottwainstock** [comment]
This is what I see for a non-super admin, non-portland user:

<img width="1440" alt="screen shot 2018-03-21 at 10 01 00 pm" src="https://user-images.githubusercontent.com/179757/37752105-623670b4-2d53-11e8-8f64-61c0023c624d.png">

**Comment by RyanTG** [comment]
What about for a suggested location? That's where the problem is. Location type when editing suggested location, non super admin.

Sorry, this thread is sort of chaotic.

**Comment by scottwainstock** [comment]
OK well how about this then?

https://github.com/scottwainstock/pbm/commit/5ac4005093bcfb3f9c3f6415ab187f06a61b4a8e

**Comment by RyanTG** [comment]
Yesssssssssssssssss!
