### ISSUE TITLE
On admin/location_picture_xref show original size and not thumb

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#863]
When admins need to approve a photo, it's kind of a hassle to just see a micro thumbnail that you then need to expand. Often, users submit multiple photos, some of which are the same, and admins often approve duplicates because it's takes more work to identify that they're dupes.

**Comment by scottwainstock** [comment]
This makes the image show at original size: https://github.com/scottwainstock/pbm/commit/291a248cfcefb3b6697a34b958ea0cbeb9443390

**Comment by RyanTG** [comment]
Nice!
