### ISSUE TITLE
Activate admin History papertrail

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#868]
https://github.com/sferik/rails_admin/wiki/History

**Comment by scottwainstock** [comment]
We already had that line in our config.

I think maybe the DASHBOARD view is gone? I'm seeing history on the individual objects. There's a little tab called "history". 

https://pinballmap.com/admin/location/history

**Comment by RyanTG** [comment]
Alrighty. That seems just as good. Though I definitely did more today than it's showing. I wonder why those other actions - changing lat/long of existing locations - isn't on there.
