### ISSUE TITLE
Stern Army flag for locations

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#873]
- Create a flag on locations for Stern Army (super admin can flag when editing location)
- Add it to API

The goal is for Stern to use the API to pull location info for all their Stern Army spots.

We could also include the ability to show that info in the location description. Kind of like how we show Location Type.

Stretch Goal would be to have it as a search param so that you could click a link and it would spit out all stern army locations in the region. Kind of like `by_type_id=`. `stern_army=1` 
We wouldn't add it as a lookup option, but we might want to make the text in the location details a clickable search - just like how we have location type as a clickable search in the location details (or we might want to list the link elsewhere, like on the region intro section).

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/166f1d0eb826f6534722384f66bab113bc94d48b

**Comment by scottwainstock** [comment]
Didn't do the stretch goal, but it's not a large follow-up once we want to surface it via a FE search. API search works.

**Comment by RyanTG** [comment]
Closing. And we can add additional related issues at our leisure.

They will be:

- Stretch Goal would be to have it as a search param so that you could click a link and it would spit out all stern army locations in the region. Kind of like by_type_id=. stern_army=1
We wouldn't add it as a lookup option, but we might want to make the text in the location details a clickable search - just like how we have location type as a clickable search in the location details (or we might want to list the link elsewhere, like on the region intro section).

- We'll probably need a "regionless" location endpoint.
