### ISSUE TITLE
Allow other phone formats

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#883]
What format do they use? At least three different ones...

+61 7 3846 5622
+61 423 122 189
+61 13 24 68

**Comment by RyanTG** [comment]
Existing `/\A(\(\d{3}\) |\d{3}-)\d{3}-\d{4}\z/` see https://github.com/scottwainstock/pbm/blob/master/app/models/location.rb#L7

So, we need something like `\+61 [0-9] [0-9]{4} [0-9]{4}`

`/(\d{1})(\d{1})(\d{1})/` maybe? just making notes here...

**Comment by RyanTG** [comment]
`/(\d{1} \d{4} \d{4})|(\d{3} \d{3} \d{3})|(\d{2} \d{2} \d{2})/`
and with +61

**Comment by RyanTG** [comment]
I think this is screwing with the Australian formats: `ActionController::Base.helpers.number_to_phone(new_phone)`

What is this thing doing? Seems to be overwriting the formatting, so that it's ###-###-####. So the Australian formats don't work here because of this.

**Comment by scottwainstock** [comment]
I'm using this: https://github.com/daddyz/phonelib

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/e1eb5d6fd1d2e46fe50943262788ab5cfbf0f50c

**Comment by RyanTG** [comment]
Seems good. I successfully added Australian, British, and Norwegian phone numbers. I was only able to add them via the web map - got an invalid phone error when trying to add them from rails admin.
