### ISSUE TITLE
Geocoding only works on Submitted locations; not new locations nor when editing suggested

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#884]
**Problem:** Locations are not being geocoded in some cases.

**Details:**

Geocoding consistently works:
- When users submit a location, the location gets properly geocoded as long as the required fields are present.

Geocoding rarely (or perhaps never) works:
- When admins a new location (not referring to promoting a suggested location).
- When admins edit a suggested location that didn't geocode. Like, if a location was submitted with an incomplete address and thus wasn't geocoded, if the admin then corrects the address and presses save, they'll see an error that the address still isn't geocoded.

I'm not good at troubleshooting this... unsure about any errors while testing it on local.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/79e38774aec8591470a5e0f1541ad106a93a2817

This worked for me when I:
submitted a new location with a good address
submitted a new location with a BAD address and manually updated it
created a new location as an admin

**Comment by RyanTG** [comment]
Seems great!
