### ISSUE TITLE
Home page - state_name containers with all that state's regions nested within it

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#889]
**Goal:**
Have an "outer" div that wraps around a state name and all the regions within that state.

Currently looks like this:

````
<div class="state_name">
  <span class="state_name">Arizona</span>
</div>
<div class="region_name">
  <a href="/phoenix">Phoenix</a>
</div>
<div class="state_name">
</div>
<div class="region_name">
  <a href="/tucson">Tucson</a>
</div>
````

There's no hierarchy. The state_name div only contains the name of the state, and the regions within that state are in their own separate divs, not nested within the state name.

Would like to see:

````
<div class="state_name_container">
  <div class="state_name">
    <span class="state_name">Arizona</span>  
  </div>
  <div class="region_name">
    <a href="/phoenix">Phoenix</a>
  </div>
  <div class="state_name">
  </div>
  <div class="region_name">
    <a href="/tucson">Tucson</a>
  </div>
</div> <!-- end state_name_container -->
````

Something to that effect. And do that for each state.

Also, the
````
  <div class="state_name">
  </div>
````
doesn't need to exist if there's nothing in it.

Let me know if that needs more clarification.

**Comment by scottwainstock** [comment]
@RyanTG I'm confused still, I guess. It looks like you just put a div around the entire loop. And, that's super easy and I know you know how to do that, so I feel like I'm missing something.

**Comment by scottwainstock** [comment]
@RyanTG Oh you want one container for each state... but I think the fact that you put a "stateless region" in your example is throwing me off. That shouldn't be in its own container?

**Comment by RyanTG** [comment]
That's not a stateless region - that's the second Arizona region. That's how the loop looks right now - only the first region has the state name, and all the subsequent regions have an empty `<div class="state_name"></div>`. So I was just trying to show how it looks.

But like I mentioned, those don't need to be there in the version I'm envisioning. And here's what that would look like:
````
<div class="state_name_container">
  <div class="state_name">
    <span class="state_name">Arizona</span>  
  </div>
  <div class="region_name">
    <a href="/phoenix">Phoenix</a>
  </div>
  <div class="region_name">
    <a href="/tucson">Tucson</a>
  </div>
</div> <!-- end state_name_container -->
````

**Comment by scottwainstock** [comment]
Like this? https://github.com/scottwainstock/pbm/commit/aec34ac2434fb40282c59b12330e37334b315e4a

**Comment by RyanTG** [comment]
Yesssssssssssss!

Thank you.
