### ISSUE TITLE
Remove "Link to this Search Result"

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#894]
No longer necessary now that the url shows the search. Assigning self.

**Comment by RyanTG** [comment]
This? https://github.com/scottwainstock/pbm/commit/5f800672f75aaafa1fefaec3e48c29667421861a#diff-f476c17fe3f7a40e40fc45e7ee6d7a3fR20

This is only for newer browsers?

**Comment by scottwainstock** [comment]
Exactly, yeah. That's only available for HTML5 enabled browsers. So maybe
we can leave the old thing around for super old browsers? I dunno, just a
thought. No MASSIVE loss to ditch it entirely.

**Comment by RyanTG** [comment]
Let's just keep it for now.
