### ISSUE TITLE
Admin - super user - error when selecting user "region is present"

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#901]
Also errors when selecting "region is blank"

**Comment by scottwainstock** [comment]
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: ""
LINE 1: ...sers.region_id IS NOT NULL AND users.region_id != '')) ORDER.

**Comment by scottwainstock** [comment]
This should do it: https://github.com/scottwainstock/pbm/commit/27f1cd04c54c66af6a4f206227c3b6129cd142cf

The filters won't work, but there are two buttons to click to see this:
<img width="1430" alt="screen shot 2018-08-07 at 9 23 31 pm" src="https://user-images.githubusercontent.com/179757/43816200-61997564-9a88-11e8-9e86-0f6f3f56b520.png">

**Comment by RyanTG** [comment]
Seems GREAT.
