### ISSUE TITLE
Get rid of approval process for pictures

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#917]
Once photo uploads are allowed in the app, I think we should just allow them to go through without approval.

First we would need to fix the issue with the website that allows users to upload the same pic multiple times in a row. I’ll look into that to figure out why it’s happening. 

We might also consider allowing users to delete their own photos.

**Comment by RyanTG** [comment]
Labeling this as priority, since we're going to have more regions w/o admins soon.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/3b9092a942567a7a97a7e545cf0de5ce06d98831

**Comment by RyanTG** [comment]
Awesome! I like how it reloads the location.

I think an additional issue would be to show a "loading" gif while it's uploading.

**Comment by RyanTG** [comment]
What happened to the unapproved photos? Did they get automatically approved during this transition, or were they deleted?
