### ISSUE TITLE
Regionless: region-agnostic location submission form

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#928]
(I might be misusing the word "agnostic" right now)

Create a functioning submission form that isn't in a region folder path (aka https://pinballmap.com/suggest). 

On the form, include an _optional_ "region" dropdown list, where they may choose to submit the location to a particular region. If they don't include that field, it goes to the super admin.

**Comment by scottwainstock** [comment]
I'll have it go to the super admin for now, I think we should do a follow-up task to send it to the admin within a "bounding box" of the lat/lon of the location.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/5ec8e869b907138d170cf992ffd6eedabcf8a398

**Comment by scottwainstock** [comment]
https://pinballmap.com/suggest
