### ISSUE TITLE
Allow admins to delete pictures

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#933]
Right now admins can not approve a picture, but they can't delete them from the system. With so many duplicate pictures, it would be great if admins could clean the list by deleting some of them.

**Comment by RyanTG** [comment]
If this is non-trivial, then forget it.

**Comment by scottwainstock** [comment]
It's trivial.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/3f68e1d598f32143cc359e65688db64c0e6e3d91

**Comment by RyanTG** [comment]
Thanks!
