### ISSUE TITLE
Regionless: Autocomplete location also shows %like% results

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#934]
Steps:

- Lookup by location name
- Type "Harkin"
- There will be two autocompleted results. One is "Harkins Theatres" and the other is "Harkins Theatres Metrocenter 12"
- If you choose "Harkins Theatres" It shows results for both. Like, even though you choose an autocomplete, it still thinks you are doing a %like% search (I think this is because on the regional maps when you choose an autocomplete, the item then moves into the dropdown list, so it's clear that you're specifically choosing just that item).

This makes it so you can't always pick a specific location without extra locations showing up in the results.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/154294e8b4e4670814dce4a0efefbc78422c9e6e

**Comment by scottwainstock** [comment]
Need to do a little more here.
