### ISSUE TITLE
Regionless - "Link to this search result" always links to https://pinballmap.com/regionless

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#939]
I think we can either remove this (related: https://github.com/scottwainstock/pbm/issues/894) and make it so the URL updates as you search (as it does on regions) - or we could fix this link.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/4c11f01d308a41c606cd7cdbee2fd77bc41e3f86
