### ISSUE TITLE
Regionless: Clear definitions of how the search criteria should work

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#941]
If you have more than one of the lookup fields populated, the search will either ignore one of them or produce a "not found" error (let me know if I am wrong in any way - I haven't been able to manage a search where two parameters are used). 

Solution for now would be to clear out the other two lookup fields when you conduct a search.

Currently:

- If the machine field is populated, and you do a Location search, the machine field gets cleared.
- and vice versa.

So that's good, but it's only two use cases.

**Comment by RyanTG** [comment]
Wait, did I misinterpret you, @scottwainstock, when you said this is an mvp? I pasted in the title, but is the description something different?

**Comment by scottwainstock** [comment]
What I meant here is that we should figure out all the use-cases for the CURRENT search functionality... that is MVP. For example:
* You should be forced to search by SOMETHING
* If the machine field is populated, and you do a location search, the machine field is cleared
* If the location field is populated, and you do a machines search, the location field is cleared

... maybe better worded in one-bullet point, "you can only search using one field at a time... blank out other fields when you enter data in a new one"

Any other ones we need to account for?

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/71ad046d9a534fc06f396ed49e2c911f45d9428f

This accounts for the two bulletpoints above. Anything else we need?

**Comment by RyanTG** [comment]
I think that’s it.

**Comment by scottwainstock** [comment]
Search by address + machine:
https://github.com/scottwainstock/pbm/commit/b56a16706785c0d2dd1e86d0044395a716798738
