### ISSUE TITLE
Regionless: show region name in location details

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#949]
Seems like a nice thing to have.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/44b58a589712b184f6ca0617ae67c6db76e11ee7

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/e49ef9a1df977448b458e26d0decc900c8b5f062
