### ISSUE TITLE
When there are multiple results, display # of results

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#950]
In the results (region and regionless) say “x number of locations in results”..

Sometimes it’s tough to know if you’ve 5 or 20..

**Comment by RyanTG** [comment]
![57c662a5-52cb-4c0a-b834-bd573eaf1fe3](https://user-images.githubusercontent.com/632682/42856701-41a8be2e-89fb-11e8-8245-0fdeaea1aabb.jpeg)

**Comment by scottwainstock** [comment]
Does it: https://github.com/scottwainstock/pbm/commit/1e188c732bb0928f4506b193e56aa23055cdf5c0

**Comment by RyanTG** [comment]
Awesome! Thanks. 

I’ll style it a bit.
