### ISSUE TITLE
Regionless: tracking cities/locations to be moved to regionless

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#959]
Track which cities/locations should be changed to regionless. And change them when the app update is released.

- Dayton, OH
- Marion, OH (and probably more of Ohio...)
- Oregon coast
- Salem, OR
- Palm Springs
- Adirondack Pizza
- Lotta spots on the philadelphia map are far outside the city.

**Comment by syracusepinball** [comment]
All locations in Upstate NY
Watertown
Black River
Ilion
Old Forge
Binghamton
Elmira
Vestal
Watkins Glen
New York Mills
Yorkville
Endwell
Ithaca

**Comment by RyanTG** [comment]
Regions without admins - should they be dropped?

If so:

- Charlottesville

**Comment by RyanTG** [comment]
I tightened up the Toronto region.
Gonna do Seattle now.

@syracusepinball I removed all the cities in your list from the Syracuse map. Thanks!
