### ISSUE TITLE
Regionless Location search: include city, state in autocomplete

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#960]
Include `(City, State)` in the autocomplete for location names (similar to how we include man/year for machine name autocomplete)

**Comment by RyanTG** [comment]
I think this is the commit that added year/man to machine autocomplete https://github.com/scottwainstock/pbm/commit/6eec5b86dd13485befc73d4f7bcfbfe20b34f395

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/ec88a52fa9bf93970f964b9421eefbfcc7dc9d9a

**Comment by RyanTG** [comment]
Really cool!
