### ISSUE TITLE
RSS for regionless locations

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#962]
Would be nice to have these updates hit the feeds.

**Comment by scottwainstock** [comment]
https://pinballmap.com/location_machine_xrefs.rss

**Comment by RyanTG** [comment]
Reopening just to give myself this task:

https://github.com/scottwainstock/pbm/blob/20a81d883a381cb6f090ee92fd88d1f3a03b1eae/app/views/location_machine_xrefs/index.rss.builder#L14

needs an `else` for regionless

**Comment by RyanTG** [comment]
I'm going to further tweak the title to something like

````
xml.title ["#{machine.name} #{machine.year_and_manufacturer} was added to #{location.name} in #{location.city} #{cloned_lmx.last_updated_by_username.empty? ? '' : 'by ' + cloned_lmx.last_updated_by_username}", location.region ? "(location.region.full_name Pinball Map)" : ""].join('')
````

REOPENING.
