### ISSUE TITLE
Regionless location digests

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#963]
It would be cool to have:

~~A daily digest of regionless comments~~
~~A daily digest of regionless removals~~
(this would work instead: https://github.com/scottwainstock/pbm/issues/1017)

A weekly digest of regionless stats

The ability to auto-delete empty regionless locations once a week (this could be on for all regionless locations)

**Comment by scottwainstock** [comment]
@RyanTG Do you want this or #1017?

**Comment by RyanTG** [comment]
Both? I crossed out the redundant ones on here. 

This issue is about: Daily - all
The other issue is about including regionless in the weekly digest.

**Comment by scottwainstock** [comment]
These should do it for #963: https://github.com/scottwainstock/pbm/commit/32b8d73dc818611bb8b7b5c095825440632ee1d7

**Comment by RyanTG** [comment]
Did you get this? I didn’t (nor the all region digest - not sure if the regionless locations have been added to that email, or if it’ll be a separate one). Maybe it coincided with the site going down?
