### ISSUE TITLE
Machine Search in Add Location Not Working

### ISSUE THREAD

**Issue by applbaum** [scottwainstock/pbm#965]
When adding a new location through the web the machine search returns no results.  When the search box is empty the machine list returns "Too many objects." As soon as you start typing the name of a machine nothing is displayed in the results at all.  Case doesn't matter and typing the full name of the machine also doesn't return results.

**Comment by scottwainstock** [comment]
Hi @applbaum,

Is this still an issue for you? I'm not able to repeat it. If you are still seeing it, can you let me know what OS/browser/browser version you're using? Here's what I see in OSX/Chrome/67.0.3396.99:

<img width="778" alt="screen shot 2018-08-02 at 9 03 05 pm" src="https://user-images.githubusercontent.com/179757/43623748-b229d770-9697-11e8-885a-0e7254ec2823.png">

**Comment by applbaum** [comment]
Hi Scott,

Yes, I still am seeing this issue.  Win10/Chrome/67.0.3396.99

If it matters -- I don't see the "Add a new machine" button at all.

[image: image.png]

Also, I thought the podcast you guys put out was great!  Keep up the good
work.

Let me know if you need me to test again.


Thanks,
Lyle

**Comment by scottwainstock** [comment]
@applbaum Thanks for the podcast feedback. It's fun, we'll keep doing it.

As far as this problem goes... I just changed my account permissions to match yours and stuff still worked, so no luck there.

Would it be possible to get Chrome console output when you type in the box? That might give us a clue.

**Comment by RyanTG** [comment]
````
rails_admin-f1f6ad95005c88a1baf75505d338ce4065931219e516750cee55ba92d17384dc.js:3 GET https://pinballmap.com/admin/machine?associated_collection=machines&compact=true&current_action=create&source_abstract_model=location&query=medi 500 (Internal Server Error)
send @ rails_admin-f1f6ad95005c88a1baf75505d338ce4065931219e516750cee55ba92d17384dc.js:3
ajax @ rails_admin-f1f6ad95005c88a1baf75505d338ce4065931219e516750cee55ba92d17384dc.js:3
_query @ rails_admin-f1f6ad95005c88a1baf75505d338ce4065931219e516750cee55ba92d17384dc.js:15
u.isFunction.o.(anonymous function) @ rails_admin-f1f6ad95005c88a1baf75505d338ce4065931219e516750cee55ba92d17384dc.js:4
_queryFilter @ rails_admin-f1f6ad95005c88a1baf75505d338ce4065931219e516750cee55ba92d17384dc.js:14
u.isFunction.o.(anonymous function) @ rails_admin-f1f6ad95005c88a1baf75505d338ce4065931219e516750cee55ba92d17384dc.js:4
(anonymous) @ rails_admin-f1f6ad95005c88a1baf75505d338ce4065931219e516750cee55ba92d17384dc.js:14
setTimeout (async)
(anonymous) @ rails_admin-f1f6ad95005c88a1baf75505d338ce4065931219e516750cee55ba92d17384dc.js:14
dispatch @ rails_admin-f1f6ad95005c88a1baf75505d338ce4065931219e516750cee55ba92d17384dc.js:2
_.handle @ rails_admin-f1f6ad95005c88a1baf75505d338ce4065931219e516750cee55ba92d17384dc.js:2
````

**Comment by scottwainstock** [comment]
This should do it: https://github.com/scottwainstock/pbm/commit/93b927baabeb78a09e4a4c336214cefd5b19f185

@applbaum @RyanTG One more try, please.

**Comment by RyanTG** [comment]
Works great for me!

**Comment by applbaum** [comment]
Working perfectly now!

**Comment by scottwainstock** [comment]
Awesome. Sorry that took so long to push through.
