### ISSUE TITLE
Trouble adding new machine name via the map

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#973]
When you add a new machine _via the map_ it gets stuck on “loading”. Refresh the page and the machine won’t have been added to the location, but it will be available as an existing machine

If you then add another new one, it will act like it works (refreshes the list of machines), but this newest machine isn’t actually added. So then you have to refresh the page and try again (and then it gets stuck on "loading", and so you need to refresh the page again, etc...)

**Comment by scottwainstock** [comment]
@RyanTG In a dev checkout, this worked fine for me. Went to http://localhost:3000/portland/?by_location_id=3212 ... clicked on ADD MACHINE... entered "This is a new machine." into the machine name textbox.... clicked ADD. Machine gets added to location.

Did I do a step wrong?

**Comment by RyanTG** [comment]
You did it correctly. And I just tested it on dev and live and it worked. So...
