### ISSUE TITLE
"Redo results when map is moved?" pops you from /region to /regionless

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#979]

**Comment by scottwainstock** [comment]
This seems to have done it: https://github.com/scottwainstock/pbm/commit/08b8852d51b8946ce9783daaa5195a7b8097d025

**Comment by RyanTG** [comment]
Reopening. This is back.

**Comment by scottwainstock** [comment]
https://github.com/scottwainstock/pbm/commit/2c4f6b7aac5a033e595828a5f17d7a4999fadda6

**Comment by RyanTG** [comment]
Thxoxo
