### ISSUE TITLE
On /regionless, not all regional locations say “Region: region_name”

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#981]
Example below (search Roanoke, VA on regionless). The first two results don’t say Roanoke in the location details. But the last two do! 

https://pinballmap.com/regionless?utf8=✓&by_machine_id=&by_location_id=&by_machine_name=&address=Roanoke%2C+VA&by_location_name=

**Comment by scottwainstock** [comment]
This should do it: https://github.com/scottwainstock/pbm/commit/d7735ffa506ca1a1d311977b8f85f9d040708acf
