### ISSUE TITLE
Include location type for /locations/closest_by_address.json and /locations/closest_by_lat_lon.json requests

### ISSUE THREAD

**Issue by bpoore** [scottwainstock/pbm#983]
<img width="831" alt="screen shot 2018-06-28 at 8 27 28 am" src="https://user-images.githubusercontent.com/7720282/42045566-af676276-7ab0-11e8-8f34-d5fd2c4c55a0.png">

**Comment by scottwainstock** [comment]
@bpoore It looks like we already do that, did I miss something?

https://pinballmap.com/api/v1/locations/closest_by_address?address=97203
https://pinballmap.com/api/v1/locations/closest_by_lat_lon?lat=45.584318;lon=-122.742234;send_all_within_distance=1

**Comment by bpoore** [comment]
Nope. My bad!  :(
