### ISSUE TITLE
More Suggested Location automation

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#996]
- Detect when a website doesn't have `http://` and add it.
- Default country to United States if it isn't filled in (or include country as part of initial geocode).

I think those are the two most common slowdowns right now.

**Comment by scottwainstock** [comment]
This should do it for both: https://github.com/scottwainstock/pbm/commit/89fceac7f64cb743c5ba33d23dddf47a7ae68075

**Comment by RyanTG** [comment]
A location was submitted and the http wasn’t added. But the country is getting added.

**Comment by RyanTG** [comment]
Shootersbilliardclub.com

Capitalized like that. Just to confirm, the http would be added when the location is submitted, and not when it’s promoted, right?

**Comment by RyanTG** [comment]
The country isn’t defaulting to US, either. I was wrong when I previously said it was.

**Comment by scottwainstock** [comment]
I think this will do it: https://github.com/scottwainstock/pbm/commit/0430868051f6e63ea0124acc7058da91371aee60

**Comment by RyanTG** [comment]
Country field seems good.

Website field is adding "http://" when there's no website entered.
Should it be 
````
self.website = "http://#{website}" if website.blank? && website !~ /\A#{URI.regexp(%w[http https])}\z/
````

**Comment by scottwainstock** [comment]
Close... we want !website.blank? but I think that'll be a rubocop
failure. And we need to add a test. I can put that stuff in.

**Comment by RyanTG** [comment]
I edited my comment and had `!website.blank?`.

**Comment by scottwainstock** [comment]
OK man, OK.

**Comment by RyanTG** [comment]
LET THE RECORD STATE that ryan kind of got something right on his third edit.

**Comment by scottwainstock** [comment]
Maybe this: https://github.com/scottwainstock/pbm/commit/0f52126faa68dbe649ae3c79bb96bd964ae963bb

**Comment by RyanTG** [comment]
Seems good.
